### ISSUE TITLE
request: better nullable support

### ISSUE THREAD

**Issue by connor4312** [gogo/protobuf#102]
For our use case, we don't need to know if values are undefined in most cases, so the nullable option is nice and leads to much cleaner code.

Unfortunately nullable right now is only available right now as a field option. It'd be great to have a `nullable_all` option, and perhaps `nullable_required` as well (so that required fields are not nullable).

**Comment by awalterschulze** [comment]
I would recommend using a vanity binary, like protoc-gen-gogofaster (same as gogofast, without XXX_unrecognized, less pointer fields).
You could even roll your own the code is pretty easy, see
https://github.com/gogo/protobuf/blob/master/protoc-gen-gogofaster/main.go
As you can also see in the code there are many exceptions to nullable=false for all fields and I don't know if I have flushed them all out yet.
Does this help?

**Comment by awalterschulze** [comment]
Please reopen if my answer was not satisfactory.

**Comment by connor4312** [comment]
Sorry, I forgot to reply. This looks good. Thanks!

**Comment by awalterschulze** [comment]
Cool no problem :)
