### ISSUE TITLE
Vote For New Feature: generate getter for `oneof` when no type repeats

### ISSUE THREAD

**Issue by tamird** [gogo/protobuf#103]
See discussion in https://github.com/cockroachdb/cockroach/pull/2481/files#r39291843

This would bring back the convenience of `onlyone` in the presence of the new `oneof` implementation.

**Comment by tamird** [comment]
It would be super cool if the user could specify a return type other than `interface{}`, too.

**Comment by awalterschulze** [comment]
Wow I did not realise how useful onlyone is/was.
I think generating such a getter and setter is definitely on the table, but as usual I would prefer to have the user enable this with an extension and some vanity binary.
Basically oneof would need its first extension which can also be called onlyone.
Basically onlyone is going to generate almost exactly the same code as before
GetValue and SetValue, but only for:
  - the messages with one oneof and 
  - in which that oneof only has fields of different types and 
  - in which the extension is enabled.

**Comment by awalterschulze** [comment]
In the meantime you could always just not use oneof yet and use messages with optional fields and the onlyone extension as is.

**Comment by tamird** [comment]
Looking at this again after #168 and after having implemented a few options myself, I think we should go ahead and do it using an option (and allow the user to specify the argument/return type of the setter/getter).

**Comment by awalterschulze** [comment]
Thats interesting :)

Ok so you specify the fieldname of the setter?

And what types who you specifiy as the getter return type?

**Comment by tamird** [comment]
Well you have a name on the `oneof`, so the setter/getter would be called `{Set,Get}OneOfName`.

Normally the type would have to be `interface{}`, but in some cases (e.g. in CockroachDB) all members of the `oneof` may implement a common interface which can be used as the type. In effect, I'm suggesting that it should be possible to generate [this method](https://github.com/tamird/cockroach/commit/5abcff4cc8e00de49e3abe06753754fae7f28fa3#diff-060e95a3a2839243f16cfc13837a5913R223).

**Comment by awalterschulze** [comment]
Ok I understand the getter thats cool, it safes another type assertion.
So Set would be.
```
func (ru RequestUnion) SetInner(r Request)  {
...
}
```

**Comment by tamird** [comment]
Yep, the singular version of [this](https://github.com/tamird/cockroach/commit/5abcff4cc8e00de49e3abe06753754fae7f28fa3#diff-a00f8e8d4c1367cb94d8b42cd41d9b51R165).

**Comment by awalterschulze** [comment]
Ok @dennwc what do you think of this?

**Comment by awalterschulze** [comment]
I think the discussion is stuck in 
https://github.com/gogo/protobuf/issues/168
