### ISSUE TITLE
optimization: messages in a oneof wrapping struct do not need to be pointers

### ISSUE THREAD

**Issue by tamird** [gogo/protobuf#106]
From https://github.com/golang/protobuf/issues/78:

> See: https://github.com/golang/protobuf/blob/535a10468679b4cf155f6a7afdf53b554633fc09/proto/testdata/test.pb.go#L2031
> There's no need for this to be a pointer, since the union interface is implemented for a pointer of the wrapping struct. The downside of using a pointer here is that it results in an additional allocation.

**Comment by awalterschulze** [comment]
Basically this would be done by allowing nullable=false for oneof fields that are of type struct.  I hope David changes his mind.

**Comment by tamird** [comment]
@awalterschulze shall I try to work up a PR for this?

**Comment by awalterschulze** [comment]
That would be great, but lets first wait to hear what David says.
I think https://github.com/gogo/protobuf/issues/103 would be easier and give you more bang for you buck right now.

**Comment by awalterschulze** [comment]
I think the discussion is stuck in 
https://github.com/gogo/protobuf/issues/168
