### ISSUE TITLE
import "fmt" two times in proto3 generated code

### ISSUE THREAD

**Issue by mwitkow** [gogo/protobuf#107]
After upgrading to head, when generating `proto3` with `gogoslick` we're getting a double import for `fmt`:

```go
import proto "github.com/gogo/protobuf/proto"
import "fmt"
import math "math"

import "fmt"
import "strings"
```

This unfortunately causes it not to compile.

**Comment by awalterschulze** [comment]
Ok I am really sorry, that really sucks.
Could you please provide an input proto file that reproduces this error?

**Comment by mwitkow-io** [comment]
Apologies for the delay, I'll cook up a repro case over the weekend :)

**Comment by awalterschulze** [comment]
That will be great Thank you :)

**Comment by awalterschulze** [comment]
Ok I am going to close this issue, but once you have an example please reopen this issue.

**Comment by gyuho** [comment]
@awalterschulze We have the same issue here:

```proto
syntax = "proto2";
package etcdserverpb;

import "gogoproto/gogo.proto";

option (gogoproto.marshaler_all) = true;
option (gogoproto.sizer_all) = true;
option (gogoproto.unmarshaler_all) = true;
option (gogoproto.goproto_getters_all) = false;

message Request {
	optional uint64 ID         =  1 [(gogoproto.nullable) = false];
	optional string Method     =  2 [(gogoproto.nullable) = false];
	optional string Path       =  3 [(gogoproto.nullable) = false];
	optional string Val        =  4 [(gogoproto.nullable) = false];
	optional bool   Dir        =  5 [(gogoproto.nullable) = false];
	optional string PrevValue  =  6 [(gogoproto.nullable) = false];
	optional uint64 PrevIndex  =  7 [(gogoproto.nullable) = false];
	optional bool   PrevExist  =  8 [(gogoproto.nullable) = true];
	optional int64  Expiration =  9 [(gogoproto.nullable) = false];
	optional bool   Wait       = 10 [(gogoproto.nullable) = false];
	optional uint64 Since      = 11 [(gogoproto.nullable) = false];
	optional bool   Recursive  = 12 [(gogoproto.nullable) = false];
	optional bool   Sorted     = 13 [(gogoproto.nullable) = false];
	optional bool   Quorum     = 14 [(gogoproto.nullable) = false];
	optional int64  Time       = 15 [(gogoproto.nullable) = false];
	optional bool   Stream     = 16 [(gogoproto.nullable) = false];
}

message Metadata {
	optional uint64 NodeID    = 1 [(gogoproto.nullable) = false];
	optional uint64 ClusterID = 2 [(gogoproto.nullable) = false];
}
```

with git SHA `df65e0b667d9cb6578785fc18df94b089d320d91`

file is here https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/etcdserver.proto

And script is here https://github.com/coreos/etcd/blob/master/scripts/genproto.sh


Any idea?

Thanks!

**Comment by gyuho** [comment]
I found out the commit that introduced this.

On this commit https://github.com/gogo/protobuf/commit/30a1e8b92028bc88272062936ad57fae7aa2f6f9, I get 

```
# github.com/coreos/etcd/storage/storagepb
storage/storagepb/kv.pb.go:24: fmt redeclared as imported package name
	previous declaration at storage/storagepb/kv.pb.go:18
# github.com/coreos/etcd/raft/raftpb
raft/raftpb/raft.pb.go:29: fmt redeclared as imported package name
	previous declaration at raft/raftpb/raft.pb.go:23
# github.com/coreos/etcd/lease/leasepb
lease/leasepb/lease.pb.go:23: fmt redeclared as imported package name
	previous declaration at lease/leasepb/lease.pb.go:17
# github.com/coreos/etcd/snap/snappb
snap/snappb/snap.pb.go:23: fmt redeclared as imported package name
	previous declaration at snap/snappb/snap.pb.go:17
```

But before this, I don't.

Thanks,

**Comment by awalterschulze** [comment]
I struggle to reproduce this issue, but I get problems when I use ",import_prefix=github.com/coreos/" and don't do all the sedding.
Maybe this example could be minimized a little to something I can use as a test in the future?

**Comment by gyuho** [comment]
@awalterschulze Sorry, I just dumped a lot of code on you. I will come up with some
easy way to reproduce not specific of our use case. Thanks!

**Comment by awalterschulze** [comment]
Thank you that will be great :)
Please open a new issue then.

**Comment by gyuho** [comment]
Sure I will. You can close this if you want to. Thanks!

**Comment by mwitkow** [comment]
We have a similar issue when using `import_prefix`. 

It seems that gogo_slick (latest head) generates a `import "my_prefix/fmt"` and `import "fmt"` separately.

```
import fmt "fmt"
import math "math"
import _ "improbable.io/proto/_go/github.com/mwitkow/go-proto-validators"
import google_protobuf1 "improbable.io/proto/_go/google/protobuf"

import fmt "improbable.io/proto/_go/fmt"
import strings "improbable.io/proto/_go/strings"
```

That's with 
`--gogoslick_out=plugins=grpc,import_prefix=improbable.io/proto/_go

**Comment by awalterschulze** [comment]
Ok thats a new one :)
I'll look into it.

**Comment by awalterschulze** [comment]
Sorry I have been a little under the weather.
Is it possible to provide an example .proto file?

**Comment by awalterschulze** [comment]
no example proto provided, closing
