### ISSUE TITLE
generated code for grpc is broken

### ISSUE THREAD

**Issue by antmanler** [gogo/protobuf#110]
This is due to
https://github.com/grpc/grpc-go/pull/370

and this commit on golang/protobuf

https://github.com/golang/protobuf/commit/3d2510a4dd961caffa2ae781669c628d82db700a

**Comment by awalterschulze** [comment]
Done
https://github.com/gogo/protobuf/commit/200875106f3bf0eb01eb297dae30b250a25ffc84

**Comment by awalterschulze** [comment]
Thanks for reporting :)

**Comment by antmanler** [comment]
Cool, thank you for your great work!

**Comment by awalterschulze** [comment]
My pleasure. Thanks for the complement :)
