### ISSUE TITLE
Merge some utilities

### ISSUE THREAD

**Issue by peter-edge** [gogo/protobuf#112]
So I just started reading through this, so funny enough I have some utilities I maintain on top of golang/protobuf at go.pedge.io/proto - I'm not sure how many are useful, but if a maintainer of this project wants to take a quick look, I'm happy to send pull requests to merge some of that functionality.

**Comment by awalterschulze** [comment]
I am struggling to see what you have made.
This project's docs could use some work, but I'll be happy to just get an explanation from you.

I know about this one, 
https://github.com/peter-edge/go-google-protobuf
since this is what is holding gogoprotobuf back from having full proto3 support, but I am waiting to see what golang/protobuf does.

**Comment by peter-edge** [comment]
Haha :) Ya so documentation is lacking, most/all of these packages were created in support of other projects, and I never got around to a full README or package documentation (although all public structures have basic godoc, although sometimes it's along the lines of "Version is the version").

So, in lieu of me getting my act together on that, let's go through them:

**prototime**: Timestamp/Duration utilities (timestamp.proto and duration.proto)

**protostream**: Utilities around `google.protobuf.BytesValue` for streaming RPC calls. Creates an `io.Reader` and `io.Writer` for generated clients and servers (ie if you have functions of the form `rpc Foo(stream google.protobuf.BytesValue) ...` or `rpc Foo(...) returns (stream google.protobuf.BytesValue) {} `). Also has a relayer that allows for having a local wrapping client from a server.

**protoplugin**: Utilities for writing protoc golang plugins. Used at https://github.com/peter-edge/go-protolog/blob/master/cmd/protoc-gen-protolog/main.go. Should probably be replaced with https://github.com/golang/protobuf/tree/master/protoc-gen-go/generator.

**protoprocess**: A library to remotely modify a local directory. Sends a local directory to a protobuf rpc service as an archive, processes it, and returns the modified contents.

**protorpclog**: This is a wrapper around go.pedge.io/protobuf in lieu of method interceptors (see https://github.com/grpc/grpc-go/pull/349). Example usage: https://github.com/peter-edge/go-openflights/blob/master/log_api_server.go. This could be not hardcoded to protolog and made more generic.

**prototest**: Sets up a suite that provides a a given number of grpc servers and connections. Kind of hacky, so unlikely of interest.

**protoversion**: defines a message `protoversion.Version`, which has a major, minor, micro, and additional version on it. Also defines a service with `GetVersion`, and a google.api.http binding at `get /version`. This can be used for attaching simple versions to protobuf services. Examples: https://github.com/peter-edge/go-openflights/blob/master/openflights.go https://github.com/pachyderm/pachyderm/blob/master/pachyderm.go. Both of these use the `protoserver` package to attach a the service to a server https://github.com/peter-edge/go-proto/blob/349662dd857bab46d77b0f6296840a91b0cb33cb/server/protoserver.go#L82 but I doubt `protoserver` is of interest.

**protoclient**: creates a cobra command for get version

** protoserver**: a do-all for serving insecure grpc servers. This is really more of a personal package so unlikely of interest.

I'm not sure what would be useful or not, but offering my help, let me know :)

**Comment by awalterschulze** [comment]
Don't worry I am not really into over documenting.
I just commented on the fact that there is not enough documentation if you are going to point someone to that repo and ask them to figure it out.

A lot of these projects are more grpc related.  
I hope those can stay as orthogonal tools.

I especially like the idea of protostream.  That is a really cool idea.

prototime might also be useful in future.
Lets first see what golang/protobuf does with those new proto types and then talk about possibly merging those two.
How does that sound?

**Comment by peter-edge** [comment]
Ya sounds great, just let me know :) Ya my bad on the docs, I'll make it
better in the next week so the next time I link to it it's not so bad
:) prototime is definitely more interesting once we resolve the well known
protobuf types issue. Protostream - I want to make this
non-google.protobuf.BytesValue-specific, which I believe will benefit from
a code generation tool, but if I get there I'll let you know.

And of course let me know if I can be of help otherwise. :)

**Comment by awalterschulze** [comment]
You are welcome to look through the issues and see if there is something you would like to help with.

I am going to close this issue.
We'll talk about this again once golang/protobuf has done something about the new proto types.
