### ISSUE TITLE
Generate idiomatic Go names

### ISSUE THREAD

**Issue by cespare** [gogo/protobuf#114]
(Searched but couldn't find any previous discussion.)

Would you be interested in accepting a patch which adds a new extension for generating more idiomatic Go names wrt initialisms? For example:

```
message QpsStats -> struct QPSStats
client_id -> ClientID
```

I was thinking of using [this list that golint uses](https://github.com/golang/lint/blob/master/lint.go#L702-L739) as the basis.

Thanks for your consideration!

**Comment by awalterschulze** [comment]
Currently you can use customname to manually change each field name, but there is no way to change the message name.  If we had that extension, then we would have two options to proceed.

1) Make a vanity binary which traverses the file descriptor set and automatically adds those extensions to the fields and messages that need linting.

2) Make another file level extension that could be turned on and off for each file.  This might be hard.

Personally I am not a fan of go lint.
I think go vet and go fmt are enough.

The first thing to do would be to check if it would be possible to have a message extension that changes the message name and plays well with all the other extensions.

Or you could skip that and simply make a vanity binary that only changes the field names.  That should be pretty easy.

**Comment by cespare** [comment]
Thanks for the feedback! I like the vanity binary approach the most. I'll give it a shot.

(We've been having trouble with using any extensions since importing the gogo proto file makes our generated java not compile. Haven't had a chance to figure that out yet.)

For the record, we don't want this feature in order to satisfy golint; we want the generated code to look more like our handwritten code.

**Comment by awalterschulze** [comment]
We are using the imported gogoproto extensively with java.  It should not be a problem its just hard getting the proto paths and classpaths right.

But if you are starting to use gogoprotobuf then I would recommend the vanity approach, since it just makes everything simpler :)

Making it look like handwritten code is a cool goal.

**Comment by awalterschulze** [comment]
Please reopen if this is still an issue

**Comment by cespare** [comment]
This is still an issue, but I cannot reopen it.

I took your approach and it was easy enough to fix field names by automatically adding a `Customname` extension as appropriate: https://github.com/cespare/gogo/blob/master/cmd/protoc-gen-gogogo/main.go

But I don't see any extensions that will allow me to change message or enum names. Any suggestions?

**Comment by awalterschulze** [comment]
Yes, so what you have there will work for fieldnames, but as I have mentioned before to change message names you would need to create another extension and first test to see it that will play well with all the other extensions in gogoprotobuf.  The same would go for enums.
After the extension is created you could again adjust your vanity binary to also change the message names.

**Comment by ecnahc515** [comment]
It seems like copying the list of `commonInitialisms` from golint would be enough to reduce the need for `Customname` by quite a lot.

The list: https://github.com/golang/lint/blob/master/lint.go#L702

**Comment by awalterschulze** [comment]
Its good to have a link to the list here :)

**Comment by cespare** [comment]
@awalterschulze FYI for expediency I ended up doing the enum/message name modifications by parsing the output Go code and doing the renaming there. I still think this would be a good feature for gogoprotobuf.

**Comment by awalterschulze** [comment]
We are slowly working on it https://github.com/gogo/protobuf/issues/149
Could you maybe post your solution online.
I think you will get quite a few users.

**Comment by cespare** [comment]
Ah, thanks for the pointer! I hadn't seen the new issue.
