### ISSUE TITLE
embedded message containing oneof: generated test fails

### ISSUE THREAD

**Issue by andres-erbsen** [gogo/protobuf#115]
syntax = "proto3";
        package proto;
        import "gogoproto/gogo.proto";

        option (gogoproto.populate_all) = true;
        option (gogoproto.equal_all) = true;
        option (gogoproto.testgen_all) = true;

        message Foo {
                Bar bar = 1 [(gogoproto.embed) = true];
        }

        message Bar {
                oneof pick {
                        bool a = 11;
                        bool b = 12;
                }
        }

        // protoc --version
        // > libprotoc 3.0.0
        // go get -u github.com/gogo/protobuf/protoc-gen-gogo
        // protoc --gogo_out=. -I . -I $GOPATH/src/github.com/gogo/protobuf test.proto && go test
        // > --- FAIL: TestFooProto (0.00s)
        // > panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        // >    panic: runtime error: invalid memory address or nil pointer dereference
        // > [signal 0xb code=0x1 addr=0x0 pc=0x483ce8]
        // >
        // > goroutine 5 [running]:
        // > testing.tRunner.func1(0xc82009e000)
        // >    /usr/lib/go/src/testing/testing.go:450 +0x171
        // > github.com/andres-erbsen/coname-mit/proto.(*Foo).XXX_OneofFuncs(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        // >    <autogenerated>:10 +0x28
        // ...

**Comment by awalterschulze** [comment]
This should fix the problem.
https://github.com/gogo/protobuf/commit/735a7119638333b86cc87394bbac13e670fd5427

Good catch :)
Thank you for reporting.
