### ISSUE TITLE
casttype ignored when generating maps in proto2?

### ISSUE THREAD

**Issue by smarterclayton** [gogo/protobuf#116]
The following proto2 IDL

```
// LimitRangeItem defines a min/max usage limit for any resource that matches on kind.
message LimitRangeItem {
  ...

  // Max usage constraints on this kind by resource name.
  map<string, k8s.io.kubernetes.pkg.api.resource.Quantity> max = 2 [(gogoproto.nullable) = false, (gogoproto.customname) = "Max", (gogoproto.casttype) = "ResourceList"];

  ...
}
```

where `ResourceList` is `map[string]*resource.Quantity`.  That results in the following Go code:

```
// LimitRangeItem defines a min/max usage limit for any resource that matches on kind.
type LimitRangeItem struct {
	// Max usage constraints on this kind by resource name.
	Max map[string]*k8s_io_kubernetes_pkg_api_resource.Quantity `protobuf:"bytes,2,rep,name=max,casttype=ResourceList" json:"max" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}
```

with protoc 3.0.0 and gogoprotobuf 2093b57

I would assume that the map type in the Go struct should be using the alias - and that the generated unmarshaller would cast to it, but that is not the case:

```
// unmarshal
mapvalue := &k8s_io_kubernetes_pkg_api_resource.Quantity{}
if err := mapvalue.Unmarshal(data[iNdEx:postmsgIndex]); err != nil {
	return err
}
iNdEx = postmsgIndex
if m.Max == nil {
	m.Max = make(map[string]*k8s_io_kubernetes_pkg_api_resource.Quantity)
}
m.Max[mapkey] = mapvalue
iNdEx = postIndex
```

Perhaps I should not be attempting to use map with proto2 (although I noticed that there is a test for it in proto2 syntax, so I was unsure what the exact support was).

**Comment by smarterclayton** [comment]
As context, I'm trying to generate IDLs that adhere closely to existing types so that I can provide an IDL and Marshaller that is compatible with the existing internal types - in this case the use of aliases complicates the generation process, so I wanted to understand whether this was just a bug, or something that is fundamentally difficult to implement in gogo/protobuf

**Comment by awalterschulze** [comment]
Ok wow, well lets see what features we can add to gogoprotobuf :)
The interoperability of maps and the other gogoprotobuf features are definitely lacking.

Is go2idl a tool that converts a go struct to its proto idl or other?
It would be great if this was a thing where the roundtripping between go2idl and gogoprotobuf stabilizes at some point, but that might be a little idealistic.
Point is I am really in favour of making canonical go structs better as it hopefully eliminates the need to copy from the struct you want in your api to the struct you need to be able to serialize, which can be very expensive.

**Comment by awalterschulze** [comment]
golang/protobuf supports proto2 maps, so gogoprotobuf does too :)
https://github.com/golang/protobuf/blob/master/proto/testdata/test.proto#L476

**Comment by awalterschulze** [comment]
Are you saying that casttype already works in proto3?

**Comment by smarterclayton** [comment]
go2idl is a tool we're working on to support any sort of struct driven generation as a refactor of the tools we've built elsewhere piecemeal in Kubernetes (to generate conversions between different versioned Go structs, to generate deep copies, etc).  

Under go2idl I've been working on taking a Go struct -> protobuf IDL (that can then result in 100% compatible Go structs and marshaling) -> marshalers that work with our existing marshalers. I've got a few hundred fairly complex and idiomatic Go structs roundtripping (gogo's generated Go struct is identical to the source struct), just hitting the last issues with maps.

This and #117 and #118 are related - this was the clearest example of "I expected the generator to support this already" i.e. a bug instead of "I would like a new feature to make generating canonical Go structs easier" i.e. features.

I'm happy to submit a PR to fix this, just wanted to be sure there wasn't something catastrophically obvious I was missing.

**Comment by awalterschulze** [comment]
Ok wow, do you intend on release go2idl as a separate tool?

I would really appreciate a PR, since I am going to be quite busy for the following month.
If you don't have time I could always start working on this then.

**Comment by awalterschulze** [comment]
Sorry for not supporting this already.  I took a bit of a shortcut with maps and oneof.

**Comment by smarterclayton** [comment]
I think so yes.  It just happens to live under the Kube repo right now for iteration.  I will look to send a PR - thanks.  

Oneof is something I need to look into for proto3 (I fell back to proto2 for now) to properly handle pointers to types internally - I'd want to be able to define a rough `OneOf { type, null }` like the proto3 json serialization does and then expect to get back a go struct with `*type`.  At first glance it seemed a harder problem so I punted for now.

**Comment by awalterschulze** [comment]
I had a pipe dream about such a tool, so it will be amazing to see it actually be THING :)

oneof is a proto2.6 feature, but I see what you mean.

I don't know if oneof (type, null) will work.
Where did you see the proto3 json code use that?
I want to read that code.

There is always gogoproto.nullable=true, but I think it will require quite a bit of work.
Do your go structs really contain structs with fields that are pointing to native values?
I have found these to be quite rare.

I think proto2 is still going to be with us for a WHILE. 
You could probably get away with not supporting proto3.  
Or at least only supporting proto3 for cases where the user does not have native type pointers.

**Comment by smarterclayton** [comment]
We use pointers to primitive types very heavily to handle defaulting on API types (difference between *int64 nil and 0), so unfortunately it's on almost every struct :)
