### ISSUE TITLE
Support for key and value type casttype on maps?

### ISSUE THREAD

**Issue by smarterclayton** [gogo/protobuf#117]
I would like to be able to alias key and value types on maps via `casttype`, to allow the generated Go struct to have a strongly typed key and value.  Is this something that you would accept a PR for?

For instance, turn this IDL:

```
  // Max usage constraints on this kind by resource name.
  map<string, k8s.io.kubernetes.pkg.api.resource.Quantity> max = 2 [(gogoproto.casttype.key) = "ResourceName", (gogoproto.customname) = "Max"];
```

into Go

```
  Max map[ResourceName]resource.Quantity
```

Is there an alternative way to approach generating output like that?

**Comment by awalterschulze** [comment]
I will gladly except such a pull request.
How about we call the two new extensions castkey and castvalue?

**Comment by smarterclayton** [comment]
`(gogoproto.castkey)` and `(gogoproto.castvalue)`?

**Comment by awalterschulze** [comment]
yes if that also makes sense to you?

**Comment by awalterschulze** [comment]
I believe this can now be closed :)
