### ISSUE TITLE
Service code generation for grpc plugin with gofast doesnt work?

### ISSUE THREAD

**Issue by kunaljham** [gogo/protobuf#122]
The example in the `readme.md` for the service code generation for the grpc plugin is state as:
`protoc --gofast_out=plugins=grpc:. my.proto`

However, the command above generates the messages but not the service definition for the following example:
https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/testdata/grpc.proto

The following command, however, generates the appropriate interfaces for the service:
`protoc --gogo_out=plugins=grpc:. my.proto`

Is that because gofast does not support the grpc plugin?

**Comment by awalterschulze** [comment]
I think the grpc plugin should be working with gofast.
It is a possible bug.
I'll check it out asap (monday).

**Comment by kunaljham** [comment]
perfect - thanks @awalterschulze!

**Comment by awalterschulze** [comment]
I tried
```
cd protoc-gen-gogo/testdata/
protoc --gofast_out=plugins=grpc:. grpc.proto
```
And I got
```
...
type Test_DownstreamClient interface {
...
func NewTestClient(cc *grpc.ClientConn) TestClient {
```
Seems like it is working.

Are you sure you have the newest version?

**Comment by awalterschulze** [comment]
Please reopen if this is really an issue
