### ISSUE TITLE
Extensions problem

### ISSUE THREAD

**Issue by dennwc** [gogo/protobuf#123]
I've tried to disable one of the extensions and got the following error:
```
types.proto:5:8: Option "(gogoproto.sizer_all)" unknown.
```
File types.proto looks like this:
```proto
syntax = "proto3";

package types;

option (gogoproto.sizer_all) = false;

message MyType {
    uint32 size = 1;
}
```
And command:
```
protoc --gogoslick_out=. types.proto
```

What am I doing wrong? I also tried to update gogoproto and protoc itself, but the problem remains.

**Comment by awalterschulze** [comment]
You need to import gogoproto.proto

**Comment by awalterschulze** [comment]
Like in the example.proto
https://github.com/gogo/protobuf/blob/master/test/example/example.proto

protoc does not know about gogoslick.  It requires the import of gogoproto to be able to parse gogoproto.sizer.  The parsed protocol buffer descriptor is then passed to gogoslick which edits the descriptor to add those extensions without needing to parse them.

**Comment by awalterschulze** [comment]
I hope this helps. 
If not just reopen the issue.

**Comment by dennwc** [comment]
Thanks! That fixed the problem.

**Comment by awalterschulze** [comment]
my pleasure :)
