### ISSUE TITLE
Proposal: Add an option to ignore message for code generation

### ISSUE THREAD

**Issue by dennwc** [gogo/protobuf#126]
Proto3 spec says that `bytes` and `message` types are binary compatible. I think it could be used to declare a custom type in a following way:
```proto
message MyType {
  // this should mean "skip code generation for this type entirely"
  option (gogoproto.is_custom) =  true;
}
message Msg {
  MyType custom = 1;
}
```
instead of
```proto
message Msg {
  bytes custom = 1 [(gogoproto.customtype) = "MyType"];
}
```
Effect from both variant is the same - lib will not complain about the custom type, but generated code will contain references to it. But the proposed approach has an advantage: other proto files can import and use MyType as if it was a real proto message.

**Comment by awalterschulze** [comment]
Well how would a non go client unmarhsal that.
Basically all the bytes would go into MyType's unrecognized field, which does not exist in proto3, so it will just be thrown on the floor.

**Comment by dennwc** [comment]
Oh, sorry, I forgot that proto3 has no support for unrecognized fields.

How about this example:
```proto
message MyType {
  option (gogoproto.ignore) =  true;
  string name = 1;
}
```
It's not usable for types like `[n]byte`, but will work for struct types.

And lets rephrase the proposal then: Add an option to ignore type for code generation.

It can be still useful for Go clients. With that option a can firstly generate a type with `ignore=false`, move it to separate file, customize the type and set `ignore=true`. Other clients will still have a list of fields for `MyType` while Go will unmarshal it in a different way (maybe just store as private fields, or rearrange data in a special way).

**Comment by awalterschulze** [comment]
Couldn't you achieve the same thing by simply putting MyType in a separate proto file which you can import, but not generate code for?

**Comment by dennwc** [comment]
I haven't considered it. Seems like it will work. Sorry for disturbing)

**Comment by awalterschulze** [comment]
No problem, glad I could help :)

**Comment by dennwc** [comment]
The only downside I found so far is that it tries to import the package and `MyType` becomes `pkg.MyType`. But this can be fixed with sed in go:generate.

**Comment by awalterschulze** [comment]
MyType should become pkg.MyType and pkg should be imported.
But know you can write your MyType code in pkg instead of having the generated go code.
