### ISSUE TITLE
Allow message to be generated with lowercase name / unexported.

### ISSUE THREAD

**Issue by byrnedo** [gogo/protobuf#127]
Is there any appetite for having some way to generate a struct as unexported?

My use case is that I need to wrap my protobuf generated structs to add some setters/cusom functionality.
I would rather that I did this in the same package and that the generated structs were not exported (began with lowercase).
Otherwise this could be confusing to users of this package.

Thoughts?

**Comment by awalterschulze** [comment]
You could obviously embed those structs in a new private structure and have the proto structure in a separate package, but you are saying that, that is what you are trying to avoid, right?

```
type Wrapper struct {
  protoMsg protoPkg.MyMessage
}

func (this *Wrapper) SetCustom() {
...
}
```

**Comment by awalterschulze** [comment]
I think adding private fields would also require generating setters and appenders.
I think it would be very hard, but maybe I am wrong.

**Comment by byrnedo** [comment]
Yeah your example was what I was after. 
After thinking about it a bit more, like you say, it gets messy since if the inner struct were unexported, one would have to have quite verbose NewWrapper(...) functions to populate the embedded struct.

**Comment by awalterschulze** [comment]
So would you like to close the case and/or bounce some more ideas?

go likes the idea of internal packages for this use case.
I am not a fan, but if you really want to limit the way people use your code for very strictly compatible APIs, I guess it makes sense.

**Comment by byrnedo** [comment]
For the most part this is all because I want to add a setter to my messages, so that I can create an interface.
I see that setters have been proposed and shot down before based on complexity.

**Comment by awalterschulze** [comment]
Yes, but I think gogoprotobuf is now at a place where we can talk about adding setters again.
But we will need someone who wants or has already implemented it to discuss some of the pros and cons

**Comment by byrnedo** [comment]
Wrong button there :/

yeah, I would like to limit the usage but like I say it's just because I need a setter.

I know that dropbox have a fork with setters ( https://github.com/dropbox/goprotoc ) though not very active right now.

**Comment by byrnedo** [comment]
I can close it if you want, is there another forum to discuss this on?

**Comment by awalterschulze** [comment]
No this is fine :)

Yes I was trying to get them to contribute it now that I am more open to the idea, but they are quite busy.

**Comment by awalterschulze** [comment]
Once you introduce a feature, everyone starts using it in the most unforeseen ways.  So I try to only implement complete features.  But to be fair I haven't always succeeded.

**Comment by awalterschulze** [comment]
Ok I have to go, but we'll talk more on Monday.

**Comment by byrnedo** [comment]
I can understand that. 

Ok, have a good weekend and looking forward to chatting a bit more about this!

**Comment by awalterschulze** [comment]
Did you still want to chat about this?

**Comment by byrnedo** [comment]
Sorry, only saw your message now, well it would be a nice feature I feel?

**Comment by awalterschulze** [comment]
Well we some more input here, don't you think?

**Comment by rogeralsing** [comment]
My interest in this would be for thread safety.
If there are multiple concurrent consumers of the same message instance and some consume accidentally mutates the message, there will be race conditions.

So if it would be possible to generate messages with unexported fields, and Getters only, and additional NewXYZMessage(params) constructor functions that could be used to create instances of the immutable messages, that would be awesome.

Currently the only way to get isolation across threads is to serialize and deserialize the messages for each consumer.

Or pass by value, but that gives other problems. as it seems impossible(?) to go from value to pointer in a generic way.

e.g.

```go
value := MyMessage{}
genericHandler(value)

func genericHandler(message interface{}) {
      switch msg := message.(type) {
             case proto.Message:
                   //this only matches if the message is passed as a pointer
                   //do stuff,send across wire or whatever
             default:
                   //handle in some other way. 
      }    
}
```

From my understanding, there is no clean way of going from `interface{}` to `proto.Message` if the content of the `interface{}` is a message value and not a pointer
(http://stackoverflow.com/questions/36864450/cast-boxed-struct-to-boxed-pointer-golang/36868843#36868843)

**Comment by awalterschulze** [comment]
If you generate the Marshal method you can just call the Marshal method and you don't need to satisfy the proto.Message interface, or am I wrong?

If you don't pass by value, some thread can just change what value the reference points to, which is also unsafe?

What about the Wrapper idea?
```
type CantTouchThis struct {
   private proto.Message
}

func (this *CantTouchThis) Marshal() ([]byte, error) {
  return proto.Marshal(this.private)
}
```

**Comment by rogeralsing** [comment]
The problem with the wrapper is that it can't be touched, not even read.

Lets say you want to send a message to _someone_ you don't know if this someone is in your local process, or remote, there is some routing code that will direct your message to the recipient.

e.g.
`sendToRecipients(myMessage)`

if the message is passed as a pointer, inprocess subscribers can mutate it right now as messages are mutable. thus causing race conditions amongst consumers

If the message is passed by value, it's incompatible with protobuf as protobuf wants you to pass the pointer.

e.g.

```go
sendToRecipients(MyMessage { } ) //compile error 
func sendToRecipients(message proto.Message) {
}
```
And this wont work either
```go
sendToRecipients(MyMessage { } )
func sendToRecipients(message interface{}) {
     //you cant go from interface to proto.Message if the "message" is a value
     //(you could typeswitch and get pointer from concrete type, but that wouldnt work unless the code knows about all possible types you are using)
}
```

So, the best bet, and most clean IMO, is to generate Getter only messages.
So that inprocess consumers can only _read_ from the messages but not mutate them.
And you can still pass by pointer and avoid allocations.

**Comment by awalterschulze** [comment]
I think using CantTouchThis will still work for message passing, but yes then you can't read the values.

**Comment by awalterschulze** [comment]
You could code some getters for CantTouchThis to simply expose the values you want to expose to allow for reading.
But this is quite manual.

**Comment by awalterschulze** [comment]
Problem with the private fields is making a sensible constructor and/or sensible set/append methods.
