### ISSUE TITLE
Custom bytes types and proto3 syntax generates broken Unmarshal without nullable = false

### ISSUE THREAD

**Issue by erikswanson** [gogo/protobuf#128]
The following definition generates an Unmarshal that doesn't compile:

    syntax = "proto3";
    package example;
    import "github.com/gogo/protobuf/gogoproto/gogo.proto";
    message KeyPair {
        bytes public_key = 1 [ (gogoproto.nullable) = false, (gogoproto.customtype) = "Key" ];
        bytes private_key = 2 [ (gogoproto.customtype) = "Key" ];
    }

The generated struct is more or less right:

    type KeyPair struct {
    	PublicKey  Key `protobuf:"bytes,1,opt,name=public_key,proto3,customtype=Key" json:"public_key"`
    	PrivateKey Key `protobuf:"bytes,2,opt,name=private_key,proto3,customtype=Key" json:"private_key,omitempty"`
    }

However, the generated Unmarshal includes this spurious code in the fieldNum case for private_key:

 			var v Key
			m.PrivateKey = &v

(This code is correctly absent in the case for public_key.) 

Tested with gogo/protobuf 8658879224bd739bf5f1009a686d4841ef397843 and protoc `3.0.0-beta-1-bzl-fix` (brew install --devel protobuf).''

My invocation is a little weird because I'm managing my entire GOPATH as a git repo with submodules:

	cd ${GOPATH}/src

	protoc \
	--gogofaster_out=. \
	--proto_path=${GOPATH}/src \
	--proto_path=$(brew --prefix protobuf)/include \
	${GOPATH}/src/example/*.proto

**Comment by awalterschulze** [comment]
customtype for proto3 and nullable=true was not working
https://github.com/gogo/protobuf/commit/9dc510915846dd5a05607d3b5bf41f5ca5cce972
This should now generate PrivateKey with a pointer.
Thank you for reporting :)

**Comment by erikswanson** [comment]
Should custom types actually be nullable by default for proto3? That's a bit surprising, I'd have expected them to be treated like scalars in that regard because they ultimately get written to the wire as a scalar.

**Comment by awalterschulze** [comment]
I would prefer nullable=true to stay the default and not to have different defaults for different cases, if that makes sense?

**Comment by erikswanson** [comment]
Consider the perspective of a user for whom proto2's behaviors/defaults are ancient history, with their expectations shaped by using proto3 with the upstream library.

With no gogoproto options in the file, both upstream (`protoc --go-out=`) and all of the gogoproto generators I tried generate a non-pointer []bytes for a "bytes" in the .proto file when using proto3 syntax.

It's a surprise that specifying the customtype option (and only that option) changes it to be nullable/a pointer by default.

**Comment by awalterschulze** [comment]
I don't see proto2 being ancient history any time soon, but given that.
Using no gogoproto options and just customtype also seems very unlikely.
I would agree that it is a little bit of a surprise, but I prefer the consistency with proto2 and message types in proto3.
To be fair, I really screwed up customtype from the get go.  So now I am just trying to keep it consistent.  It is weird enough already.
