### ISSUE TITLE
Feature/Wishlist: Support customtype=[n]byte

### ISSUE THREAD

**Issue by erikswanson** [gogo/protobuf#129]
Although custom types makes working with byte arrays in protobufs enjoyable (relatively), it would be useful if I could just set the customtype option to "[32]byte" and avoid having to actually write the boilerplate (un-)marshalling code.

The only meaningful difference I can foresee among "boilerplate" implementations is how incorrect lengths are handled when unmarshalling. If this was added as a feature, it would need to pick one behavior for all users that want to take advantage of not writing the (un-)marshalling code themselves. (My own preference would be to always error out if the length on the wire is wrong.)

Being able to combine this with casttype would be nice as well, if that wouldn't introduce too much complexity. (This would be for the case of custom types that are a byte array. E.g. `type PublicKey [32]byte`, `type PrivateKey [32]byte`.)

**Comment by awalterschulze** [comment]
You only need to write the boilerplate once per customtype.
Make a type Byte32 instead of separate types like PublicKey and PrivateKey.
