### ISSUE TITLE
NewPopulated can generate infinite recursion

### ISSUE THREAD

**Issue by dennwc** [gogo/protobuf#130]
Consider this type:
```proto
message Process {
  repeated Process sub = 1;
}
```
Generated code:
```Go
func NewPopulatedProcess(r randyTypes, easy bool) *Process {
  // ...
  v1 := r.Intn(10)
  this.Sub = make([]Process, v1)
  for i := 0; i < v1; i++ {
    v2 := NewPopulatedProcess(r, easy)
    this.Sub[i] = *v2
  }
  // ...
}
```
Which will generate infinite recursion most of the time.

**Comment by awalterschulze** [comment]
It was supposed to check that, but I guess I must have missed a case.
I am on holiday and will be back in about a week.

**Comment by awalterschulze** [comment]
https://github.com/gogo/protobuf/commit/b25331f05786694d634d632a8043fef600a84e62
I added another test and tuned some of the generated parameters, but this is the generated for Node.
```
message Node {
	optional string Label = 1;
	repeated Node Children = 2;
}
```
It detects the loop and then adds another if r.Intn(10) == 0 which only happens 10% of the time.  This makes the generation of an instance less likely, which means that this code will terminate in the limit.
```
func NewPopulatedNode(r randyThetest, easy bool) *Node {
	this := &Node{}
	if r.Intn(10) != 0 {
		v238 := randStringThetest(r)
		this.Label = &v238
	}
	if r.Intn(10) == 0 {
		v239 := r.Intn(5)
		this.Children = make([]*Node, v239)
		for i := 0; i < v239; i++ {
			this.Children[i] = NewPopulatedNode(r, easy)
		}
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedThetest(r, 3)
	}
	return this
}
```
I guess it would be nice to redo populated with another plugin that takes a levels int parameter and not an easy bool.
Please let me know if this is still broken?, but I couldn't reproduce.

**Comment by dennwc** [comment]
Can't reproduce with a new commit. Thank you for the fix!

**Comment by awalterschulze** [comment]
Glad to hear it.  Thank you for reporting back :)
