### ISSUE TITLE
Avoid memory allocation when unmarshaling `[]byte` fields

### ISSUE THREAD

**Issue by valyala** [gogo/protobuf#135]
Currently `[]byte` fields are unmarshaled using the following code:

```go
m.Foo = append([]byte{}, data[iNdEx:postIndex]...)
```

This leads to unnecessary memory allocation per each `[]byte` field even if `m.Foo` is already backed by byte slice. This can be safely fixed with the following code:

```go
m.Foo = append(m.Foo[:0], data[iNdEx:postIndex]...)
```

This code works as expected also if `m.Foo` is `nil`.

**Comment by awalterschulze** [comment]
This issue starts failing again after the change is made.
https://github.com/gogo/protobuf/issues/34

Basically if iNdEx == postIndex then no bytes are appended to m.Foo and m.Foo stays == nil, but it should be an empty slice.

**Comment by awalterschulze** [comment]
I still think we can do something here

**Comment by awalterschulze** [comment]
One way would be to add an if after the append
```
if m.Foo == nil {
  m.Foo = []byte{}
}
```

**Comment by awalterschulze** [comment]
This allows all tests to pass, but maybe there is a better way to do it?

**Comment by valyala** [comment]
This approach looks fine to me.

**Comment by awalterschulze** [comment]
Ok this has been pushed.
Thank you very much :)
