### ISSUE TITLE
Have an option to choose field order when serializing

### ISSUE THREAD

**Issue by mildred** [gogo/protobuf#151]
I have a protocol buffer message that I must be able to generate choosing the precise field order. Currently, it is sorted in tag order. Previously the order was the same as the order on the `.proto` file.

This is a problem for me because I need to be able to generate the message exactly in the correct order. This is because the message is then hashed and the hash must be equal to the previous serialization of the same message.

This is why I ask if it is possible to add an option to get the old ordering back.

**Comment by awalterschulze** [comment]
It was changed, because of this issue
https://github.com/gogo/protobuf/issues/42

We also hash our protobufs, but didn't feel your pain, because our tag order and field order has always been the same.

**Comment by awalterschulze** [comment]
I don't think we can it back, but please reply if you think we should reopen
