### ISSUE TITLE
protoc-gen-gogo/generator.FileName is broken

### ISSUE THREAD

**Issue by peter-edge** [gogo/protobuf#158]
If a file name (minus the `.proto`) has reserved golang characters in it, for example `geo.gen.proto` has a `.` in `geo.gen`, then the generated code is incorrect:

```
2016/03/21 13:58:02 protoc-gen-gogo: error:bad Go source code was generated: 1579:22: expected ';', found '.'
...
 1579	var fileDescriptorGeo.gen = []byte{
 1580		// 2235 bytes of a gzipped FileDescriptorProto
 1581		0x1f,0x8b,0x08,0x00,0x00,0x09,0x6e,0x88,0x02,0xff,0x7c,0xdb,0x57,0x90,0x1d,0xd5,
```

**Comment by peter-edge** [comment]
https://github.com/gogo/protobuf/blob/d5d4941acc4490628827091cafee2168f8c4bc67/protoc-gen-gogo/generator/helper.go#L446

golang/protobuf does something different here and doesn't have this issue

**Comment by peter-edge** [comment]
adding `fname = strings.Replace(fname, ".", "_", -1)` would fix this one issue, but you might want a more complete solution

**Comment by awalterschulze** [comment]
Good catch :)
Yes but they have problems with multiple files in the same folder not being generated with the same protoc instance.

**Comment by awalterschulze** [comment]
Fixed https://github.com/gogo/protobuf/commit/4168943e65a2802828518e95310aeeed6d84c4e5
Thank you
