### ISSUE TITLE
New formal release please?

### ISSUE THREAD

**Issue by onlyjob** [gogo/protobuf#159]
Projects of Docker, CoreOS and others already massively vendoring unreleased _protobuf_ for its `proto3` syntax so it might be a good time to consider tagging new formal release...

**Comment by awalterschulze** [comment]
I could do that, wouldn't you want to wait for full proto3 support, which should happen in a couple of weeks?

**Comment by onlyjob** [comment]
No rush but it would be great to tag sooner than later. Few weeks should be just fine, thank you. :)

**Comment by awalterschulze** [comment]
Whatever I made a release :)  I can just make another one later.

**Comment by onlyjob** [comment]
Awesome! Thank you. :)
