### ISSUE TITLE
Create a plugin that prints out a warning if `testgen` is enabled, but `populate` and `equal` are not.

### ISSUE THREAD

**Issue by Thomasdezeeuw** [gogo/protobuf#160]
Currently the following proto file will generate invalid code, which can't compile.

``` protobuf
syntax = "proto3";

package package;

import "github.com/gogo/protobuf/gogoproto/gogo.proto";

option (gogoproto.testgen_all) = true;

message Message {
  int64 field = 1;
}
```

But it doesn't generate any error. It requires the `populate_all` and `equal_all` options to work:

``` protobuf
syntax = "proto3";

package package;

import "github.com/gogo/protobuf/gogoproto/gogo.proto";

option (gogoproto.testgen_all) = true;
option (gogoproto.populate_all) = true; # Required by testgen_all.
option (gogoproto.equal_all) = true;      # Required by testgen_all.

message Message {
  int64 field = 1;
}
```

It would be nice if the generated code could work without those options. Alternatively those options could be set by `testgen_all`, so at least the code can compile.

**Comment by awalterschulze** [comment]
There is no way for me to tell whether you implemented your own populate function and equal method.
I could at most give a warning, what do you think?

**Comment by Thomasdezeeuw** [comment]
That would work for me.

**Comment by awalterschulze** [comment]
Ok then this because a task:

Create a plugin to check that when testgen is enabled for a message that populate and equal are also enabled.  If not, print out a warning.
See embedcheck, oneofcheck and defaultcheck as examples.

**Comment by Thomasdezeeuw** [comment]
I don't know if this is till relevant, but I personally no longer need it, so I'm going to close this.
