### ISSUE TITLE
Gogofast bug with map fields in nested messages

### ISSUE THREAD

**Issue by cespare** [gogo/protobuf#167]
gogofast generates invalid Go code from this proto:

``` protobuf
syntax = "proto3";

package example;

message M1 {
    message M2 {
        map<string, double> f = 1;
    }
}
```

[Generated Go here.](https://gist.github.com/cespare/384241f15c900ffcf21ea7bc3f6bf2ed) It doesn't compile:

```
./example.pb.go:96: msg.Size undefined (type float64 has no field or method Size)
./example.pb.go:97: msg.MarshalTo undefined (type float64 has no field or method MarshalTo)
./example.pb.go:145: e.Size undefined (type float64 has no field or method Size)
./example.pb.go:270: undefined: M1_M2_FEntry
./example.pb.go:270: first argument to append must be slice; have map[string]float64
./example.pb.go:271: cannot use len(m.F) - 1 (type int) as type string in map index
./example.pb.go:271: m.F[len(m.F) - 1].Unmarshal undefined (type float64 has no field or method Unmarshal)
```

**Comment by awalterschulze** [comment]
Good catch :)
A map is represented in the descriptor as a nested message and if that is already another nested message, that makes 3 levels op nested messages.
Gogoprotobuf was only able to handle two.  It has now been fixed to handle multiple levels.
https://github.com/gogo/protobuf/commit/74b6e9deaff6ba6da1389ec97351d337f0d08b06

**Comment by cespare** [comment]
Thanks for the very quick fix, @awalterschulze :)

**Comment by awalterschulze** [comment]
My pleasure :)
