### ISSUE TITLE
Merge: Update the grpc plugin to support the grpc-go interceptor implementation

### ISSUE THREAD

**Issue by gyuho** [gogo/protobuf#169]
https://github.com/golang/protobuf/commit/331aba25e29be6408a842fca779ec9c0526d9409

Could you merge this?

grpc-go has introduced interceptor, and we try to update our grpc
code but it breaks with the change in grpc.

Thanks a lot!

**Comment by ax-nathan** [comment]
+1

Just stubbed my toe on this.

**Comment by awalterschulze** [comment]
I have been holding back on merging in new things from golang/protobuf until they have well known types properly figured out.  But I'll take a look at making an exception asap next week.

**Comment by awalterschulze** [comment]
Done
https://github.com/gogo/protobuf/commit/516a501ca6e7ae3ff293043b84e509ce2537185b
