### ISSUE TITLE
Immutable messages

### ISSUE THREAD

**Issue by rogeralsing** [gogo/protobuf#171]
Would it be possible to support generation of immutable messages?
Are there any such plans?

e.g.

```go
myMessage := myprotos.NewMyMessage(40,"Roger",myprotos.NewOtherMessage(2))
a := myMessage.GetAge()
b := myMessage.GetName()

myMessage.Age = 123 //compile error, `age` is unexported
```

that would be sort of nice if you want to pass messages around concurrently to threads/goroutines or some such scenario.

**Comment by awalterschulze** [comment]
We discussed it here https://github.com/gogo/protobuf/issues/127 , but it does not make the messages immutable only private.
But its probably a good approximation if NewMyMessage does not return a pointer.
Please read the linked issue and see if you have anything to add.

**Comment by awalterschulze** [comment]
no reply on this issue for months, so closing
