### ISSUE TITLE
Generate generic message instance creators by name

### ISSUE THREAD

**Issue by rogeralsing** [gogo/protobuf#172]
Would it be possible to generate something similar to `proto.MessageType(name)` but instead of returning the `reflect.Type` return an instance of that message ?

For example, when working with "self describing messages" where you have an envelope message that carries the message name and byte array for message data.
If you want to materialize the payload of such envelope message, you have to resort to reflection (unless I have missed something)

```go
func CreateInstanceFromPayload(typeName string, messageData []byte) proto.Message {
    t := proto.MessageType(typeName).Elem()
    intPtr := reflect.New(t)
    instance := intPtr.Interface().(proto.Message)
    proto.Unmarshal(messageData , instance)
    return instance
}
```

It would be nicer if one could do something like:

```go
func CreateInstanceFromPayload(typeName string, messageData []byte) proto.Message{
    message := gogo.CreateMessage(typeName, messageData)
    return message
}
```

**Comment by awalterschulze** [comment]
Why would this need to be generated, seems like a simple function?

**Comment by awalterschulze** [comment]
no reply for months, so closing this issue
