### ISSUE TITLE
Adding a new UnsafeMarshallerWithArenaAllocation

### ISSUE THREAD

**Issue by smarterclayton** [gogo/protobuf#174]
I've been experimenting with an unsafe arena allocation technique for generated gogoprotobuf unmarshallers that avoids `[]byte -> string` allocations during decode, by leveraging the technique Vitess describes here: https://github.com/youtube/vitess/blob/master/go/hack/hack.go

It has the potential to dramatically improve the speed of decodes for any object with more than a few strings, but requires a slightly more complex Unmarshal signature to pull off.  Would you accept a ReallyUnsafeMarshaller that allowed the unmarshal caller to pass an Arena object in to the unmarshaller?  Because of the signature change it would be different than the normal unmarshaller, and callers would need to really understand that Go might change the semantics around strings in an incompatible way in the future.  On the other hand... performance...

E.g.

```
f.Unmarshal(data, &proto.Options{Arena: proto.NewArena(len(data) / 2)})

func (f *foo) Unmarshal(data []byte, o *proto.Options) {
  ...
  switch field
  case 1:
     ...
     m.AString = o.Arena.NewString(data[i:l])
     ...
  }
}
```

Picking the arena size relative to the data would be important - guessing based on your object what the percentage of data is part of strings.

**Comment by awalterschulze** [comment]
Have you seen this issue
https://github.com/gogo/protobuf/issues/54

What do you think about the effects of a moving garbage collector?

**Comment by smarterclayton** [comment]
I saw the issue - I *think* the moving garbage collector would still be safe here because we still have a concrete references first to the overall string, and every subsequent string is part of that original object.  However, I am not an expert on the implications so if we think it would be totally broken in the presence of a moving GC I'll give it up (although I haven't seen movement on that).

**Comment by awalterschulze** [comment]
I am not an expert either, I am just a little cautious.
What would be the difference in simply unmarshaling into a byteslice and a proto.Arena?

**Comment by awalterschulze** [comment]
Looks like not much its just adds a little abstraction.

**Comment by awalterschulze** [comment]
Is there some way we could benefit more types than just strings?
It would be nice if we could do all the pointer management ourselves and have even less of a garbage collector impact.
That is what I was trying to do in #54 
But when I push it there I get really scared about the moving garbage collector.
Maybe we can ask someone who knows?

**Comment by smarterclayton** [comment]
Tried to grab some concrete numbers from a fairly complex Kubernetes object (roughly 40 strings, deep structure, etc).  Changed only the unmarshaller to generate a string unsafe cast of bytes:

```
		} else if proto3 || !nullable {
			p.P(`var s `, typ)
			p.P(`part := data[iNdEx:postIndex]`)
			p.P(`source := (*reflect.SliceHeader)(unsafe.Pointer(&part))`)
			p.P(`hdr := (*reflect.StringHeader)(unsafe.Pointer(&s))`)
			p.P(`hdr.Data, hdr.Len = source.Data, source.Len`)
			p.P(`m.`, fieldname, ` = s`)
			//p.P(`m.`, fieldname, ` = `, typ, `(data[iNdEx:postIndex])`)
		} else {
			p.P(`var s `, typ)
			p.P(`part := data[iNdEx:postIndex]`)
			p.P(`source := (*reflect.SliceHeader)(unsafe.Pointer(&part))`)
			p.P(`hdr := (*reflect.StringHeader)(unsafe.Pointer(&s))`)
			p.P(`hdr.Data, hdr.Len = source.Data, source.Len`)
			p.P(`m.`, fieldname, ` = &s`)
			//p.P(`s := `, typ, `(data[iNdEx:postIndex])`)
		}
```

This roughly emulates what it would be to create an arena up front (a copy of the incoming buffer that the object can hold a reference to that is guaranteed not to mutate) and then use unsafe to avoid string allocations.  The numbers below represent a straight decode to the go struct (`DecodeIntoProtobuf` is the protobuf version, `JSON` is the stdlib, and `JSONCodecGen` is the https://github.com/ugorji/go generated JSON marshallers):

```
benchmark                                      old ns/op     new ns/op     delta
BenchmarkDecodeIntoProtobuf-8                  9399          7452          -20.71%
BenchmarkDecodeIntoJSON-8                      90679         94594         +4.32%
BenchmarkDecodeIntoJSONCodecGen-8              52818         51626         -2.26%

benchmark                                      old allocs     new allocs     delta
BenchmarkDecodeIntoProtobuf-8                  99             50             -49.49%
BenchmarkDecodeIntoJSON-8                      175            175            +0.00%
BenchmarkDecodeIntoJSONCodecGen-8              337            337            +0.00%

benchmark                                      old bytes     new bytes     delta
BenchmarkDecodeIntoProtobuf-8                  4984          3736          -25.04%
BenchmarkDecodeIntoJSON-8                      10673         10673         +0.00%
BenchmarkDecodeIntoJSONCodecGen-8              12745         12737         -0.06%
```

That's probably the biggest win I can see of the types - the remaining operations are evenly divided but are mostly array allocations as we traverse down our tree.

**Comment by awalterschulze** [comment]
Ok so by copying the original marshaled bytes you do a zero copy in the unmarshaling code.

So this means the unmarshaling more than 20% faster.

Does this include the initial copy fo the original marshaled bytes?

**Comment by smarterclayton** [comment]
It doesn't - I'll be sure to add that for a test.

**Comment by awalterschulze** [comment]
I think we are continuing the discussion in the pull request.  So closing this.
