### ISSUE TITLE
Renaming Size()

### ISSUE THREAD

**Issue by AudriusButkevicius** [gogo/protobuf#177]
It's impossible to have a struct with a Size attribute/method on it (customname does nothing), as the generated code always expects to have a Size() function. It would be nice if this could be renamed.

**Comment by AudriusButkevicius** [comment]
Ignore me, took a while to figure this out.

**Comment by awalterschulze** [comment]
Cool just for future reference.  You can rename the Size method to the ProtoSize method using a different extension.

**Comment by AudriusButkevicius** [comment]
The confusion was that you have to set sizer to false for protosizer to take effect.

**Comment by awalterschulze** [comment]
Aha cool, good comment :)

**Comment by AudriusButkevicius** [comment]
Maybe the less confusing way would be to do (gogoproto.sizer) = "protosizer"

**Comment by awalterschulze** [comment]
Yes that would have made sense, but too late to change that now.
