### ISSUE TITLE
synchronize jsonpb with upstream

### ISSUE THREAD

**Issue by tamird** [gogo/protobuf#180]
There's been quite a bit of unsynchronized work in https://github.com/golang/protobuf/commits/master/jsonpb

@awalterschulze could you merge some of this work into gogo?

**Comment by awalterschulze** [comment]
Which one specifically. Its hard to merge these without merging incomplete
wtks

**Comment by tamird** [comment]
I specifically need https://github.com/golang/protobuf/commit/99511271042a09d1e01baea8781caa5210fec66e

**Comment by tamird** [comment]
Actually, turns out I don't need this!

**Comment by awalterschulze** [comment]
I can't wait till the wtks are completed so that gogo can stay nsync with
golang protobuf :-( Glad you are ok though
