### ISSUE TITLE
Please tag a new release (and regularly keep doing so)

### ISSUE THREAD

**Issue by steveeJ** [gogo/protobuf#182]
It was been a while since the last tagged release, which makes it tempting to use a commit for vendoring of this project. However, randomly picking a commit in an unknown project is quite risky, and therefore has negative consequences WRT packaging policies.

A hopefully stable pick by the author would be much appreciated. Thanks!

**Comment by awalterschulze** [comment]
Yes well we are working on making 0.2 more stable here.
So I don't want to tag another release before that fix.
https://github.com/gogo/protobuf/issues/164

And then I am doing it every time someone asks.
But it is typically quite stable.

**Comment by vincentbernat** [comment]
Hey, 0.2 has been tagged some time ago. Could you tag a 0.3 if you think the current master is stable enough?

Thanks!

**Comment by awalterschulze** [comment]
done https://github.com/gogo/protobuf/releases/tag/v0.3

**Comment by awalterschulze** [comment]
It still has the bug, but its going to take to long to fix and go 1.7 is out.  So its probably a good idea to release a branch that is compatible with go1.7
