### ISSUE TITLE
Feature: Non-Pointer structs

### ISSUE THREAD

**Issue by AudriusButkevicius** [gogo/protobuf#184]
```
func (m *Vector) Reset()                    { *m = Vector{} }
func (m *Vector) String() string            { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()               {}
func (*Vector) Descriptor() ([]byte, []int) { return fileDescriptorBep, []int{14} }
```

It would be nice if it was possible to generate these as non-pointer receivers, so that we wouldn't need to throw pointers around just to satisfy proto.Message interface.

**Comment by awalterschulze** [comment]
Have you tried to manually do it, just to see what other errors you will get?
I suspect this is going to cause quite a few problems, especially with nested messages.

**Comment by AudriusButkevicius** [comment]
No I haven't, but I can see that for example Reset() starts making no sense, or has to have it's API changed.

**Comment by awalterschulze** [comment]
Yes I really don't know how feasible this is, but I am very skeptical.
If you have done an investigation and feel positive, please feel free to reopen this issue.
