### ISSUE TITLE
Custom type names for messages (especially nested ones)

### ISSUE THREAD

**Issue by calmh** [gogo/protobuf#186]
Consider the following message layout:

```
    message ClusterConfigMessage {
        repeated Folder folders = 1;

        message Folder {
            string id                   = 1;
            repeated Device devices = 16;

            message Device {
                bytes           id                = 1;
                string          name              = 2;
            }
        }
    }
```

This gets me attributes such as `Devices  []ClusterConfigMessage_Folder_Device` which is correct and makes sense but isn't the most friendly type name in the world. It would be neat if the generated type name could be overridden per message, for example

```
    message ClusterConfigMessage {
        repeated Folder folders = 1;

        message Folder {
            option (gogoproto.goproto_typename) = "CMFolder";  // <<-- this
            string id                   = 1;
...
```

As it is, I simply un-nest the messages to get reasonable names but it would be nice to keep the schema more semantically grouped.

**Comment by Thomasdezeeuw** [comment]
Why not define Folder as a global message called CMFolder? Like this:

```proto
message ClusterConfigMessage {
    repeated CMFolder folders = 1;
}

message CMFolder {
    string id                   = 1;
    repeated CMFDevice devices = 16;
}

message CMFDevice {
    bytes           id                = 1;
    string          name              = 2;
}
```

**Comment by calmh** [comment]
Oh, I do, as I indeed wrote above. But the nesting implies something about the structure and where the messages are used, and it would be neat to be able to do this on an existing protobuf schema with nesting.

**Comment by awalterschulze** [comment]
Sounds we have a overlapping feature request with https://github.com/gogo/protobuf/issues/149 which also needs custom message names.

**Comment by awalterschulze** [comment]
closing since its a duplicate.
