### ISSUE TITLE
gogofast generated proto files aren't compatible with "github.com/golang/protobuf/jsonpb"

### ISSUE THREAD

**Issue by gyuho** [gogo/protobuf#188]
This code only works when `WatchRequest` is generated with `gofast` but doesn't work when it is generated with `gogofast`:

```bash
protoc --gofast_out=plugins=grpc:. \
	--proto_path=$GOPATH/src:$GOPATH/src/github.com/gogo/protobuf/protobuf:. \
	*.proto;

protoc --gogofast_out=plugins=grpc:. \
	--proto_path=$GOPATH/src:$GOPATH/src/github.com/gogo/protobuf/protobuf:. \
	*.proto;
```

```proto
syntax = "proto3";
package main;

import "github.com/gogo/protobuf/gogoproto/gogo.proto";

message WatchRequest {
  oneof request_union {
    WatchCreateRequest create_request = 1;
  }
}

message WatchCreateRequest {
  bytes key = 1;
}
```

```go
import (
	"fmt"
	"log"

	"github.com/golang/protobuf/jsonpb"
)

func main() {
	const input = `{"create_request": {"key": "Zm9v"}}`
	var req WatchRequest
	if err := jsonpb.UnmarshalString(input, &req); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("success with %+v\n", req.RequestUnion)
	// success with &{CreateRequest:key:"foo" } or unknown field "create_request" in main.WatchRequest
}
```

Here's the sample proto and generated files and script to reproduce this issue:

[golang-vs-gogo-proto-issue.tar.gz](https://github.com/gogo/protobuf/files/366821/golang-vs-gogo-proto-issue.tar.gz)

Reference
- https://github.com/coreos/etcd/issues/5865
- https://github.com/grpc-ecosystem/grpc-gateway/issues/82#issuecomment-231931632

**Comment by awalterschulze** [comment]
Does this fix your problem?
https://github.com/gogo/protobuf/commit/b5aec62d3ed33b10b4179b07628d362d0957d1da

**Comment by gyuho** [comment]
Yes it does. Found some other issue (https://github.com/coreos/etcd/pull/5969), but I don't think it's related to `gogo/protobuf`.

Thanks a lot, @awalterschulze!

**Comment by awalterschulze** [comment]
My pleasure :)

Just a note: I only used your issue report (which was great) and not the zip.  I tried using the zip file to help me debug and fix the issue, but it was not really useful.  So you can save yourself the effort next time.  If you really want to make an effort a pull request with a failing test (in the test folder) will help me the most, but your report was perfect and already a big help.
