### ISSUE TITLE
gogofast doesn't decode enum as string

### ISSUE THREAD

**Issue by gyuho** [gogo/protobuf#189]
```proto
syntax = "proto3";
package main;

import "github.com/gogo/protobuf/gogoproto/gogo.proto";

enum Type {
  READ = 0;
  WRITE = 1;
  READWRITE = 2;
}

message WatchCreateRequest {
  bytes key = 1;
  Type  type = 2;
}
```

```
protoc --gogofast_out=plugins=grpc:. \
	--proto_path=$GOPATH/src:$GOPATH/src/github.com/gogo/protobuf/protobuf:. \
	*.proto;
```

```go
package main

import (
	"fmt"
	"log"

	"github.com/golang/protobuf/jsonpb"
)

func main() {
	const input = `{"key": "Zm9v", "type": "READ"}`
	// works with
	// const input = `{"key": "Zm9v", "type": 0}`

	var req WatchCreateRequest
	if err := jsonpb.UnmarshalString(input, &req); err != nil {
		log.Fatal(err)
		// unknown value "READ" for enum main.Type
	}
	fmt.Printf("success with %+v\n", req)
}
```

Reproduce

[golang-vs-gogo-proto-issue-jsonpb.tar.gz](https://github.com/gogo/protobuf/files/366985/golang-vs-gogo-proto-issue-jsonpb.tar.gz)

Reference
- https://developers.google.com/protocol-buffers/docs/proto3#json
- https://github.com/golang/protobuf/commit/5d7f79bcf383219d69ddd0edf148166689fdf7fc#diff-ef290093d80b46fd7f16c53d7b68b1e4L423
- https://github.com/coreos/etcd/issues/5942

**Comment by awalterschulze** [comment]
You are trying to generate code with gogo/protobuf which also imports gogo/protobuf (gogofast) and unmarshal it with golang/protobuf.
You could use gofast_out or replace the import
```
"github.com/golang/protobuf/jsonpb"
```
with
```
"github.com/gogo/protobuf/jsonpb"
```

**Comment by awalterschulze** [comment]
Enums have to register with the same (golang or gogo) package that is used to marshal and unmarshal it.

**Comment by gyuho** [comment]
Thanks!
