### ISSUE TITLE
Add ways to access comments of Messages/Fields in codegen

### ISSUE THREAD

**Issue by mwitkow** [gogo/protobuf#193]
We'd like to use the gogo `Generator` base to build a customizeable Markdown generator. 

Unfortunately, the `FileDescriptor` fields that deal with comments are private. Similarly, on a message the `Descriptor.path` is private, making it hard to reconstruct.

It would be extremely helpful if there was easy access to `SourceCodeInfo_Location` of a given `Message`, `Service` or `Field`.

**Comment by awalterschulze** [comment]
I think this is probably a very small amount of code?

If I am correct maybe you could just code it and show me your proposal in code?

If I am incorrect please let me know and I'll think a bit more about it before you make any effort.

**Comment by awalterschulze** [comment]
no response
