### ISSUE TITLE
Panics after upgrading to go1.7

### ISSUE THREAD

**Issue by psanford** [gogo/protobuf#194]
After upgrading to 1.7 we started seeing occasional panics which seem be coming from gogo protobuf. I've created a minimal test case that can consistently reproduce the panic. All of the following code is go get'able from https://github.com/psanford/gogopanic.

Here's the protobuf definition:
```
syntax = "proto2";
package main;

import "github.com/gogo/protobuf/gogoproto/gogo.proto";

message Record {
  optional string A = 2 [(gogoproto.nullable) = false];
}

message RecordList {
  repeated Record recs = 1 [(gogoproto.nullable) = false];
}
```

main.go:
```
package main

import (
	"time"

	"github.com/gogo/protobuf/proto"
)

func main() {
	rec := Record{
		A: "neutralizes-nicety",
	}

	list := &RecordList{
		Recs: []Record{rec, rec},
	}

	for i := 0; i < 100; i++ {
		go func() {
			for {
				encoded, err := proto.Marshal(list)
				if err != nil {
					panic(err)
				}

				var eventList RecordList
				if err = proto.Unmarshal(encoded, &eventList); err != nil {
					panic(err)
				}

				_ = eventList
			}
		}()
	}

	time.Sleep(500 * time.Second)
}
```

There are two different panics that I'm getting when I run this program:
```
runtime: nelems=39 nfree=31 nalloc=8 previous allocCount=7 nfreed=65535
fatal error: sweep increased allocation count
```

and 
```
runtime: pointer 0xc4200dffe0 to unused region of spanidx=0x6f span.base()=0xc4200de000 span.limit=0xc4200dffe0 span.state=0
runtime: found in object at *(0xc4205bbef0+0x0)
object=0xc4205bbef0 k=0x62102dd s.base()=0xc4205ba000 s.limit=0xc4205bbfe0 s.sizeclass=6 s.elemsize=80
 *(object+0) = 0xc4200dffe0 <==
 *(object+8) = 0x12
 *(object+16) = 0x0
 *(object+24) = 0x0
 *(object+32) = 0x0
 *(object+40) = 0xc42031a3c0
 *(object+48) = 0x12
 *(object+56) = 0x0
 *(object+64) = 0x0
 *(object+72) = 0x0
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)
```

You can see the full panic output here:

- https://github.com/psanford/gogopanic/blob/master/panic.a
- https://github.com/psanford/gogopanic/blob/master/panic.b

There is a closed issue on golang/go for one of these panics:   https://github.com/golang/go/issues/16778. That issue suggests that this might be caused by improper use of unsafe.

**Comment by awalterschulze** [comment]
For a quick fix simply generate the marshal and unmarshal methods. 
gogofast_out=. instead of gogo_out=.
But I am looking into the problem as well.

**Comment by awalterschulze** [comment]
Yes this is exercising the hardest code written in gogoprotobuf: Unmarshaling into a slice of structs using unsafe and not using the generated code.

**Comment by psanford** [comment]
Thanks for the tip.

**Comment by awalterschulze** [comment]
This should also fix the problem
https://github.com/gogo/protobuf/commit/330d6892d1d39fcd6cff0b4240821bdaf30c3a3c
