### ISSUE TITLE
Known Issue: unsafe(marshaler and unmarshaler) test failures on big endian architectures

### ISSUE THREAD

**Issue by onlyjob** [gogo/protobuf#195]
Some tests failed only on _s390x_: https://buildd.debian.org/status/fetch.php?pkg=golang-gogoprotobuf&arch=s390x&ver=0.3-1&stamp=1472170768

**Comment by xnox** [comment]
And on powerpc https://launchpadlibrarian.net/281035268/buildlog_ubuntu-yakkety-powerpc.golang-gogoprotobuf_0.2-5_BUILDING.txt.gz

This is probably a bigendian issue in the expected values.

**Comment by awalterschulze** [comment]
Are these still all 32 bit big endian architectures?
As previously reported in this issue.
https://github.com/gogo/protobuf/issues/164

**Comment by xnox** [comment]
powerpc - is 32 bit big endian
s390x - is 64 bit big endian

**Comment by awalterschulze** [comment]
Ok I think I might have found the problem.
Maybe you can test the the `bigendian` branch 
https://github.com/gogo/protobuf/tree/bigendian

**Comment by xnox** [comment]
That branch vs master is a good improvement

```
# grep '^FAIL' protobuf-2/bigendian.log protobuf/master.log  | grep github
protobuf-2/bigendian.log:FAIL	github.com/gogo/protobuf/test/combos/unsafemarshaler	0.138s
protobuf-2/bigendian.log:FAIL	github.com/gogo/protobuf/test/combos/unsafeunmarshaler	0.157s
protobuf-2/bigendian.log:FAIL	github.com/gogo/protobuf/test/mapsproto2/combos/unsafemarshaler	0.016s
protobuf-2/bigendian.log:FAIL	github.com/gogo/protobuf/test/mapsproto2/combos/unsafeunmarshaler	0.043s
protobuf-2/bigendian.log:FAIL	github.com/gogo/protobuf/test/oneof/combos/unsafemarshaler	0.006s
protobuf-2/bigendian.log:FAIL	github.com/gogo/protobuf/test/oneof/combos/unsafeunmarshaler	0.006s
protobuf-2/bigendian.log:FAIL	github.com/gogo/protobuf/test/oneof3/combos/unsafemarshaler	0.004s
protobuf-2/bigendian.log:FAIL	github.com/gogo/protobuf/test/oneof3/combos/unsafeunmarshaler	0.004s
protobuf-2/bigendian.log:FAIL	github.com/gogo/protobuf/test/packed	0.002s
protobuf-2/bigendian.log:FAIL	github.com/gogo/protobuf/test/theproto3/combos/unsafemarshaler	0.027s
protobuf-2/bigendian.log:FAIL	github.com/gogo/protobuf/test/theproto3/combos/unsafeunmarshaler	0.028s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test	0.103s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/combos/both	0.094s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/combos/marshaler	0.110s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/combos/unmarshaler	0.119s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/combos/unsafeboth	0.120s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/combos/unsafemarshaler	0.166s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/combos/unsafeunmarshaler	0.109s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/custom	0.002s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/example	0.010s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/mapsproto2/combos/unsafemarshaler	0.022s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/mapsproto2/combos/unsafeunmarshaler	0.025s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/oneof/combos/both	0.019s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/oneof/combos/marshaler	0.007s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/oneof/combos/neither	0.007s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/oneof/combos/unmarshaler	0.006s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/oneof/combos/unsafeboth	0.009s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/oneof/combos/unsafemarshaler	0.013s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/oneof/combos/unsafeunmarshaler	0.006s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/oneof3/combos/unsafemarshaler	0.004s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/packed	0.002s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/theproto3/combos/both	0.027s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/theproto3/combos/marshaler	0.027s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/theproto3/combos/neither	0.021s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/theproto3/combos/unmarshaler	0.030s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/theproto3/combos/unsafeboth	0.034s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/theproto3/combos/unsafemarshaler	0.040s
protobuf/master.log:FAIL	github.com/gogo/protobuf/test/theproto3/combos/unsafeunmarshaler	0.038s
```

I will attach the logs in a moment.

**Comment by xnox** [comment]
[bigendian.txt](https://github.com/gogo/protobuf/files/452931/bigendian.txt)
[master.txt](https://github.com/gogo/protobuf/files/452932/master.txt)

**Comment by awalterschulze** [comment]
Ok great now all that is breaking is unsafe marshaling and unmarshaling.
This makes sense because of the use of unsafe to cast to and from 64bit and 32bit numbers.
https://github.com/gogo/protobuf/blob/master/plugin/marshalto/marshalto.go#L247
https://github.com/gogo/protobuf/blob/master/plugin/marshalto/marshalto.go#L247
This does not work in the case of bigendian architectures.
I also don't think I can fix this.  The only way is to skip the tests for bigendian architectures which I don't know how to do.

**Comment by EricLagergren** [comment]
> The only way is to skip the tests for bigendian architectures which I don't know how to do.

In each test you could write `if isBigEndian { return }` where `bigEndian` is a global boolean indicating the arch is be

**Comment by awalterschulze** [comment]
Yes so the problem is how to get that isBigEndian equal to true for big endian architectures, any ideas?

**Comment by EricLagergren** [comment]
There's a few ways:

1) Let the user decide using build tags (i.e., `// +build bigendian`)

2) Make a compile-time constant using runtime.GOARCH. (To determine the big endian architectures, run: `grep -rn 'BigEndian\s\+=\s\+1' $GOROOT/src/runtime/* | cut -sf2 -d_ | cut -d. -f1`). Then you can make a compile-time constant:

```go
const bigEndian = runtime.GOARCH = "ppc64" || runtime.GOARCH =  ...
```

3) Use a runtime variable:
```go
var bigEndian bool
var x uint32 = 0x01020304 
if *(*byte)(unsafe.Pointer(&x)) == 1 { bigEndian = true }
```

**Comment by awalterschulze** [comment]
1) No, it should be automatic.

2) Do you know exactly which arcs are the bigEndian archs because then we can just have a function
```
func IsBigEndian() bool {
  switch runtime.GOARCH:
  case "ppc64", "...", "..":
     return true
  }
  return false
}

3) Thats a really cool idea, why didn't I think of that :)

**Comment by EricLagergren** [comment]
2) Yeah, run the shell command In my comment and it'll list them :-) Although, it might make sense to just have a global `const BigEndian = ...` because it'd remove a lot of branching. But that's just my particular style.

3) Credit to rob pike, although that trick is pretty old.

**Comment by awalterschulze** [comment]
2) Ok great so its as simple as?

```
func IsBigEndian() bool {
  switch runtime.GOARCH:
  case "ppc64", "mips64", "s390x":
     return true
  }
  return false
}
```

**Comment by awalterschulze** [comment]
3) Do you maybe have a reference?

**Comment by EricLagergren** [comment]
Yeah, it's as simple as that.

Also, the reference: https://groups.google.com/forum/#!msg/golang-nuts/zmh64YkqOV8/iJe-TrTTeREJ

**Comment by awalterschulze** [comment]
@onlyjob @xnox 
Would one of you mind testing the bigskip branch?
https://github.com/gogo/protobuf/tree/bigskip

**Comment by awalterschulze** [comment]
hello? @onlyjob @xnox

**Comment by awalterschulze** [comment]
hello?

**Comment by xnox** [comment]
Whilst that test is now skipped, there are still other failures.
I'm not sure how wise it is to just skip the tests... Either expectations of the results should be altered, or results should be demangled into the expected endianness. Will attach log shortly.

**Comment by xnox** [comment]
[s390x-test-log.txt](https://github.com/gogo/protobuf/files/824501/s390x-test-log.txt)

**Comment by awalterschulze** [comment]
I see lots of Compare and VerboseEqual tests failing.

I also see some weird need here
```
Verbose
Compare

=== RUN   TestDashFilename
--- FAIL: TestDashFilename (0.00s)
	df_test.go:43: err = exec: "protoc": executable file not found in $PATH: 
FAIL
exit status 1
FAIL	github.com/gogo/protobuf/test/dashfilename	0.002s
=== RUN   TestNullableDefault
--- PASS: TestNullableDefault (0.00s)
	nc_test.go:47: received expected error = exec: "protoc": executable file not found in $PATH and output = 
=== RUN   TestNullableExtension
--- PASS: TestNullableExtension (0.00s)
	nc_test.go:47: received expected error = exec: "protoc": executable file not found in $PATH and output = 
=== RUN   TestNullableEnum
--- PASS: TestNullableEnum (0.00s)
	nc_test.go:47: received expected error = exec: "protoc": executable file not found in $PATH and output = 
=== RUN   TestFaceDefault
--- PASS: TestFaceDefault (0.00s)
	nc_test.go:47: received expected error = exec: "protoc": executable file not found in $PATH and output = 
=== RUN   TestNoGettersDefault
--- PASS: TestNoGettersDefault (0.00s)
	nc_test.go:47: received expected error = exec: "protoc": executable file not found in $PATH and output = 
PASS
ok  	github.com/gogo/protobuf/test/defaultconflict	0.002s
=== RUN   TestEmbedConflict
--- PASS: TestEmbedConflict (0.00s)
	ec_test.go:47: received expected error = exec: "protoc": executable file not found in $PATH and output = 
=== RUN   TestEmbedMarshaler
--- FAIL: TestEmbedMarshaler (0.00s)
	ec_test.go:54: received error = exec: "protoc": executable file not found in $PATH and output = 
	ec_test.go:56: Expected WARNING: found non-[marshaler unsafe_marshaler] C with embedded marshaler D
	ec_test.go:59: remove em.pb.go: no such file or directory
=== RUN   TestEmbedExtend
--- PASS: TestEmbedExtend (0.00s)
	ec_test.go:72: received expected error = exec: "protoc": executable file not found in $PATH and output = 
=== RUN   TestCustomName
--- PASS: TestCustomName (0.00s)
	ec_test.go:84: received expected error = exec: "protoc": executable file not found in $PATH and output = 
=== RUN   TestRepeatedEmbed
--- FAIL: TestRepeatedEmbed (0.00s)
	ec_test.go:97: received error = exec: "protoc": executable file not found in $PATH and output = 
	ec_test.go:100: Expected ERROR: found repeated embedded field B in message A
=== RUN   TestTakesTooLongToDebug
--- FAIL: TestTakesTooLongToDebug (0.00s)
	ec_test.go:114: received error = exec: "protoc": executable file not found in $PATH and output = 
	ec_test.go:117: Expected ERROR: found embedded bytes field
FAIL
exit status 1
FAIL	github.com/gogo/protobuf/test/embedconflict	0.002s
```

And here
```
--- FAIL: TestUnsafeIssue21 (0.00s)
	packed_test.go:81: Field1 this[0](-0.04947258049824538) Not Equal that[0](6.369994500859523e+119)
```

**Comment by awalterschulze** [comment]
The VerboseEqual and Compare tests are failing for unsafemarshaler and unsafeunmarshaler.
So these tests should also be skipped if the message has unsafemarshaler or unsafeunmarshaler enabled.
I think its O K to skip the tests, if we also documented that it is not supported for bigendian CPUs.

**Comment by awalterschulze** [comment]
Can you maybe figure out why some of the tests cannot find the protoc binary in $PATH ?
`nc_test.go:47: received expected error = exec: "protoc": executable file not found in $PATH`

**Comment by awalterschulze** [comment]
I have now updated the bigskip branch to the newest version and we are also skipping VerboseEqual and Compare tests if the message which is being tested has enable the unsafemarshaler or unsafeunmarshaler.

**Comment by awalterschulze** [comment]
I have also updated the documentation on this branch to reflect that unsafe is not supported by bigendian architectures. 
https://github.com/gogo/protobuf/commit/d31b212e5e5828c949dab032ca7e8e681065e151

**Comment by awalterschulze** [comment]
I am now also skipping TestUnsafeIssue21 if is not on a little endian architecture, since its also using unsafe marshaling and unmarshaling.  So now the only tests that fail that are left should be the tests that cannot find protoc in the $PATH.
https://github.com/gogo/protobuf/commit/44aac9e35c90453309e292586885ca99c747a23d
All on the bigskip branch.

**Comment by xnox** [comment]
With these build completes; also resolved lack of protoc in the $PATH (local setup error).

Will the unsupported unsafe marshaling/unmarshaling functions be un-exported on big-endian systems, such that projects that use protobuf cannot use those functions on big-endian systems? (Or e.g. safe functions used instead)

**Comment by awalterschulze** [comment]
Thats great to hear :)

Just for reference, the check:
```
var bigendian uint32 = 0x01020304
if *(*byte)(unsafe.Pointer(&bigendian)) == 1 {
```

1) I guess this check could be done before marshaling or unmarshaling in every unsafe method.
1a) This could then result in an error 
1b) or calling the safe path.

2) Or this check could be done when generating the code.

3) Or the documentation is enough.

**Comment by awalterschulze** [comment]
I am going to merge this branch for now so that we can get a release out that finally passes your tests.
But I'll leave this case open for further work if someone is interested.

**Comment by pascaldekloe** [comment]
Hi Walter, I just bumped into [gohci](https://github.com/periph/gohci). For 50 bugs you'll have both 32- and 64-bits big endian covered. =)

**Comment by awalterschulze** [comment]
Yes, but then I'll have to set them up and maintain these raspberry pis.
It would be nice if there was a raspberry pi farm to run tests on, like travispi or circlepi or pidrone
That would be great.

**Comment by awalterschulze** [comment]
I have removed unsafe, since the "new" range checking hints give comparable speed, so this issue should no longer exist.
