### ISSUE TITLE
customtype of type struct cannot jsonpb unmarshal

### ISSUE THREAD

**Issue by ericlagergren** [gogo/protobuf#201]
(Posting b/c you asked for a separate issue.)

See: https://github.com/gogo/protobuf/issues/199#issuecomment-248066262

**Comment by awalterschulze** [comment]
Would you like to attempt a fix?

**Comment by EricLagergren** [comment]
See my comment on the other issue. This one is much simpler so I think it's manageable :)

**Comment by awalterschulze** [comment]
Fixed by https://github.com/gogo/protobuf/pull/239
