### ISSUE TITLE
proto3: bool extension fields result in invalid generated code

### ISSUE THREAD

**Issue by alecthomas** [gogo/protobuf#204]
I couldn't see any existing issues for this, so here it is.

This:

```proto
extend google.protobuf.FieldOptions {
  bool primary = 51234;
  bool index = 51235;
}
```

Results in this:

```go
var E_Primary = &proto.ExtensionDesc{
  ExtendedType:  (*google_protobuf.FieldOptions)(nil),
  ExtensionType: (bool)(nil),
  Field:         51234,
  Name:          "store.primary",
  Tag:           "varint,51234,opt,name=primary",
}

var E_Index = &proto.ExtensionDesc{
  ExtendedType:  (*google_protobuf.FieldOptions)(nil),
  ExtensionType: (bool)(nil),
  Field:         51235,
  Name:          "store.index",
  Tag:           "varint,51235,opt,name=index",
}
```

Which fails to compile because bool can not be cast to nil:

```
store.pb.go:58: cannot convert nil to type bool
store.pb.go:66: cannot convert nil to type bool
```

**Comment by awalterschulze** [comment]
Have you tried this with golang/protobuf, because I suspect they will have the same problem.  Otherwise I'll look into this tonight, if I get time.

**Comment by awalterschulze** [comment]
Wait a second no, that doesn't make sense.  I have many bool extensions.

```
var E_GoprotoEnumPrefix = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62001,
	Name:          "gogoproto.goproto_enum_prefix",
	Tag:           "varint,62001,opt,name=goproto_enum_prefix,json=goprotoEnumPrefix",
}
```

**Comment by awalterschulze** [comment]
Which protoc-gen-xxx are you using?

**Comment by alecthomas** [comment]
This was with proto3. I will send through reproducible samples in a bit. The standard proto compiler works. It was compiled with the one that generates .Equals()

**Comment by alecthomas** [comment]
Here's the test file:

```proto
syntax = "proto3";

package test;

import "google/protobuf/descriptor.proto";


extend google.protobuf.MessageOptions {
  bool stored = 51234;
}

extend google.protobuf.FieldOptions {
  bool primary = 51234;
  bool index = 51235;
}

message FieldMask {
  repeated string paths = 1;
}
```

Here are the two commands:

Works:

```
protoc -I/usr/local/Cellar/protobuf/3.1.0/include -I. --go_out=plugins=grpc:. ./test.proto
```

Does not work:

```
protoc -I/usr/local/Cellar/protobuf/3.1.0/include -I. --gogoslick_out=plugins=grpc:. ./test.proto
```

fast and faster also generate the same code.

**Comment by awalterschulze** [comment]
It makes sense that gogofaster and gogoslick will do this since it enables nullable=false for all fields.
Are you sure gogofast_out and gofast_out does this?

**Comment by awalterschulze** [comment]
Ok I see this is definitely just happening with gogoprotobuf.

**Comment by awalterschulze** [comment]
This should fix it and test it for future.
https://github.com/gogo/protobuf/commit/e9acdbd3df86a768398d7d5ebd0c2d8b0950c85b

Thanks for reporting

**Comment by alecthomas** [comment]
Thanks for fixing!

**Comment by awalterschulze** [comment]
Always a pleasure working with you.
