### ISSUE TITLE
Option to generate camelCase json field names

### ISSUE THREAD

**Issue by nekto0n** [gogo/protobuf#206]
Hi there!
First of all: thanks for such a great library!
We've got a service which is protobuf based, but for AJAX requests from browsers we marshall protobuf objects into json. There is also a great library [easyjson](https://github.com/mailru/easyjson/) which allows generating marshall methods for structs. I tried to use it as a drop-in replacement for reflection based `jsonpb` marshaller in gogo, but `json` tags in generated `.pb.go` files use snake_case names.
So, my proposal is to add an option to generate camelCase names (same as in `proto` annotation). It looks like [this](https://github.com/nekto0n/protobuf/commit/413219b36b3eda0125b84d9b9cb2be18b2291a7d#diff-c5ab46099bd055be2629de524005c350R2085). I'm not quite sure where to add this option: in `gogo` (generate camelCase) or `easyjson` (take tag from protobuf annotation), so no pull request yet.
What do you think?

**Comment by awalterschulze** [comment]
Did you notice that there is already a jsontag override extension?
https://github.com/nekto0n/protobuf/commit/413219b36b3eda0125b84d9b9cb2be18b2291a7d#diff-c5ab46099bd055be2629de524005c350R2093
So this will require some manual work by the user the specify the jsontag manually for every field.
But you can use a vanity binary to programmatically do this for you.

Maybe you could do something like this
https://github.com/gogo/protobuf/blob/master/protoc-gen-gogofaster/main.go#L45
It enables the nullable extension for most fields nullable=false.
You could do the same and set the gogoproto.jsontag to the camelcase of the field name.

What do you think?

**Comment by nekto0n** [comment]
I guess I could try vanity binary way. Thanks!

What do you think about my approach and/or about faster json marshalling/unmarshalling in gogo?

**Comment by awalterschulze** [comment]
When you already have proto files setup, I think json is purely for debugging and not for speed.
But I don't see a reason why you can't have both and that a json generator and a proto generator can't live side by side.  
You could even use the same vanity binary approach as this example
https://github.com/gogo/protobuf/blob/master/protoc-gen-gostring/main.go
Then you can generate the json methods in a separate file.
What do you think?

**Comment by nekto0n** [comment]
Great, I'll play with that approach, thanks!

**Comment by awalterschulze** [comment]
any luck?
