### ISSUE TITLE
If you use a proto package named data, invalid code is generated

### ISSUE THREAD

**Issue by johanbrandhorst** [gogo/protobuf#208]
The input variable to the "Unmarshal" function is called "data", which shadows the use of the package "data" when imported. This results in an invalid generated file.

**Comment by awalterschulze** [comment]
Cool I have had a similar problem before.
I'll rename all the `data` words to `dAtA`

**Comment by awalterschulze** [comment]
This fix is going to take a while, since I am moving soon.
Please feel free to make a contribution with a test if you need this fix sooner.

**Comment by johanbrandhorst** [comment]
I'll give it a go, thanks!

**Comment by johanbrandhorst** [comment]
Probably not gonna have much time to look at this myself in the coming days either, but if I do get free time and it's not done I will.

**Comment by johanbrandhorst** [comment]
See #215 for my first attempt at fixing this.
