### ISSUE TITLE
When using the stdtime plugin with every google.protobuf.Timestamp in a protofile, generated code contains unused import "github.com/golang/protobuf/ptypes/timestamp"

### ISSUE THREAD

**Issue by johanbrandhorst** [gogo/protobuf#209]
Simple example to reproduce:

```
syntax = "proto3";

import "google/protobuf/timestamp.proto";

message Thing {
    google.protobuf.Timestamp date = 1 [(gogoproto.stdtime) = true];
}
```

The generated file imports `github.com/golang/protobuf/ptypes/timestamp` but then wont compile, because it is unused. Also applies to generated tests.

**Comment by johanbrandhorst** [comment]
I'm not using the M parameter for the timestamp.proto, just running protoc with gogo_out yields this. I wasn't aware of the M parameter options for gogo protobuffers. Do you think this is working as intended when the user is ignorant of the "correct" settings?

**Comment by johanbrandhorst** [comment]
I can provide a simple gist for this if you would like it.

**Comment by awalterschulze** [comment]
I'll have to think about this.

**Comment by johanbrandhorst** [comment]
It also appears to be generating invalid code when I'm using the gogo type:
```
level1/level1.pb.go:19: imported and not used: "github.com/gogo/protobuf/types" as google_protobuf    
```

**Comment by awalterschulze** [comment]
I think I only tested when I used both time.Time and timestamp and not time.Time alone.  This is a bug :)

**Comment by johanbrandhorst** [comment]
Indeed, I did take a look at the example implementation. You're amazingly responsive by the way, mad props!

**Comment by johanbrandhorst** [comment]
This gist should reproduce it as well:

https://gist.github.com/johanbrandhorst/715a061bb4610a39c35396800c2a3121

**Comment by awalterschulze** [comment]
I hope to get a chance to look at all your problems tomorrow night. Sorry to disappoint on the responsiveness.

**Comment by awalterschulze** [comment]
This should fix it
https://github.com/gogo/protobuf/commit/45378b5eef9c4105423260005ed829ad79f2691a

Please also check the Makefile in the commit for how to use it.

Just a note:  using `import weak` instead of `import` might also work instead of using the `M` parameters.
