### ISSUE TITLE
issue with grpc-gateway and well known types: github.com/golang/protobuf/ptypes vs github.com/gogo/protobuf/types

### ISSUE THREAD

**Issue by johanbrandhorst** [gogo/protobuf#210]
Hi,

When using `import "google/protobuf/empty.proto"` and using `gogo_out` to generate the files we end up with a go import looking like this:

```
import google_protobuf1 "github.com/gogo/protobuf/types"
```

This is clashing with the imports generated by the grpc-gateway_out, which use the following:

```
"github.com/golang/protobuf/ptypes/empty"
```

So when the grpc-gateway tries calling into functions generated by gogo_out, it will use the `empty.Empty` struct, while the function signature expectes a `types.Empty`

The source of this error took a while to nail down, but it appears that the version of empty.proto in this repo that is used to generate the custom empty.pb.go is too old.

Specifically the `go_package` option is an old value. In newer versions it should be

```
option go_package = "github.com/golang/protobuf/ptypes/empty";
```

Currently in this repo it is

```
option go_package = "types";
```

So it should just be a matter of updating the google/protobuf reference and regenerating the files.

References:
Up-to-date google/protobuf: https://github.com/google/protobuf/blob/master/src/google/protobuf/empty.proto
Up-to-date golang/protobuf: https://github.com/golang/protobuf/blob/master/ptypes/empty/empty.proto

**Comment by awalterschulze** [comment]
gogoprotobuf's is also up to date
https://github.com/gogo/protobuf/blob/master/protobuf/google/protobuf/empty.proto

I specifically change the go_package name to types instead of ...ptypes/empty
https://github.com/gogo/protobuf/blob/master/protobuf/Makefile#L18

**Comment by awalterschulze** [comment]
You could try using the -M parameter with grpcgateway_out to try and fix the import?
https://github.com/gogo/protobuf/blob/master/test/types/Makefile#L33

**Comment by awalterschulze** [comment]
Thanks :)
Feel free to cc me please.

**Comment by awalterschulze** [comment]
Reference https://github.com/grpc-ecosystem/grpc-gateway/issues/229#issuecomment-251909756
