### ISSUE TITLE
Invalid JSON is generated with `gogo/protobuf`'s jsonpb.Marshaler

### ISSUE THREAD

**Issue by liranp** [gogo/protobuf#216]
In continue to issue #212, I'm opening a new issue cause they're not necessarily related to each other. 

I have changed my gRPC gateway server to use `gogo/protobuf`'s `jsonpb.Marshaler` instead the one from `golang/protobuf`. I'm having another issue now; since the change, all JSON messages are marshaled by the `jsonpb.Marshaler`, but it uses the `json` field from the `protobuf` tag instead of the `json` tag (even if I'm using `[(gogoproto.jsontag) = "..."]`; which just [overrides](https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/generator/generator.go#L2096-L2099) the `json` tag if I understood correctly).

Let's say I have the following message in my `.proto` file:
```
message Value {
    string foo_bar = 1;
}
```
In the `.pb.go` this translated to:
```go
type Value struct {
	FooBar    string     `protobuf:"bytes,2,opt,name=foo_bar,json=fooBar,proto3" json:"foo_bar"`
}
```
So, the JSON looks like:
```json
{
    "value": {
        "fooBar": "baz"
    }
}
```
While (at least for my understanding) the expected result is (like it worked before):
```json
{
    "value": {
        "foo_bar": "baz"
    }
}
```

What am I missing?
Any help will be much appreciated!

**Comment by liranp** [comment]
I've found the answer, but perhaps we should keep this issue as closed for documentation purposes. 

If no `WithMarshalerOption` is provided to the grpc-gateway's `NewServeMux` function, it uses a default marshaler which is the `jsopb.Marshaler` from `golang/protobuf`, and it instantiates it like [this](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/marshaler_registry.go#L16):
```go
defaultMarshaler = &JSONPb{OrigName: true}
```

So, the solution for me was just to set the `OrigName` to true as well.

**Comment by awalterschulze** [comment]
Thanks for providing the answer, this is great :)
