### ISSUE TITLE
Using protosize_all and sizer_all with a oneof generates invalid code

### ISSUE THREAD

**Issue by johanbrandhorst** [gogo/protobuf#222]
Here's a gist that reproduces the problem:
https://gist.github.com/johanbrandhorst/880326d70e69d191d7560fd498031605

Essentially, the interface is created with the `ProtoSize` method, but it is not implemented, presumably because there is some check to prevent both `ProtoSize` and `Size` methods to be generated. I would suggest a compile time warning here if possible.

``` go
type isValue_Type interface {
    isValue_Type()
    Size() int
    ProtoSize() int
}
```

**Comment by awalterschulze** [comment]
Yes a generation time warning should already exist, this is weird.

Something here would be nice
https://github.com/gogo/protobuf/blob/master/plugin/size/size.go#L581

That throws an error, not just a warning, like this
https://github.com/gogo/protobuf/blob/master/plugin/defaultcheck/defaultcheck.go#L116

**Comment by johanbrandhorst** [comment]
Cool, I'll take a look, thanks for the pointers.

**Comment by awalterschulze** [comment]
You still want to take a look?

**Comment by johanbrandhorst** [comment]
Sorry, I got sidetracked on this one, I'll take another look! :100:
