### ISSUE TITLE
Update SupportPackageIsVersion3 to Version4

### ISSUE THREAD

**Issue by davidmhudson** [gogo/protobuf#225]
Related closed issue: https://github.com/gogo/protobuf/issues/185

Looks like the same issue but now it's just needing updated from `SupportPackageIsVersion3` to `SupportPackageIsVersion4`.

If more information would be required, I'll happily expand.

**Comment by awalterschulze** [comment]
Seems I am about 10 commits behind.
https://github.com/gogo/protobuf/issues/191

Hopefully I'll get some time this weekend.

**Comment by awalterschulze** [comment]
all commits up to 3 Nov have been merged.
