### ISSUE TITLE
Feature request: Extension to create setter for `oneof`

### ISSUE THREAD

**Issue by atombender** [gogo/protobuf#226]
Consider this "polymorphic" message:

```proto
message AnyError {
  oneof Value {
    QueryError query = 1;
    MutationError mutation = 2;
    // ... etc.
  }
}
```

If I have a method that returns `QueryError` and I want to turn that into an `AnyError`, I have to build a manual switch statement for every possible value:

```go
func WrapAnyError(err proto.Message) *AnyError {
  var result AnyError
  switch t := err.(type) {
  case *MutationError:
    result.Value = &AnyError_Mutation{
      Mutation: t,
    }
  case *QueryError:
    result.Value = &AnyError_Query{
      Query: t,
    }
  // ... etc.
  }
  return &result
}
```

It would be nice if Gogo, which already has this information, could provide a setter that allowed me to simply do:

```go
func WrapAnyError(err proto.Message) *AnyError {
  var result AnyError
  if e := result.SetValue(err); e != nil {
    panic(e)
  }
  return &result
}
```

**Comment by awalterschulze** [comment]
I think should be part of the discussion in https://github.com/gogo/protobuf/issues/168
You can have this type of code generation using the onlyone extension, but its kind of deprecated, since we should be able to figure out something better for oneof.
