### ISSUE TITLE
Generating cleaner package names

### ISSUE THREAD

**Issue by rogeralsing** [gogo/protobuf#228]
I'm building a cusom generator.
If I use the `NewImport` func to get a package reference, like so

```go
logg = p.NewImport("log")
time = p.NewImport("time")
grains = p.NewImport("github.com/AsynkronIT/gam/cluster/grains")
cluster = p.NewImport("github.com/AsynkronIT/gam/cluster")
actor = p.NewImport("github.com/AsynkronIT/gam/actor")
```

and then emit the reference like so:
```
p.P(grains.Use(), ".GrainMixin")
```

The emitted package name becomes the full github path but in an escaped format.
Is this the only way to do this?
It makes intellisense help look strange when working with the generated types.
```go
github_com_AsynkronIT_gam_cluster_grains.GrainMixin
```

It would have been nice with just `grains.GrainMixin`

**Comment by awalterschulze** [comment]
Can't intellisense handle renamed package names, thats quite a bug?

By emitting the full package name I skip the logic of having to do more book keeping about duplicate package name suffixes.

"my/math"
"her/math"

I think I even started out only using the prefixes with a number.

math "my/math"
math1 "her/math"

But this ended up causing non deterministic output and quite a few other problems.
Maybe I just did it wrong.

Won't a package name like math1 also confuse with intellisense?

**Comment by awalterschulze** [comment]
closing since no response, please reopen if you want to respond.
