### ISSUE TITLE
gostring_all generates invalid code if gogoprotobuf is not imported.

### ISSUE THREAD

**Issue by ains** [gogo/protobuf#243]
If a file is processed by the gostring plugin (gostring_all in particular, because gostring will then be run on files which don't necessarily have to import gogoprotobuf) the generated code will attempt to use the method GetUnsafeExtensionsMap from "github.com/golang/protobuf/proto" where it doesn't exist, instead of "github.com/gogo/protobuf/proto" where it does.

The issue was introduced in 
https://github.com/gogo/protobuf/commit/6abcf94fd4c97dcb423fdafd42fe9f96ca7e421b#diff-bebe69f1868bace0174c76c29e8d628fR336

Due to the conditional at
https://github.com/gogo/protobuf/blob/master/plugin/gostring/gostring.go#L140

I'll submit a PR which doesn't generate this method if your message does not have extensions or an extension map, which resolves our issue as we don't use this feature, but the underlying issue will remain.

**Comment by awalterschulze** [comment]
Yes extensions are not really supported when gogoprotobuf is not imported, but when extensions are not used in any of your structs gostring should work.
I will appreciate a pull request.

**Comment by awalterschulze** [comment]
Please add yourself to the CONTRIBUTORS or AUTHORS file as appropriate, if you want to.

**Comment by ains** [comment]
Thanks for the quick response!

That PR actually needs more thought than just a quick one liner in the Github web UI, will fix it properly and send one in!

**Comment by awalterschulze** [comment]
Awesome looking forward to it :)

**Comment by awalterschulze** [comment]
fixed by #245
