### ISSUE TITLE
Generate non-packed []int32 etc with gogofast?

### ISSUE THREAD

**Issue by calmh** [gogo/protobuf#246]
We (Syncthing) use the gogofast generator, and until recently code generated by a fairly old version of it - we committed the generated code on Jul 4, 2016. Recently we updated a couple of protocol definitions, regenerated with current master, and ran into some issues. Specifically, []int32 and similar types are now packed, which of course is entirely correct. Unfortunately our currently released versions don't understand that, as it was not supported by gogofast at the time.

Is there an option we could use to generate non-packed slices, but still use the newer code and hence unmarshaller? We could roll that out, wait a couple of months, and then update the marshaller to properly generate packed slices when most users have upgraded. Currently I've backed out that part of the diff manually, but it's prone to getting blown away whenever we update a field and regenerate...

**Comment by awalterschulze** [comment]
This seems to be the change that must be affecting you in some way
https://github.com/gogo/protobuf/commit/3660948db4266bc218b5ee7321966626ab44297c

But when looking at plugin/unmarshal.go it seems unmarshaling for packed types is supposed to also support the fallback of trying to unmarshal the repeated field in the non packed form.  

Does this help?

**Comment by calmh** [comment]
Yes, that's the change. Perhaps I described it poorly. The problem is that when using code generated prior to that change, the *unmarshaller* doesn't understand packed fields. So messages marshalled by the new code cause a `incorrect wireType =2 for ...` error on the older receiving side. I'd like to temporarily switch the new marshaller to writing non-packed fields for compatibility's sake, and then at some point in the future when the new unmarshaller is common switch that off again.

**Comment by Thomasdezeeuw** [comment]
A test file mentions `packed=false`: https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/testdata/proto3.proto#L47, does that work? I haven't tried it myself.

**Comment by calmh** [comment]
It does, and I'm a muppet for missing it. I went looking among the extensions... Thank you!

**Comment by calmh** [comment]
Actually no, sorry, it's still packed. :(

**Comment by awalterschulze** [comment]
Thats a bug :)

**Comment by awalterschulze** [comment]
This should fix it
https://github.com/gogo/protobuf/commit/3fd451e252e307ed726b8be170fa945a6fae8262

**Comment by calmh** [comment]
This unfortunately doesn't really do what I want either. :) With `packed=false` the unmarshaller will again reject packed fields, so we can never move away from it towards using packed fields. It would be nice if the unmarshaller was more liberal and accepted both, while the marshaller followed the `packed=false` directive when writing?

**Comment by awalterschulze** [comment]
Good point.  This should work now
https://github.com/gogo/protobuf/commit/f6b4bb7b2dde1736b809b3da996ed72f278e9be9
