### ISSUE TITLE
customtype with package causes spurious import

### ISSUE THREAD

**Issue by calmh** [gogo/protobuf#247]
I have a `bep.proto` that defines the `protocol` package:

```protobuf
syntax = "proto3";

package protocol;

// stuff
```

and another package that uses it:

```protobuf
syntax = "proto3";

package db;

import "github.com/gogo/protobuf/gogoproto/gogo.proto";
import "github.com/syncthing/syncthing/lib/protocol/bep.proto";

//...

message FileInfoTruncated {
    // ...
    uint64                modified_by    = 12 [(gogoproto.customtype) = "protocol.ShortID", (gogoproto.nullable) = false];
}

/// more stuff
```

The `protocol.ShortID` type is not defined in the `bep.proto` file - it is a simple `type ShortID uint64` defined elsewhere in the normal Go code for the `protocol` package.

This, using `protoc -I ../../../../../ -I ../../../../gogo/protobuf/protobuf -I . --gogofast_out=. structs.proto` then generates:

```go
// Code generated by protoc-gen-gogo.
// source: structs.proto
// DO NOT EDIT!

// ...
package db

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import protocol "github.com/syncthing/syncthing/lib/protocol"

import protocol "protocol"

import io "io"
```

Note that `protocol` is imported an extra time, with an incorrect import path. This is trivial to remove, but of course fails the build. Removing the customtype makes the extra import go away.

**Comment by awalterschulze** [comment]
You need to include the full gopath you want to generate in customtype.
So

```
message FileInfoTruncated {
    // ...
    uint64                modified_by    = 12 [(gogoproto.customtype) = "github.com/syncthing/syncthing/lib/protocol.ShortID", (gogoproto.nullable) = false];
}
```

**Comment by awalterschulze** [comment]
Please reopen if this does not fix your problem.

**Comment by calmh** [comment]
It works, although it results in a double import.

```
import protocol "github.com/syncthing/syncthing/lib/protocol"
import github_com_syncthing_syncthing_lib_protocol "github.com/syncthing/syncthing/lib/protocol"
```

This compiles and I think it's OK (same package, two names), if odd.

**Comment by awalterschulze** [comment]
Yes its a little odd, but not the end of the world.
