### ISSUE TITLE
influx db compilation

### ISSUE THREAD

**Issue by pranabpal** [gogo/protobuf#249]
during compilation of influx db - i am getting this error
C:\Go\src\vendor\github.com\influxdata\influxdb\influxql\point.go:11:2: non-stan
dard import "github.com/gogo/protobuf/proto" in standard package "vendor/github.
com/influxdata/influxdb/influxql"
C:\Go\src\vendor\github.com\influxdata\influxdb\influxql\internal\internal.pb.go
:23:8: non-standard import "github.com/gogo/protobuf/proto" in standard package
"vendor/github.com/influxdata/influxdb/influxql/internal"
C:\Go\src\vendor\github.com\influxdata\influxdb\tsdb\meta.go:17:2: non-standard
import "github.com/gogo/protobuf/proto" in standard package "vendor/github.com/i
nfluxdata/influxdb/tsdb"
C:\Go\src\vendor\github.com\influxdata\influxdb\tsdb\internal\meta.pb.go:19:8: n
on-standard import "github.com/gogo/protobuf/proto" in standard package "vendor/
github.com/influxdata/influxdb/tsdb/internal"
C:\Go\src\vendor\github.com\influxdata\influxdb\cmd\influx_tsm\tsdb\types.go:10:
2: non-standard import "github.com/gogo/protobuf/proto" in standard package "ven
dor/github.com/influxdata/influxdb/cmd/influx_tsm/tsdb"
C:\Go\src\vendor\github.com\influxdata\influxdb\cmd\influx_tsm\tsdb\internal\met
a.pb.go:19:8: non-standard import "github.com/gogo/protobuf/proto" in standard p
ackage "vendor/github.com/influxdata/influxdb/cmd/influx_tsm/tsdb/internal"
package ./cmd/influx_tsm/tsdb
        imports github.com/influxdata/influxdb/cmd/influx_tsm/tsdb/internal: use
 of internal package not allowed
C:\Go\src\vendor\github.com\influxdata\influxdb\services\admin\service.go:12:2:
non-standard import "github.com/rakyll/statik/fs" in standard package "vendor/gi
thub.com/influxdata/influxdb/services/admin"
C:\Go\src\vendor\github.com\influxdata\influxdb\services\admin\statik\statik.go:
4:2: non-standard import "github.com/rakyll/statik/fs" in standard package "vend
or/github.com/influxdata/influxdb/services/admin/statik"
C:\Go\src\vendor\github.com\influxdata\influxdb\services\meta\data.go:13:2: non-
standard import "github.com/gogo/protobuf/proto" in standard package "vendor/git
hub.com/influxdata/influxdb/services/meta"
C:\Go\src\vendor\github.com\influxdata\influxdb\services\meta\internal\meta.pb.g
o:58:8: non-standard import "github.com/gogo/protobuf/proto" in standard package
 "vendor/github.com/influxdata/influxdb/services/meta/internal"
C:\Go\src\vendor\golang.org\x\crypto\bcrypt\bcrypt.go:15:2: non-standard import
"golang.org/x/crypto/blowfish" in standard package "vendor/golang.org/x/crypto/b
crypt"
package ./influxql
        imports github.com/influxdata/influxdb/influxql/internal: use of interna
l package not allowed
package ./services/meta
        imports github.com/influxdata/influxdb/services/meta/internal: use of in
ternal package not allowed
package ./tsdb
        imports github.com/influxdata/influxdb/tsdb/internal: use of internal pa
ckage not allowed

**Comment by calmh** [comment]
You have an incorrect Go setup, installing custom packages into your Go root. By default the Go compiler lives in C:\Go on Windows. This is not where you put *your* packages.

**Comment by pranabpal** [comment]
I am following this video [https://www.youtube.com/watch?v=34oOp1OLOUk&index=1&list=PLHoJlLKqR9v81o4eFbQKUScfW1akx22Eq] and try to compile the influx DB.

If you have any handy document on installation windows 7- then please share with me on the installation.
Thanks in advance.

Regards
Pranab

**Comment by awalterschulze** [comment]
Maybe you want to report this issue to influxdb?

**Comment by pranabpal** [comment]
Now i am getting this error in InfluxDB setup.

C:\Go\projects\github.com\influxdata\influxdb>go get -u -f ./..
package _/C_/Go/projects/github.com/influxdata: unrecognized import path "_/C_/G
o/projects/github.com/influxdata" (import path does not begin with hostname)

C:\Go\projects\github.com\influxdata\influxdb>go build ./..
can't load package: package ./..: no buildable Go source files in C:\Go\projects
\github.com\influxdata


Can any one help me in this regard?

**Comment by awalterschulze** [comment]
influxdb might be able to help, but I am not, sorry.

**Comment by pranabpal** [comment]
Waiting from techies for a resolution of this issue?
