### ISSUE TITLE
Resolving paths on Windows

### ISSUE THREAD

**Issue by rogeralsing** [gogo/protobuf#251]
I'll corss post this here.
I'm not sure if this is gogoslick or protoc itself that is the issue here.
https://github.com/google/protobuf/issues/2577

If I have imports that are mapped with the "M" setting, like so:
`gogoslick_out=Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types`

This works nice on *nix systems.
But the file will not be found on Windows.

I have verified that the file is indeed at the location specified, but I still get the error when trying to generate.

Currently I solved this by introducing a "google/protobuf" folder in one of the protopath folders.
And placed the relevant protos in there.

I do suspect this is a matter of `/` vs `\`

Anyone else having problems with this?

**Comment by awalterschulze** [comment]
Hmmm interesting.
I was wondering whether you could try 
```
go_out=Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types
```
With golang/protobuf/protoc-gen-go
Instead of gogoslick_out

I am wondering whether its a gogoprotobuf or a golang/protobuf issue

**Comment by rogeralsing** [comment]
Ah, good thinking, I've tried the same now, still same result

GOPATH is `C:\projects`

```
C:\projects\src\github.com\AsynkronIT\protoactor-go\actor>protoc -I=. -I=c:\projects\src --go_out=Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,plugins=grpc:. protos.proto
google/protobuf/any.proto: File not found.
google/protobuf/descriptor.proto: File not found.
github.com/gogo/protobuf/gogoproto/gogo.proto: Import "google/protobuf/descriptor.proto" was not found or had errors.
github.com/gogo/protobuf/gogoproto/gogo.proto:37:8: "google.protobuf.EnumOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.EnumOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.EnumOptions" is not defined.
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.EnumOptions" is not defined.
```

So I move over to golang/protobuf?

**Comment by awalterschulze** [comment]
Lets see what they say.

**Comment by rogeralsing** [comment]
If anyone else stumbles across this. see https://github.com/golang/protobuf/issues/279
