### ISSUE TITLE
stdduration extension doesn't work with gogo{fast,faster,slick}

### ISSUE THREAD

**Issue by abecciu** [gogo/protobuf#252]
I tried the new `stdduration` extension, but I could only get it to work with `gogo_out`. It's ignored by the other code generators. Am I missing something? Thanks!

**Comment by awalterschulze** [comment]
Could you provide a breaking example please?

**Comment by abecciu** [comment]
@awalterschulze here's an example: https://gist.github.com/abecciu/07c79f52425bc8b3f9a3b9f2dac1a38d

**Comment by awalterschulze** [comment]
The Makefile works for me and generates time.Duration.
Have you tried maybe updating gogoprotobuf and clearing out all old versions of protoc-gen-gogoslick?

**Comment by abecciu** [comment]
@awalterschulze you're right. Sorry for the silly question. Thanks!!
