### ISSUE TITLE
gostring generates uncompilable code for stdduration and stdtime when nullable=false

### ISSUE THREAD

**Issue by abecciu** [gogo/protobuf#253]
Here is an example that triggers the bug: https://gist.github.com/abecciu/f17147492c968215a9f8b9f5eea93053

When I run `go build` in the example code, I get the error

```
./t.pb.go:89: this.Dur.GoString undefined (type time.Duration has no field or method GoString)
```

This only happens with gogoslick. It works flawlessly with all the other generators.

**Comment by awalterschulze** [comment]
The gostring plugin seems to have problems with nullable=false for time.Duration and time.Time

You could fix it in the mean time by turning off the gostring plugin.
Also its not necessary to turn on marshaler, unmarshaler and size, this is already done by gogoslick.

```
syntax = "proto3";

package test;
option go_package = "main";

import "github.com/gogo/protobuf/gogoproto/gogo.proto";
import "google/protobuf/duration.proto";

option (gogoproto.goproto_getters_all) = false;
option (gogoproto.gostring_all) = false;

message Test {
  google.protobuf.Duration dur = 1 [(gogoproto.jsontag) = "dur", (gogoproto.stdduration) = true, (gogoproto.nullable) = false];
}
```

**Comment by awalterschulze** [comment]
This should fix the issue https://github.com/gogo/protobuf/commit/6e505820968158ec7ac58ea92bba501a82b41171

**Comment by abecciu** [comment]
Awesome! Thanks @awalterschulze!

**Comment by awalterschulze** [comment]
Thanks for reporting :)
