### ISSUE TITLE
Typedecl false + stdtime generates unused import.

### ISSUE THREAD

**Issue by Serabe** [gogo/protobuf#260]
If a message has the option typedecl false and is using the stdtime extension (non nullable), then an import for the package "time" is generated even if it is not needed.

**Comment by Serabe** [comment]
Open so the test can reference this issue.

**Comment by Thomasdezeeuw** [comment]
I think https://github.com/gogo/protobuf/pull/258 ment closed this?

**Comment by awalterschulze** [comment]
Yes Thank you
