### ISSUE TITLE
stdtime generation broken, no longer imports time.Time

### ISSUE THREAD

**Issue by dbudworth** [gogo/protobuf#262]
When using:
`import "google/protobuf/timestamp.proto";`
and
`google.protobuf.Timestamp archived_at = 4 [(gogoproto.stdtime) = true];`

time.Time is no longer imported

I assume it's related to: https://github.com/gogo/protobuf/commit/2221ff550f109ae54cb617c0dc6ac62658c418d7 as it just broke in the last several hours.

Do we need to do something else to get time to import?  I couldn't quite tell from the comments in https://github.com/gogo/protobuf/blob/master/test/issue260/README.md

For what it's worth, I'm using gogoslick to genereate

**Comment by awalterschulze** [comment]
Could you also provide a sample proto file that breaks this please?

@dbudworth does https://github.com/gogo/protobuf/pull/261 fix your problem?

@Serabe maybe this is also worth noting.

**Comment by Serabe** [comment]
Providing a test is taking me longer than expected, but I am on it. More on this soon.

**Comment by dbudworth** [comment]
for my use case, i just added `g.useTime()` to both cases at https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/generator/generator.go#L1884

logic being, if I have a field of type time.Time, i must import it.   
May not be complete enough, but it solved my case.

#261 possibly fixes it, though it's a much bigger change and doesn't specifically touch that switch statement.  WIll try it in a bit.

as for reproducible case, will put something together today as well

**Comment by dbudworth** [comment]
also #261 seems to add the useTime call to every if/else case in unmarshall.  Could be simplified to a single line at top checking for IsStdTime.  

that said, it also doesn't fix my use case, will make a simple .proto fill to demo

**Comment by dbudworth** [comment]
my bad, #261 does fix my issue.   I needed to refresh my editor to see the time.Time import show up

**Comment by awalterschulze** [comment]
Unfortunately its not as simple as importing time when the struct has a time field, since the gogoproto.typedecl extension allows you to not generated the type declaration and then you don't always need to import time.

**Comment by dbudworth** [comment]
got it, yep, i'm not as familiar with all the edge cases.

that said: https://github.com/dbudworth/timefail

simplest example I could make that shows the issue with HEAD right now (pre #261 merge)
I can make in to a real test case later if you like, I just wasn't sure how to do quickly

**Comment by dbudworth** [comment]
Note, there's 2 commits in there.  before HEAD (pre #261) and the last one (with #261 applied locally)

yes, I should have done that better.   Just wanted to give you before / after quickly.

**Comment by johanbrandhorst** [comment]
Having this issue as well.

**Comment by awalterschulze** [comment]
I have added the test case
https://github.com/gogo/protobuf/tree/master/test/issue262
Also remember to use the -M parameter to rename your google/protobuf imports.

Lets wait for the build server, but it might all be fixed now.

**Comment by awalterschulze** [comment]
Ok it should be fixed now
https://github.com/gogo/protobuf/commit/378d8e6701762213272d3cb98c56a483be36b2c5
