### ISSUE TITLE
Problem with stdtime when the type is inside a map.

### ISSUE THREAD

**Issue by Serabe** [gogo/protobuf#264]
_Original thread https://github.com/gogo/protobuf/pull/261#issuecomment-280297014 (is a PR)_

If we have a field whose type is a map with `Timestamp` as its value type, and the `stdtime` is used in that field, then the imports are broken because...

1. [`GoMapType`](https://github.com/gogo/protobuf/blob/d2e1ade2d719b78fe5b061b4c18a9f7111b5bdc8/protoc-gen-gogo/generator/generator.go#L1919) gets called with the `FieldDescriptorProto` of the field itself.
2. In `GoMapType`, `GoType` is called for both the key and value types but...
3. Protobuf have no notion of types, but of fields, and therefore, bot the key and value ~types~ fields are not aware of the options in the map ~type~ field.

**Comment by awalterschulze** [comment]
Is this broken on the current master?

**Comment by awalterschulze** [comment]
I think these two fix the problem
https://github.com/gogo/protobuf/commit/f1756eb6594909c6b25c3f4be28a127aa16b28a7
https://github.com/gogo/protobuf/commit/83faaee7bbbdf0c59310ec67d340bc0cbe77053f
The problem was in the unmarshal plugin that RecordsTypeUse for alias types.
