### ISSUE TITLE
Cannot enable unsafe unmarshall

### ISSUE THREAD

**Issue by tomwilkie** [gogo/protobuf#265]
I get the following error, which I don't understand:

```
protoc -I ./vendor:./. --gogoslick_out=plugins=grpc:./. ./cortex.proto
panic: unsafe_marshaler and marshalto enabled for WriteRequest

goroutine 1 [running]:
panic(0x68cb00, 0xc420187e80)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/gogo/protobuf/plugin/marshalto.(*marshalto).Generate(0xc42007e280, 0xc4200dc480)
	/go/src/github.com/gogo/protobuf/plugin/marshalto/marshalto.go:1274 +0x4d01
github.com/gogo/protobuf/protoc-gen-gogo/generator.(*Generator).runPlugins(0xc420084f00, 0xc4200dc480)
	/go/src/github.com/gogo/protobuf/protoc-gen-gogo/generator/generator.go:1225 +0x5c
github.com/gogo/protobuf/protoc-gen-gogo/generator.(*Generator).generate(0xc420084f00, 0xc4200dc480)
	/go/src/github.com/gogo/protobuf/protoc-gen-gogo/generator/generator.go:1281 +0x3b9
github.com/gogo/protobuf/protoc-gen-gogo/generator.(*Generator).GenerateAllFiles(0xc420084f00)
	/go/src/github.com/gogo/protobuf/protoc-gen-gogo/generator/generator.go:1211 +0x262
github.com/gogo/protobuf/vanity/command.Generate(0xc420014230, 0x2)
	/go/src/github.com/gogo/protobuf/vanity/command/command.go:131 +0x244
main.main()
	/go/src/github.com/gogo/protobuf/protoc-gen-gogoslick/main.go:57 +0x2ca
--gogoslick_out: protoc-gen-gogoslick: Plugin failed with status code 2.
Makefile:81: recipe for target 'cortex.pb.go' failed
```

Here's the proto: https://github.com/weaveworks/cortex/pull/296/commits/dbb4d55e90a87578a50d71f3a1ed90a0a8b07f25

Is it because I'm using `[(gogoproto.nullable) = false]` on some of the fields?

Can unsafe unmarshaling be enable on a subset of messages?

Thanks!

**Comment by tomwilkie** [comment]
Looks like this might be because I'm using gogoslick?

**Comment by awalterschulze** [comment]
gogoslick already enables the generation of MarshalTo and Unmarshal methods
https://github.com/gogo/protobuf/blob/master/protoc-gen-gogoslick/main.go#L41

cortex.proto currently has 
```
option (gogoproto.marshaler_all) = true;
option (gogoproto.unmarshaler_all) = true;
```
Are you sure you didn't have `option (gogoproto.unsafe_marshaler_all)=true`
?

But either way you can remove those options and you should still get the generated Marshal and Unmarshal methods and more.

**Comment by tomwilkie** [comment]
Yeah, I had `unsafe_marshaler_all` set but the change has been rebased away.  I was trying to get unsafe-enabled unmarshall, as I was getting a log of overhead from copying strings.  But then I realised unsafe didn't avoid the string copy, so I made a custom type that did (see https://github.com/weaveworks/cortex/blob/master/util/wire/bytes.go).  It lead to a 4x reduction in my 99th percentile latency...

**Comment by awalterschulze** [comment]
If you are not using a string anymore, why do you need a customtype?

For future reference: to enable unsafe_marshaler you will to create you own vanity binary or start adding the options manually.
unsafe_marshaler only helps with fixed sized numbers.

**Comment by tomwilkie** [comment]
> If you are not using a string anymore, why do you need a customtype?

The generated code still does a copy for bytes types:

```go
m.Name = append(m.Name[:0], dAtA[iNdEx:postIndex]…)
```

> For future reference: to enable unsafe_marshaler you will to create you own vanity binary or start adding the options manually. unsafe_marshaler only helps with fixed sized numbers.

Got it, thanks!

**Comment by awalterschulze** [comment]
Aha ok now I see. On unmarshaling you avoid the copy. This does mean though
that you have to remember NOT to reuse the input byte buffer.

**Comment by tomwilkie** [comment]
> This does mean though that you have to remember NOT to reuse the input byte buffer.

Indeed; I can guarantee in my code that the buffer is not reused - still, it would be cheaper to copy the original buffer in this case (lots of small strings).

**Comment by awalterschulze** [comment]
You could also use unsafe and still have your customtype be a string. If
you ever use it as a string.

But this is definitely an interesting optimization.

**Comment by tomwilkie** [comment]
> If you ever use it as a string.

I considered this, but in the performance-sensitive component all its ever used for is a hash, which needs bytes.  I will might make that optimisation for another component though.

Would you be interested in making a "zero copy" extension for gogo?

**Comment by awalterschulze** [comment]
Might be worth looking into these issues.

Current:
https://github.com/gogo/protobuf/pull/217
https://github.com/gogo/protobuf/issues/174

Deprecated:
https://github.com/gogo/protobuf/issues/54
