### ISSUE TITLE
Suggestion: when using stdtime in proto3 files, generated time.Time fields should be a value.

### ISSUE THREAD

**Issue by alecthomas** [gogo/protobuf#267]
Currently, using stdtime with a proto3 file results in code like this:

```go
type LoginResponse struct {
	Token   string     `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Expires *time.Time `protobuf:"bytes,2,opt,name=expires,stdtime" json:"expires,omitempty"`
}
```

IMO stdtime fields should not be pointers when generating proto3 files. Rationale:

1. All stdlib functions return `time.Time` values, not pointers.
2. All other "value" types in proto3 are treated this way (string, numeric types).
3. It is awkward to deal with pointers to `time.Time`, for the same reasons that it was awkward to deal with pointers to `string` in proto2. ie. you can not do this: `r := &LoginResponse{Expires: &time.Now()}`, you have to do `now := time.Now(); r := &LoginResponse{Expires: now}`
4. `time.Time.IsZero()` can be used to check for a "valid" time.

**Comment by awalterschulze** [comment]
I agree, you can set nullable=false as an option to get time.Time without a pointer.

**Comment by alecthomas** [comment]
Aha! Thanks.

**Comment by alecthomas** [comment]
Is there any reason for this not to be the default behaviour for proto3?

**Comment by awalterschulze** [comment]
Technically time and duration are seen as structs and structs have pointers.
But I guess not.  
To change this now would break quite a few people's setups though.

**Comment by alecthomas** [comment]
Yeah, makes sense. Thanks.
