### ISSUE TITLE
Stray import when using stdtime/stdduration for map values.

### ISSUE THREAD

**Issue by geeknoid** [gogo/protobuf#273]
Using the following proto:

```
syntax = "proto3";

package istio.mixer.v1;

import "gogoproto/gogo.proto";
import "google/protobuf/timestamp.proto";

message Test {
  map<int32, google.protobuf.Timestamp> timestamp_attributes = 8 [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];
}

```
The generated .pb.go file contains an unused:

`import google_protobuf1 "github.com/gogo/protobuf/types"
`

which leads to a Go compilation error. If I remove the stdtime option, then all is well. The same import is generated, but this time it's used to reference the google.protobuf.Timestamp type.

**Comment by awalterschulze** [comment]
Have you recently updated, because I think we recently solved this issue here
https://github.com/gogo/protobuf/issues/264

**Comment by geeknoid** [comment]
Aha, we're a bit out of date. I'll update our binaries and close this issue if it's fixed.

Thanks.

**Comment by awalterschulze** [comment]
I am looking forward to hearing from you.

**Comment by geeknoid** [comment]
Given we're using bazel to drive our builds, I need to submit a change in a bazel repo (https://github.com/pubref/rules_protobuf) in order to update the gogoprotobuf bits we use in our repo (seems broken, doesn't it?). As soon as my PR is approved in the rules_protobuf repo, then I can test on my end.

**Comment by geeknoid** [comment]
Looks good.
