### ISSUE TITLE
For `moretags` option, how can I make it like `jsontag `, automatically add the camel key and omitempty

### ISSUE THREAD

**Issue by lnshi** [gogo/protobuf#277]
@awalterschulze Thank you very much for making this awesome repo and actively maintain it.

Now I am using the `moretags` feature for `bson`, just like you demoed here: https://github.com/gogo/protobuf/blob/a11c89fbb0ad4acfa8abc4a4d5f7e27c477169b1/test/tags/tags.proto 

It behaves exactly as what you described, but I am thinking how to make it just like the `jsontag`? I mean automatically generate the camel-case key and the `omitempty` tag.

---- Edited
I just submitted the PR, pls help to review, feel free to require any changes.

**Comment by awalterschulze** [comment]
I would recommend to rather create a vanity binary
for example
https://github.com/gogo/protobuf/blob/master/protoc-gen-gogofast/main.go

And then for each field add a moretags extension to that field with the camelCased and omitempty bson tag text, just like you would have manually done with moretags.

What do you think?

**Comment by lnshi** [comment]
Ah, definitely better than my approach, I don't know that functionality.

But haven't exactly understand how will it work, roughly checked a bit, so:
```
// ExtensionDesc represents an extension specification.
// Used in generated code from the protocol compiler.
type ExtensionDesc struct {
	ExtendedType  Message     // nil pointer to the type that is being extended
	ExtensionType interface{} // nil pointer to the extension type
	Field         int32       // field number
	Name          string      // fully-qualified name of extension, for text formatting
	Tag           string      // protobuf tag style
	Filename      string      // name of the file in which the extension is defined
}
```

Then I can refer this func in https://github.com/gogo/protobuf/blob/a11c89fbb0ad4acfa8abc4a4d5f7e27c477169b1/vanity/field.go
```
func SetBoolFieldOption(extension *proto.ExtensionDesc, value bool) func(field *descriptor.FieldDescriptorProto) {
	return func(field *descriptor.FieldDescriptorProto) {
		if FieldHasBoolExtension(field, extension) {
			return
		}
		if field.Options == nil {
			field.Options = &descriptor.FieldOptions{}
		}
		if err := proto.SetExtension(field.Options, extension, &value); err != nil {
			panic(err)
		}
	}
}
```

but just return a `func` to change the `extension.Options` instead of the `field.Tag`? Am I correct?

**Comment by awalterschulze** [comment]
I think you want something like this

```
func SetBsonTagFieldOption(field *descriptor.FieldDescriptorProto) {
	return func(field *descriptor.FieldDescriptorProto) {
		if FieldHasStringExtension(field, gogoproto.E_Moretags) {
			return
		}
		if field.Options == nil {
			field.Options = &descriptor.FieldOptions{}
		}
                value := "bson: " + strconv.Quote(camelCaseOf(field.Name)+",omitempty")
		if err := proto.SetExtension(field.Options, gogoproto.E_Moretags, &value); err != nil {
			panic(err)
		}
	}
}
```

**Comment by hcliff** [comment]
For those coming across this, here's my implementation of Walters suggestion to write a custom vanity binary fn

```
func SetBsonTagFieldOption(field *descriptor.FieldDescriptorProto) {
	moreTagsExtension := gogoproto.GetMoreTags(field)

	var moreTags reflect.StructTag
	if moreTagsExtension != nil {
		moreTags = reflect.StructTag(*moreTagsExtension)
	}

	// The value we'll be assigning to moreTags
	// start with any existing tags
	value := string(moreTags)
	if _, ok := moreTags.Lookup("bson"); !ok {
		bsonTag := fmt.Sprintf("bson:%s,omitempty", strconv.Quote(*field.Name))
		if value != "" {
			value += " "
		}
		value += bsonTag
	}
	if err := proto.SetExtension(field.Options, gogoproto.E_Moretags, &value); err != nil {
		panic(err)
	}
}
```
this approach will let you use moretags for other purposes too
