### ISSUE TITLE
Vote For New Feature: Support BinaryMarshaler and TextMarshaler for custom types

### ISSUE THREAD

**Issue by awalterschulze** [gogo/protobuf#28]
_From [joa...@dynamic-design.se](https://code.google.com/u/116413275603785449127/) on September 29, 2014 21:40:54_

I have several times tried using custom types (mostly existing types from imported packages) with no luck. It always fails when I don't want to implement the proto.Marshaler interface, since I then have to wrap the type which bring (IMO) unnecessary complexity.

Since we can use a byte slice as a custom type, wouldn't it be perfectly logical to just use the existing go interface for marshalling to/from binary? ( http://golang.org/pkg/encoding/#BinaryMarshaler ) 

Also it should not be hard at all to implement, if you don't want this change maybe you could point me to the proper place for me to implement it locally?

_Original issue: http://code.google.com/p/gogoprotobuf/issues/detail?id=28_

**Comment by tv42** [comment]
Personally I've never used Equal or Populate, but encounter the need for custom marshaling every now and then. For me, personally, it's not the end of the world if types using MarshalBinary won't work with Equal or Populate.

**Comment by awalterschulze** [comment]
If customtype does not work with Equal and Populate is also does not work for any test generation.
I think this is a little scary, since your custom type is not tested anywhere else.

I think there are a couple of ideas about Equal, Marshaling and then checking, reflect.DeepEqual after finding that the type does not implement the equaler interface.

I hope testing/quick.Generator is used a lot in the standard library, since then this is a perfect replacement for Populate.

I just haven't had the time to check.

**Comment by awalterschulze** [comment]
Ok quick.Generator does not look very popular in the standard library :(

grep -R "Generate(rand" .                         ./crypto/tls/handshake_messages_test.go:func (*clientHelloMsg) Generate(rand *rand.Rand, size int) reflect.Value {
./crypto/tls/handshake_messages_test.go:func (*serverHelloMsg) Generate(rand *rand.Rand, size int) reflect.Value {
./crypto/tls/handshake_messages_test.go:func (*certificateMsg) Generate(rand *rand.Rand, size int) reflect.Value {
./crypto/tls/handshake_messages_test.go:func (*certificateRequestMsg) Generate(rand *rand.Rand, size int) reflect.Value {
./crypto/tls/handshake_messages_test.go:func (*certificateVerifyMsg) Generate(rand *rand.Rand, size int) reflect.Value {
./crypto/tls/handshake_messages_test.go:func (*certificateStatusMsg) Generate(rand *rand.Rand, size int) reflect.Value {
./crypto/tls/handshake_messages_test.go:func (*clientKeyExchangeMsg) Generate(rand *rand.Rand, size int) reflect.Value {
./crypto/tls/handshake_messages_test.go:func (*finishedMsg) Generate(rand *rand.Rand, size int) reflect.Value {
./crypto/tls/handshake_messages_test.go:func (*nextProtoMsg) Generate(rand *rand.Rand, size int) reflect.Value {
./crypto/tls/handshake_messages_test.go:func (*newSessionTicketMsg) Generate(rand *rand.Rand, size int) reflect.Value {
./crypto/tls/handshake_messages_test.go:func (*sessionState) Generate(rand *rand.Rand, size int) reflect.Value {
./testing/quick/quick.go:	Generate(rand *rand.Rand, size int) reflect.Value
./testing/quick/quick.go:		return m.Generate(rand, complexSize), true

**Comment by awalterschulze** [comment]
Ok I propose a new extension custombinary and customtext.
This is if someone is interested in implementing this.

**Comment by awalterschulze** [comment]
Sorry for the super long delay.

**Comment by awalterschulze** [comment]
This also assumes that NewPopulated will not be implemented and in the case that a random value needs to be generated an empty one will have to do.
Equal with call MarshalBinary or MarshalText and simply compare the result.

**Comment by awalterschulze** [comment]
If anyone still needs this, please drop a comment.

**Comment by awalterschulze** [comment]
no comments for more than a year, closing.
