### ISSUE TITLE
equal plugin generates wrong import line

### ISSUE THREAD

**Issue by andreimatei** [gogo/protobuf#283]
I've added the `option (gogoproto.equal) = true;` line to the following proto:
https://github.com/cockroachdb/cockroach/blob/befea82/pkg/roachpb/metadata.proto#L69

It seems to generate the following bogus import line:
```
import bytes "github.com/cockroachdb/bytes"
```

Not sure where it got the "cockroachdb/bytes" from; that package does not exist. The `bytes` types in the proto I've annotated are using `gogoproto.casttype`, which maybe is related.

**Comment by awalterschulze** [comment]
Ok that looks like a bug. Well done.
I'll look into it asap.

**Comment by awalterschulze** [comment]
I can't seem to reproduce.
I tried creating a message with a bytes field and a casttype.

Maybe it has something to do with your protoc command, like maybe using import_prefix?
Can you give me the protoc command or can you give me a smaller reproducing example?

**Comment by andreimatei** [comment]
If you clone our repo, you can do `make protobuf` to do the code generation.
The `protoc` command seems to be:
```
/Users/andrei/work2/src/github.com/cockroachdb/cockroach/bin/protoc -I.:./cockroach/vendor/github.com/../github.com/gogo/protobuf:./cockroach/vendor/github.com/../github.com/gogo/protobuf/protobuf --cpp_out=lite:./cockroach/pkg/storage/engine ./cockroach/pkg/roachpb/data.proto ./cockroach/pkg/roachpb/internal.proto ./cockroach/pkg/roachpb/metadata.proto ./cockroach/pkg/storage/engine/enginepb/mvcc.proto ./cockroach/pkg/storage/engine/enginepb/rocksdb.proto ./cockroach/pkg/util/hlc/timestamp.proto ./cockroach/pkg/util/unresolved_addr.proto
```

It's indeed possible that it's something about our environment, but I can't think what it could be. If you don't get to it, I'll try a simpler repro.

**Comment by awalterschulze** [comment]
It would really help to get a simpler example.

**Comment by andreimatei** [comment]
It turns out that we're forced to fixup standard package imports with hacks because of the `import_prefix` we pass to protoc plugins.
https://github.com/cockroachdb/cockroach/blob/bf224cf/build/protobuf.mk#L87

@tamird, whom I believe you know, tells me that this is a known... idiosyncrasy with protoc.

Sorry for the noise.

**Comment by tamird** [comment]
Sounds like https://github.com/golang/protobuf/issues/181.

**Comment by awalterschulze** [comment]
No worries, this is a really hard issue.
