### ISSUE TITLE
Implement a EqualIgnoreOrder function

### ISSUE THREAD

**Issue by swelly127** [gogo/protobuf#284]
During testing we may want to compare protos but we can't always predict the order the elements of the slice will be in. I have code that does this, if you guys add me as a contributor I can make a request

**Comment by awalterschulze** [comment]
You are always welcome to make a pull request and if it gets merged you can become an CONTRIBUTOR or an AUTHOR, whichever is appropriate in terms of copyright.

Its always useful though to first have a design discussion, but if the work is very little, like in this case, its really nice to be able to talk concretely about the code.
I will now go and look at the pull request.

**Comment by awalterschulze** [comment]
https://github.com/gogo/protobuf/pull/285

**Comment by awalterschulze** [comment]
I am closing this, but just comment if you would like it reopened.
