### ISSUE TITLE
Reference enum by string in grpc-gateway doesn't work

### ISSUE THREAD

**Issue by foolusion** [gogo/protobuf#286]
With the standard protoc_gen_go I can reference Enum's by their string name when using grpc-gateway. This is not the case when I use gogo binaries.

**Comment by awalterschulze** [comment]
Could you please explain what you mean with reference?

**Comment by awalterschulze** [comment]
You might want to use the goproto_registration extension which is not
documented for some reason

**Comment by johanbrandhorst** [comment]
I could've sworn there was documentation added when that extension was added. It must've disappeared at some point.

**Comment by johanbrandhorst** [comment]
It appears it was only added to `gogoproto/doc.go` and not `extensions.md`:

https://github.com/gogo/protobuf/blob/master/gogoproto/doc.go#L151

**Comment by awalterschulze** [comment]
Yes me too

**Comment by foolusion** [comment]
Thanks for pointing out the extension. That solved my issue!

**Comment by awalterschulze** [comment]
I added it to extensions now.  Thanks @johanbrandhorst

**Comment by awalterschulze** [comment]
Glad to hear that this solved your problem :)
