### ISSUE TITLE
proto3 generator does not used packed=True by default for repeated fields

### ISSUE THREAD

**Issue by allovertan** [gogo/protobuf#287]
According to https://developers.google.com/protocol-buffers/docs/encoding#optional, proto3 packs repeated fields by default.

This behaviour is not obeyed in the gogo generator, meaning it is inconsistent with the spec. We had a python generate some proto3s with packed-by-default repeated varints, which results in a wiretype error when unmarshalling from Golang.

**Comment by awalterschulze** [comment]
I remember that this was an issue are you sure this is still the case in
the current master?

**Comment by allovertan** [comment]
yeah turns out we were using an old version. thanks for following up!
