### ISSUE TITLE
Descriptor's EnumValueOptions.UninterpretedOption not properly populated

### ISSUE THREAD

**Issue by josh-tepper** [gogo/protobuf#288]
I believe that the Descriptor's EnumValueOptions is not being properly populated for custom options:

I have a proto enum with custom options declared  like this:
```
enum P {
  undef = 0;
  A = 1  [(my_option) = true];
  B = 2
  ...
  Other = 3  [(my_option) = true];
}

extend google.protobuf.EnumValueOptions {
  bool my_option = 80318;
}
```

I inspect the EnumValueDescriptorProto like this:
```
if enumValueOptions := enumValueDesc.GetOptions(); enumValueOptions != nil {
  uninterpOptions := enumValueOptions.GetUninterpretedOption()
  ...
}
```

Unfortunately, the `uninterpOptions` always has length 0 even for values where the custom option is declared!

Interestingly, the EnumValueOptions *has* my custom option, and it is stored as an extension:

```
extensionDescs, err := proto.ExtensionDescs(enumValueOptions)
if err != nil { panic("cannot retrieve extensions")  }
for _, extensionDesc := range extensionDescs {
	if extensionDesc != nil && extensionDesc.Name == "my_option" {
		my_option, err := proto.GetExtension(enumValueOptions, extensionDesc)
		if err != nil { panic("Unable to get extensions for proto enumValueOptions") }

		if val, ok := my_option.(*bool); ok && val != nil {
			fmt.Println("found one and the value is %t\n", *val)
		}
	}
}
```
Executing this code will find the option, if set, and will show its correct value.

Thank you in advance!

**Comment by awalterschulze** [comment]
This might be useful
https://github.com/gogo/protobuf/blob/master/protobuf/google/protobuf/descriptor.proto#L261-L267

**Comment by awalterschulze** [comment]
Could you experiment by not declaring?
```
extend google.protobuf.EnumValueOptions {
  bool my_option = 80318;
}
```
This should result in a parsing error from protoc.  Or at least it did way back.
Would be interesting to know if this has changed.

If it does not throw a parsing error, then you might find your option in Uninterpreted options.

**Comment by josh-tepper** [comment]
This in fact give a parsing error:
`my/path/my_proto.proto:15:13: Option "(my_option)" unknown.`

@awalterschulze - Referencing the comment that you linked, is it perhaps the case that accessing the extensions is the correct way to access these fields?  It sounds like maybe `uninterpreted_option` is just an implementation detail, and used so that extensions can be populated at descriptor-creation time if that wasn't already done at proto-parse time (ie if they were not yet known).  Perhaps, then, since these are known at proto-parse time, that it is ok for the implementation to choose to just populate the extensions directly, without uninterpreted_option.

Nonetheless, this is all just my speculation.  I never know because the golang proto api docs are pretty sparse.

FYI, we're building with this:
```
python -m grpc.tools.protoc \
            -I ...
            --proto_path=... \
            --gogofast_out=plugins=grpc,protoc-gen-grpc="$( which protoc-gen-gogofast )",...
```

**Comment by josh-tepper** [comment]
Also, the example in the language spec (in C++) involves accessing the extensions:
https://developers.google.com/protocol-buffers/docs/proto#customoptions

Reproducing the example here:
```
string value = MyMessage::descriptor()->options().GetExtension(my_option);
```

**Comment by awalterschulze** [comment]
Ok so basically uninterrupted options is just for internal use and the
right way to access the extension is the way you have already done. This is
the way I use in gogoprotobuf as well. Is this a problem?

**Comment by josh-tepper** [comment]
No -- according to my new understanding, no there is no issue

**Comment by awalterschulze** [comment]
Good to know ☺️

**Comment by josh-tepper** [comment]
closing the issue.  Again, not saying anything definitively that it's ok to not populate UninterpretedOption or that accessing the extensions is the correct way to do it--this is just my current understanding
