### ISSUE TITLE
Document generating non Go-language bindings (Java, Python, etc.)

### ISSUE THREAD

**Issue by jslz** [gogo/protobuf#289]
I am confused about how to generate .java files for use in an Android client. For pseudo-example, if the .proto files use the gogoproto.moretags extension then I am seeing com.google.protobuf.GoGoProtos.getDescriptor() in the generated .java files. I think I'm using the bazel protobuf_repo protoc as the generator. (Oddly enough the [Apple Swift protobuf compiler](https://github.com/apple/swift-protobuf) manages to elide gogo-specific things.)

Fwiw, I see other people being confused about it on the Internet too but none of the replies have helped me grok it [1][2][3]. Might anybody have some helpful instructions (or docs that could be added to the README.md) to explain what needs to be done to end up with .java files that either

 * tell me I have to just strip all gogo extensions out when targeting other languages?
or
 * have the right jar or whatever to make them build?
or
 * exclude things like com.google.protobuf.GoGoProtos.getDescriptor()

thank you!

[1] https://github.com/cockroachdb/cockroach/issues/393
[2] https://github.com/docker/swarmkit/issues/647
[3] https://groups.google.com/forum/#!topic/gogoprotobuf/n20iywk5vus

**Comment by awalterschulze** [comment]
As far as I know the only thing that is hard, as always, is setting up the
proto path. It needs to include gogo.proto and the descriptor.proto

And finally you need to call java_out with protoc.

I had to figure it out once myself, but I felt the paths were very project
specific. I guess that and the fact that I am a java noob, resulted in me
not documenting it.

When you figure it out and want to contribute some docs that would be
really helpful.

**Comment by jslz** [comment]
Thank you for your thoughts on this. More debugging info/questions...

- I do think I am successfully building everything in terms of finding the gogo.proto and the descriptor.proto (e.g. if I remove the -I statements I can make the build break so it looks like we are getting them included ok).

- I am calling the Bazel version of protoc, if that matters.

- The Java output includes things like "registry.add(com.google.protobuf.GoGoProtos.moretags);" but without a .jar file that includes com.google.protobuf.GoGoProtos, there's nothing to link against, which breaks the Java build.

That's why thus far I am guessing my two choices are:

1. Find a gogoproto.jar file to include in our Java Android build.
2. Find a way to remove the gogo extensions from our original .proto files before we generate the .java files from them.

**Comment by awalterschulze** [comment]
Ah ok bazel makes it harder and I won't be able to help you with that, but
I think what will help is if you run protoc on gogo.proto to create a jar
that you can include.

**Comment by jslz** [comment]
thanks!
