### ISSUE TITLE
Slice/repeated fields: Struct Slices grow unbounded when repeatedly unmarshalled

### ISSUE THREAD

**Issue by nemosupremo** [gogo/protobuf#294]
I81 I was recently surprised by the Unmarshal functionality when it came to repeated fields. I have a proto schema like this:

```proto
syntax = "proto2";
package pb;

import "github.com/golang/protobuf/ptypes/timestamp/timestamp.proto";
import "github.com/gogo/protobuf/gogoproto/gogo.proto";

message Post {
	required string id = 1 [(gogoproto.nullable) = false, (gogoproto.moretags) = "column:\"id\""];
	repeated string labels = 8 [(gogoproto.moretags) = "column:\"labels\""];
	required google.protobuf.Timestamp created = 9 [(gogoproto.nullable) = false, (gogoproto.moretags) = "column:\"created\"", (gogoproto.stdtime) = true];
}
```

And in my code I'm doing something like this:

```go
schema := &Post{}
for buff := range stream {
	if err := schema.Unmarshal(buff); err != nil {
		return nil, err
	}
        fmt.Printf("%v\n", schema)
	// process
}
```

**Input:**
```
{"id":"0", "labels":["a"], created:"..."}
{"id":"1", "labels":["b"], created:"..."}
{"id":"2", "labels":["c"], created:"..."}
{"id":"3", "labels":["d"], created:"..."}
{"id":"4", "labels":["e"], created:"..."}
```

**Output:**

```
{"id":"0", "labels":["a"], created:"..."}
{"id":"1", "labels":["a", "b"], created:"..."}
{"id":"2", "labels":["a", "b" "c"], created:"..."}
{"id":"3", "labels":["a", "b", "c", "d"], created:"..."}
{"id":"4", "labels":["a", "b", "c", "d", "e"], created:"..."}
```

Now I would expect in `process` that `schema.Labels` would be an array of that protobuf's items. However, what I'm finding is that each new `Unmarshal` results in `schema.Labels` string slice containing *all the values seen thus far*. 

Normally I would expect that in `Unmarshal` the underlying slice is cleared, or if its being reused, that it's length is being set to 0.  This seems like a bug to me as no other `Unmarshal` interface I've used behaves this way. Looking in the code, it looks like `append` is used. Is this a bug? Or is it documented somewhere that you should be resetting your slices before you pass them to `Unmarshal`?

This "issue" is fixed with something like:

```go
if schema.Labels != nil {
	schema.Labels = schema.Labels[:0]
}
// call Unmarshal
```

**Comment by awalterschulze** [comment]
protobufs require that you are able to do merge messages, but simply concatenating them, this includes appending to lists, like you have described above.

Calling proto.Unmarshal(schema, buff) calls Reset for you and then calls schema.Unmarshal(buff) for you as well, so this should solve your problem.
