### ISSUE TITLE
UnmarshallJSON is not generated when switching to proto3

### ISSUE THREAD

**Issue by jrmarkle** [gogo/protobuf#295]
When using `proto2` syntax, if I used a message with an `enum` field, I could use the generated code to unmarshall JSON data if the enum definition matched the JSON string field values. This is because gogo-proto generated an `UnmarshalJSON` function for each `enum` type.

When I tried switching to `proto3` syntax, the `UnmarshalJSON` is no longer generated so JSON parsing fails. If I write `UnmarshalJSON` myself it works, but obviously I'd rather have this code generated. Is there an option I need to set in the `.proto` file to get this code generated again?

**Comment by awalterschulze** [comment]
This is something that comes from golang/protobuf in generator.go

```go
	if !es.proto3 {
		g.P("func (x ", s, ") Enum() *", s, "{ return (*", s, ")((", pkg, ".", s, ")(x).Enum()) }")
		g.P("func (x *", s, ") UnmarshalJSON(data []byte) error { return (*", pkg, ".", s, ")(x).UnmarshalJSON(data) }")
	}
```

They advise that you should use the jsonpb package for json marshaling and unmarshaling.
I hope that this is "fixed" in future https://github.com/golang/protobuf/issues/256

**Comment by awalterschulze** [comment]
I am closing this, but just comment if you would like it reopened.
