### ISSUE TITLE
Option to expose proto enum constants with proper Go style

### ISSUE THREAD

**Issue by awalterschulze** [gogo/protobuf#30]
_From [andyb...@chromium.org](https://code.google.com/u/103672041355317695829/) on November 10, 2014 20:28:08_

Currently proto CONSTANTS_LIKE_THIS are being exposed as such within Go code instead of translating to camelCase like message names. This is causing golint to freak out.

An option (or change to the generated files) to generate golint-friendly code would be great.

_Original issue: http://code.google.com/p/gogoprotobuf/issues/detail?id=30_

**Comment by awalterschulze** [comment]
golint has a lot of suggestions for gogoprotobuf.
I don't know if it is really worth it to pursue golint ability.
Or why with all these other errors would you only want this one golint change?

gogoprotobuf already go vets, which I think is much more worth while.

Here follows a very small summary or the errors I saw:

receiver name should be a reflection of its identity; don't use generic names such as "me", "this", or "self"

exported method ... should have comment or be unexported

type Uuid should be UUID

func NewPopulatedUuid should be NewPopulatedUUID

package comment should not have leading space

don't use underscores in Go names; struct field XXX_unrecognized should be XXXUnrecognized

don't use underscores in Go names; const TheTestEnum_A should be TheTestEnumA

struct field Id should be ID

func GetId should be GetID

exported function NewAFromFace should have comment or be unexported

func name will be used as group.GroupDescription by other packages, and that stutters; consider calling this Description

type name will be used as moredefaults.MoreDefaultsB by other packages, and that stutters; consider calling this B

type MyJson should be MyJSON

func NewPopulatedMyJson should be NewPopulatedMyJSON

package comment should be of the form "Package enumstringer ..."

exported func NewEnumStringer returns unexported type *enumstringer.enumstringer, which can be annoying to use

**Comment by andybons** [comment]
Generated files don't need to pass golint. I agree with you that it's not worth it. Not really sure what I was thinking :)

**Comment by awalterschulze** [comment]
I initially also thought this was a great idea.
Unfortunately its just too much work for too little reward.
