### ISSUE TITLE
run   go get .../. 

### ISSUE THREAD

**Issue by yang-f** [gogo/protobuf#301]
go build github.com/gogo/protobuf/test/sizerconflict: no buildable Go source files in /work/myproject/src/github.com/gogo/protobuf/test/sizerconflict

**Comment by awalterschulze** [comment]
Why do you want to go get the test folder?

**Comment by yang-f** [comment]
Thanks for your reply.
I don't want to ，but it was automatically got the test folder(running go get .../.). 
What should I do?Just run go get -d .../.  ? I think it is unreliable,help me...

**Comment by awalterschulze** [comment]
I would recommend doing what it says in the readme
```
go get github.com/gogo/protobuf/proto
go get github.com/gogo/protobuf/{binary}
go get github.com/gogo/protobuf/gogoproto
```
where binary is your binary of choice, probably protoc-gen-gogo or protoc-gen-gofast.

But I have also added a doc.go file to the sizerconflict folder which might help your go get ./... to work.  Please let me know if there is a follow up issue.

**Comment by yang-f** [comment]
Thank you very much for your advice.May be  protoc-gen-gogo.It's work now.thanks.

**Comment by awalterschulze** [comment]
Cool no problem and good luck with your usecase :)
