### ISSUE TITLE
gogo jsonpb tries to serialize non proto field

### ISSUE THREAD

**Issue by rogeralsing** [gogo/protobuf#305]
We have a proto generated struct which also contains a non proto field for caching purposes, like so

```go
type PID struct {
	Address string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`

	p *Process //<-- this field
}
```

This works nice when serializing as a normal proto message.
But, when suing jsonpb, there is an error thrown that there is no encoder for `Process`.
Why is gogo jsonpb trying to serialize a field that is not part of the proto contract, has no proto tags and clearly is not a proto type?

**Comment by awalterschulze** [comment]
Basically this usecase has not been fully explored.
I am guessing you are using `gogoproto.typedecl=false`

I am very open for a pull request with a test and a fix for this.

**Comment by rogeralsing** [comment]
Thanks, I will look into this and see if we can solve it.

**Comment by awalterschulze** [comment]
Thank you very much :)

**Comment by rogeralsing** [comment]
For anyone else facing the same issue.
You can work around this by implementing the `proto.JSONPBMarshaler` interface on your special type.
And simply emit the correct JSON yourself, omitting the non mapped field.

**Comment by rogeralsing** [comment]
There is another workaround:
https://github.com/gogo/protobuf/blob/master/jsonpb/jsonpb.go#L203

You can prefix your fields names with `XXX_` this will also resolve the issue.

But I do think it should also ignore any field lacking a `protobuf` tag, no?

**Comment by awalterschulze** [comment]
I agree :)

I think thats the way that jsonpb should ignore fields.
