### ISSUE TITLE
Support for Well Known Struct in marshaler/unmarshaler extensions?

### ISSUE THREAD

**Issue by bir** [gogo/protobuf#306]
I am attempting to use the Well Known Type [Struct](https://github.com/golang/protobuf/tree/master/ptypes/struct) for marshaling dynamic data.  However, when I compile this simple example below the generated code attempts calls to MarshalTo and Size that do not exist in the implementation linked above.  Is there a standard way to correct this?  I have scoured the code and issues and apologize if I missed something obvious, still learning the golang world.

Example.proto
```protobuf
syntax = "proto3";
option go_package = "test";

import "google/protobuf/struct.proto";
import "github.com/gogo/protobuf/gogoproto/gogo.proto";

option (gogoproto.marshaler_all) = true;
option (gogoproto.unmarshaler_all) = true;
option (gogoproto.sizer_all) = true;

message Example {
    google.protobuf.Struct testCustom = 12;
}
```

**Comment by awalterschulze** [comment]
Please see https://github.com/gogo/protobuf/blob/master/test/types/Makefile
This should help you to link to gogo/protobuf/types.Struct which has the MarshalTo and Size methods.

**Comment by bir** [comment]
An amazingly fast response!  Worked perfectly.  Many thanks!

**Comment by awalterschulze** [comment]
My pleasure ☺️
