### ISSUE TITLE
Question about json tag omitempty

### ISSUE THREAD

**Issue by yushengery** [gogo/protobuf#310]
Greetings, 
We are using gogoprotobuf in our production environment,  However I have some question about the generated go files in the JSON tag omitempty
We need to send the  marshaled  JSON string to other endpoint (PHP/Javascript eg.)  in some circumstance , where the JSON string was generated from protobuf messages. However, the field will be gone if it is "Zero" value due to the "omitempty"  property. This will make it difficult to handle in the other language.
My question is why the generator adds the omitempty . How about I remove it away? 

Best Regards.

**Comment by awalterschulze** [comment]
This is the way golang/protobuf has setup the json tags to start with.

You can use the jsontag extension to edit the tags.
https://github.com/gogo/protobuf/blob/master/extensions.md#more-serialization-formats

You will also need to think about whether you are calling jsonpb or encoding/json, since that also makes a difference.

**Comment by yushengery** [comment]
We are call encoding/json package to marshal the proto message

**Comment by awalterschulze** [comment]
Yes so then the jsontag extension should work.

You could also create your own vanity binary that modifies all your fields and adds the jsontag without the ,omitempty to each field automatically.

I hope this answered your question?

**Comment by awalterschulze** [comment]
Also who is we and can I add you to the gogoprotobuf user list?

**Comment by yushengery** [comment]
Hi awalterschulze, We are Aladinfun, a startup game company

**Comment by awalterschulze** [comment]
Do you have a website or github link you'd like to ad?

Did I answer your question?

**Comment by yushengery** [comment]
@awalterschulze , sorry for my late response ,  We do not have a website or github link yet
The question confused me most is why there is a "omitempty" in the json tag, which will make it compatible  
when passing the json marshaled result which includes some fields with "zero value" in the GO between other languages .
Thanks a lot .

**Comment by awalterschulze** [comment]
Did I answer your question, if not can you repeat it?

**Comment by awalterschulze** [comment]
I am closing this, but just comment if you would like it reopened.
