### ISSUE TITLE
GoString is generating unparseable golang

### ISSUE THREAD

**Issue by jdef** [gogo/protobuf#312]
The generated test case panics when trying to parse the result of `GoString`. Not sure how to resolve this other than by disabling the `GoString` generator.

Details here: https://github.com/mesos/mesos-go/pull/312#issuecomment-317754305

**Comment by awalterschulze** [comment]
Without properly investigating, I suspect mesos.Label does not implement GoString?
Or the Value field of mesos.Label does not implement GoString?

**Comment by jdef** [comment]
Agree, Labels looks funny. Here's how the protos are declared:
```
message Labels {
  repeated Label labels = 1 [(gogoproto.nullable) = false];
}
message Label {
  required string key = 1 [(gogoproto.nullable) = false];
  optional string value = 2;
}
```
https://github.com/mesos/mesos-go/blob/464c8d6a7d891b5f7695e6a6e78c6e3974223db4/api/v1/lib/mesos.proto#L2518

I disabled gostringer to get unit tests passing. I'll temporarily add it back and see if mesos.Label implements GoString after regenerating

**Comment by jdef** [comment]
generated code:
```
func (this *Labels) GoString() string {
        if this == nil {
                return "nil"
        }
        s := make([]string, 0, 5)
        s = append(s, "&mesos.Labels{")
        if this.Labels != nil {
                s = append(s, "Labels: "+fmt.Sprintf("%#v", this.Labels)+",\n")
        }
        s = append(s, "}")
        return strings.Join(s, "")
}
func (this *Label) GoString() string {
        if this == nil {
                return "nil"
        }
        s := make([]string, 0, 6)
        s = append(s, "&mesos.Label{")
        s = append(s, "Key: "+fmt.Sprintf("%#v", this.Key)+",\n")
        if this.Value != nil {
                s = append(s, "Value: "+valueToGoStringMesos(this.Value, "string")+",\n")
        }
        s = append(s, "}")
        return strings.Join(s, "")
}
```

**Comment by jdef** [comment]
```
func valueToGoStringMesos(v interface{}, typ string) string {
        rv := reflect.ValueOf(v)
        if rv.IsNil() {
                return "nil"
        }
        pv := reflect.Indirect(rv).Interface()
        return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
```

**Comment by jdef** [comment]
Is this because `Labels.labels` is a slice of non-pointers? For example: https://play.golang.org/p/xhswqJm3NZ

**Comment by awalterschulze** [comment]
Weird, but I see what you mean.

I wonder why it then works for:
https://github.com/gogo/protobuf/blob/master/test/thetest.proto#L191-L202

But I will need more time to look at this.
This week is crazy, sorry.
But I'll get to this.

**Comment by awalterschulze** [comment]
I am struggling to reproduce the issue
https://github.com/gogo/protobuf/tree/issue312
https://github.com/gogo/protobuf/commit/c8d250eee7392e86ded72c1363ea4212e478b1c9
Could you help me in reproducing a minimal example that we can add as a test to gogoprotobuf?

**Comment by jdef** [comment]
https://github.com/gogo/protobuf/pull/315

**Comment by awalterschulze** [comment]
Thanks for reproducing :)

**Comment by awalterschulze** [comment]
I this merged the fix.

Actually I think this might be a different issue that you found.  Please check if this fixes your issue before closing this one.

**Comment by jdef** [comment]
Thanks, your change fixes the unit test errors I was seeing. I'd like to see a fix for labels output, but maybe that's a bug that should be fixed in golang? I filed a bug report, will see what they have to say.

https://github.com/golang/go/issues/21230

**Comment by awalterschulze** [comment]
You are a brave soul logging a go issue, but it seems they are not biting.
I'll look into this as soon as I get some time again.

**Comment by awalterschulze** [comment]
I really like your comment on that golang issue.

I have also pushed a second fix to master.  This should solve your repeated non nullable type problem, but I don't like the solution.  Please check and then I can close this issue for now.

I'll be working on a more elegant solution here
https://github.com/awalterschulze/goderive/issues/5
during the next couple of weeks, using my new code generation tool.

**Comment by awalterschulze** [comment]
An elegant solution is now available in goderive and it seems from my comment that I have also pushed a fix to the gostring plugin.
So I am closing this.
Just comment if you would like it reopened.
