### ISSUE TITLE
json unmarshalling doesn't handle "null" into pointer types correctly

### ISSUE THREAD

**Issue by tamird** [gogo/protobuf#319]
Fixed upstream in https://github.com/golang/protobuf/pull/394.

**Comment by awalterschulze** [comment]
Sorry for the delay.  I'll get to this asap.

**Comment by tamird** [comment]
I'm actually doing it right now; I'll send a PR shortly.

**Comment by awalterschulze** [comment]
I want to merge all the diffs in between first, if there are any.

**Comment by tamird** [comment]
Yep, I'm doing that.

**Comment by awalterschulze** [comment]
I would prefer to do that myself, just because I think it will be harder to review than doing it. 
Maybe I am wrong.

**Comment by tamird** [comment]
Go for it.

**Comment by awalterschulze** [comment]
Ok starting now.

**Comment by awalterschulze** [comment]
I really do appreciate the gesture though.  It is quite a tedious process.  I did leave it a bit too long.

**Comment by awalterschulze** [comment]
done
