### ISSUE TITLE
Can she generate.Proto files?

### ISSUE THREAD

**Issue by CBDlkl** [gogo/protobuf#320]
I want to generate the.Proto file through struct to create the automated API Doc.

Can the project be done?

Thank you very much！

**Comment by awalterschulze** [comment]
Maybe you want to give an example?

**Comment by CBDlkl** [comment]
Sorry, this is my negligence.

for example:

I need to publish some API interfaces, based on SOAP.

One of the interface names is: `GetUserInfo`,There are input (GetUserInfoInput) and output parameters (GetUserInfoOutput),
I want to define the Struct of `GetUserInfoInput` and `GetUserInfoOutput` directly in Golang, and the program will automatically retrieve the Struct structure by reflection, and then generate the proto file. 
So I can publish the proto files directly to the users.

I used C # to implement this feature，Generate such a document：
![1](https://user-images.githubusercontent.com/9330061/29162181-3f6657d8-7deb-11e7-8b00-a45c366fca14.png)

Now I want to implement it through golang,So I asked if this project could help me.

My English is not very good, the description may not be very accurate,Thank you!

**Comment by awalterschulze** [comment]
I think you are looking for https://github.com/src-d/proteus
Does that help?

**Comment by CBDlkl** [comment]
yes！thank you ！
It's good luck to get your help

**Comment by awalterschulze** [comment]
My pleasure ☺️
