### ISSUE TITLE
oneof code generation is incorrect (un-compilable) for fields with default value.

### ISSUE THREAD

**Issue by pattyshack** [gogo/protobuf#322]
The generated code for oneof does not compile when a scalar (int/enum/etc) field has a default value (It works as intended when the default is not specified).  e.g.,
```
syntax = "proto2";
package test;

message OneofTest {
    oneof union {
        int32 i = 1 [default = 4];
    }
}
```
produces
```
type OneofTest_I struct {
    I int32 `protobuf:"varint,1,opt,name=i,oneof,def=4"`
}

...

func (m *OneofTest_I) MarshalTo(dAtA []byte) (int, error) {
    i := 0
    if m.I != nil {
        dAtA[i] = 0x8
        i++
        i = encodeVarintOneof(dAtA, i, uint64(*m.I))
    }
    return i, nil
}
```
This code is incorrect because it performs a nil check on a non-pointer field.

Look like the difference in behavior between field with / without default value is due to the usage of `vanity.TurnOffNullableForNativeTypesWithoutDefaultsOnly` (I don't have enough context to confidently fix this issue myself).

**Comment by awalterschulze** [comment]
Which gogo_out are you using?

**Comment by pattyshack** [comment]
I'm using a custom binary.  The vanity options are
```
    vanity.ForEachFile(files, vanity.TurnOnMarshalerAll)
    vanity.ForEachFile(files, TurnOnProtoSizerAll)
    vanity.ForEachFile(files, vanity.TurnOnUnmarshalerAll)
```

**Comment by awalterschulze** [comment]
Well and `TurnOffNullableForNativeTypesWithoutDefaultsOnly`?

```go
func TurnOffNullableForNativeTypesWithoutDefaultsOnly(field *descriptor.FieldDescriptorProto) {
	if field.IsRepeated() || field.IsMessage() {
		return
	}
	if field.DefaultValue != nil {
		return
	}
	SetBoolFieldOption(gogoproto.E_Nullable, false)(field)
}
```

**Comment by awalterschulze** [comment]
Oh I forgot.  It is used by the code generator plugins to help with the generation of `oneof`

**Comment by awalterschulze** [comment]
This should fix it
https://github.com/gogo/protobuf/commit/fcdc5011193ff531a548e9b0301828d5a5b97fd8
Please reopen if you are still experiencing this issue.

**Comment by pattyshack** [comment]
thx!
