### ISSUE TITLE
Why there is no context parameter for a only response stream API

### ISSUE THREAD

**Issue by lnshi** [gogo/protobuf#323]
Like my protobuf API:
```
rpc LsyncV1(microservice.lsync.v1.LsyncReq) returns (stream microservice.lsync.v1.LsyncRes) {}
```

Then the generated Go code will look like this:
```
LsyncV1(*microservice_lsync_v1.LsyncReq, Lsync_LsyncV1Server) error

type Lsync_LsyncV1Server interface {
	Send(*microservice_lsync_v1.LsyncRes) error
	grpc.ServerStream
}
```

There is no `context.Context` as 1st parameter like the other unary call, like: `HealthCheck(context.Context, *microservice.Empty) (*microservice2.HealthCheckRes, error)`

But through [here](https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md#sending-and-receiving-metadata---server-side), it seems above API should be counted as an unary call, and then I can get the values in the context like it described.

But yes, i tried to assume it as a stream call and then successfully get the values from the context like this in the server side:
```
md, _ := metadata.FromIncomingContext(stream.Context())
	fmt.Println("md: ", md)
```
but it is just a bit weird, how folks suppose to get the context values from the response stream which the values are actually passed from the GRPC client...

**Comment by lnshi** [comment]
then i traced that it is defined by the [StreamHandler](https://godoc.org/google.golang.org/grpc#StreamHandler), then searched the [unary rpc](https://grpc.io/docs/guides/concepts.html#unary-rpc) definitions,

it looks reasonable, but the way that getting the client passed context values from the response stream is still a bit wried...

**Comment by awalterschulze** [comment]
I think this is a discussion for upstream golang/protobuf.
For grpc gogoprotobuf is simply a fork of github.com/golang/protobuf.
Sorry.

**Comment by lnshi** [comment]
@awalterschulze  ok, thanks, can we keep this open for a while? see whether there will be someone coming to post the cause and effect.

**Comment by awalterschulze** [comment]
ok, but I would go to golang/protobuf with this, if you want a proper response.
