### ISSUE TITLE
Manual byte-by-byte copy instead of binary.LittleEndian func

### ISSUE THREAD

**Issue by diamondo25** [gogo/protobuf#333]
I was wondering why sfixed32 and sfixed64 are not using the binary.LittleEndian; the ASM output is optimized a lot.

**Comment by awalterschulze** [comment]
I can't remember, you are welcome to edit the marshal plugin and try to run
the tests. If they pass you are welcome to make a pull request. I will be
really interested in a Benchmark as well.

I would have tested this idea out myself, but I am at a conference.

**Comment by awalterschulze** [comment]
It seems that binary.LittleEndian does an early bounds check and that is what optimizes the asm output
https://golang.org/src/encoding/binary/binary.go?s=1176:1371#L82
Is that what you were talking about?
The rest of the code looks the same and the tests work when I replace the implementation.

But I think it this is the case then we can use the same trick in more places.

I can figure it out, but its easier if you tell me, how did you discover the optimized asm output?
Because then I can try to find more places that can be optimized.

**Comment by diamondo25** [comment]
You can run 'go compile -S file.go' to get the output for the current arch. Basically, on AMD64 it showed literally every step (load byte, set byte, increase offset) and at the end the bounds check. binary.LittleEndian generates the corresponding mov instruction to copy the block. (Movq with 64-bit elements).

I have been working on getting the bencmark and other tools working. Due to some missing info (t.go) and other outdated stuff, it doesnt work. I also found an error in the generator of gogo that causes lots of files to be indented by default, generating huge files. I think i can make a PR with the fixes for these things, at least.

Op 9 sep. 2017 10:39 a.m. schreef Walter Schulze <notifications@github.com>:

It seems that binary.LittleEndian does an early bounds check and that is what optimizes the asm output
https://golang.org/src/encoding/binary/binary.go?s=1176:1371#L82
Is that what you were talking about?
The rest of the code looks the same and the tests work when I replace the implementation.

But I think it this is the case then we can use the same trick in more places.

I can figure it out, but its easier if you tell me, how did you discover the optimized asm output?
Because then I can try to find more places that can be optimized.

**Comment by awalterschulze** [comment]
Ok I am going to assume you are working on this :)  It is much appreciated.

It would be nice if we can also compare the binary.LittleEndian with the unsafe version:
```go
*(*int64)(unsafe.Pointer(&dAtA[i])) = v
```

**Comment by diamondo25** [comment]
I already notice that some test was checking for bigendianness, which would make it fail. Not really a good experience, to be honest.

Op 9 sep. 2017 1:55 p.m. schreef Walter Schulze <notifications@github.com>:

Ok I am going to assume you are working on this :) It is much appreciated.

It would be nice if we can also compare the binary.LittleEndian with the unsafe version:

*(*int64)(unsafe.Pointer(&dAtA[i])) = v

**Comment by awalterschulze** [comment]
Yes I agree.  I would really like to remove the use of unsafe.

**Comment by awalterschulze** [comment]
Please let me know if you don't have the time to do this.
I would prefer to get another contributor and I actually very busy, but if you don't have time, I think this change is important enough that I will spend time on it.

**Comment by awalterschulze** [comment]
hello @diamondo25 ?

**Comment by diamondo25** [comment]
I am sorry. I have no time to work on this. There is a lot of code that is running on precompiled code, so its hard to exclude it. I will create a branch with all the code i have today.

Op 3 okt. 2017 1:07 p.m. schreef Walter Schulze <notifications@github.com>:

hello @diamondo25<https://github.com/diamondo25> ?

**Comment by awalterschulze** [comment]
No problem, just checking.  Then I'll take over :)

**Comment by diamondo25** [comment]
https://github.com/gogo/protobuf/pull/339

**Comment by awalterschulze** [comment]
I started with an intial comparison
https://github.com/awalterschulze/gorangecheck

The range check hint seems to require a constant.
Unsafe is still a little faster than the range checking hint, but by very little.
I think it might be time to remove unsafe and start using math and constant range check hints where we can :)

**Comment by awalterschulze** [comment]
I think its done
https://github.com/gogo/protobuf/pull/343

**Comment by awalterschulze** [comment]
done
