### ISSUE TITLE
does Unmarshal() intentionally not Reset()?

### ISSUE THREAD

**Issue by tschottdorf** [gogo/protobuf#334]
[We just ran into a bug](https://github.com/cockroachdb/cockroach/pull/18406/files) caused by the fact that (unlike `proto.Unmarshal`), the gogoproto-generated `Unmarshal()` does not implicitly `.Reset()`.

Perhaps this is intentional, but it ran counter to our intuition. If it is not intentional, it should be fixed; otherwise, it should be clearly documented on the generated `Unmarshal()` method (perhaps as a part of https://github.com/gogo/protobuf/issues/198).

**Comment by awalterschulze** [comment]
If we look at this logic
https://github.com/gogo/protobuf/blob/master/proto/decode.go#L396-L413
It seems that the proto.Unmarshal function assumes that the generated Unmarshal method, does not call the Reset method.  Otherwise this would be done twice.
That is why I decided not to call Reset in the Unmarshal method.

A pull request to add generated comments to generated methods is more than welcome.

**Comment by petermattis** [comment]
The comment on the `proto.Unmarshaler` interface is:

```
// Unmarshaler is the interface representing objects that can
// unmarshal themselves.  The method should reset the receiver before
// decoding starts.  The argument points to data that may be
// overwritten, so implementations should not keep references to the
// buffer.
```

Calling the `Reset` method twice if the user uses `proto.Unmarshal` is unfortunate, but I think that is less problematic than not calling `Reset` in the generated `Unmarshal`. The latter is a lurking bug. The former is a mild performance hit which can be worked around be calling the generated `Unmarshal` directly.

**Comment by awalterschulze** [comment]
This sounds like a bug in the comment or the implementation of golang/protobuf to me.
I'll make an issue.

**Comment by awalterschulze** [comment]
https://github.com/golang/protobuf/issues/424

**Comment by awalterschulze** [comment]
This code has been merged in gogoprotobuf from golang/protobuf
