### ISSUE TITLE
gogo and gogofast generate the same output?

### ISSUE THREAD

**Issue by pzduniak** [gogo/protobuf#337]
I'm not sure if I'm going insane or wtf is happening. Using last commit of gogoproto (f7f1376d9d231a646d4e62fe1075623ced6db327), installing using the following script:

```
go get -u github.com/gogo/protobuf/{proto,jsonpb,protoc-gen-gogofast,gogoproto}
go get -u golang.org/x/tools/cmd/goimports
pushd "${GOGOPROTO_ROOT}"
	git reset --hard "${GOGOPROTO_SHA}"
	make install
popd
```

Then building using the following command:

```
protoc --gogo_out=plugins=grpc,import_prefix=customgitlab/organization/proto/:. \
	-I=.:"${GOGOPROTO_PATH}":"${PROTO_ROOT}" *.proto
```

If I replace `gogo` with `gogofast`, it doesn't change. What I need is `gogoproto.nullable = true` to work, I don't need it anywhere but in one single place. I'm not sure what to do, am I doing something wrong? I am 100% sure that the gogo in path is this one.

**Comment by pzduniak** [comment]
command:
```bash
cd $GOPATH/src/customgitlab/organization/proto/organization/type/service && \
protoc --gogo_out=plugins=grpc,import_prefix=customgitlab/organization/proto/:. \
-I=.:"../../../.gopath/src/github.com/gogo/protobuf":\
"../../../.gopath/src/customgitlab/gogo/protobuf/protobuf":"../../../" \
*.proto
```


proto
```proto
syntax = "proto3";
package organization.type.service;
option go_package = "service";

import "gogoproto/gogo.proto";
option (gogoproto.marshaler_all) = true;
option (gogoproto.sizer_all) = true;
option (gogoproto.unmarshaler_all) = true;
option (gogoproto.goproto_getters_all) = false;
option (gogoproto.goproto_enum_prefix_all) = false;

message MethodMessage {
	bool is_ca = 1 [(gogoproto.customname) = "IsCA", (gogoproto.nullable) = true];
	string signer = 2;
	string dns_name = 3 [(gogoproto.customname) = "DNSName"];
}
```

Generates the following:

```go
type ListCertificatesRequest struct {
	IsCA    bool   `protobuf:"varint,1,opt,name=is_ca,json=isCa,proto3" json:"is_ca,omitempty"`
	Signer  string `protobuf:"bytes,2,opt,name=signer,proto3" json:"signer,omitempty"`
	DNSName string `protobuf:"bytes,3,opt,name=dns_name,json=dnsName,proto3" json:"dns_name,omitempty"`
}
```

Am I going insane?

**Comment by awalterschulze** [comment]
So you want to gerenate:

```go
type ListCertificatesRequest struct {
	IsCA   *bool   `protobuf:"varint,1,opt,name=is_ca,json=isCa,proto3" json:"is_ca,omitempty"`
	Signer  string `protobuf:"bytes,2,opt,name=signer,proto3" json:"signer,omitempty"`
	DNSName string `protobuf:"bytes,3,opt,name=dns_name,json=dnsName,proto3" json:"dns_name,omitempty"`
}
```

Is that right?

**Comment by awalterschulze** [comment]
nullable=true does not exist, but its an interesting use case.
If someone wants to develop this feature I can help guide them.

The protobuf team would recommend you add another bool field IsCASet which is there to imply whether the IsCA field is set of not.

nullable=false has some idiosyncrasies, which makes developing nullable=true quite hard.
proto2 generates fields with pointers and this is where nullable=false was born, to generate a field without a pointer.
proto3 generates most, but not all fields, without pointers, so nullable=false is still useful for structs and repeated structs.
The main idiosyncrasy is that proto3 does not serialize default values, but nullable=false does.

**Comment by pzduniak** [comment]
>Is that right?

Yes.

>proto3 generates most, but not all fields, without pointers, so nullable=false is still useful for structs and repeated structs.

Is this _really_ it? When I migrated to proto3 a few projects ago I must have totally ignored this fact. I just assumed that gogoproto used fields without pointers, that clears a lot stuff up. Is this reflected in the transmitted data (ie. can you still differentiate between set and unset bool)?

>If someone wants to develop this feature I can help guide them.

I will add it to our backlog then, we might allocate some time when our company gets some more funding. So that we can, uh, improve tooling ;)

Thanks a lot, I just needed someone to explain to me that proto3 changed the behavior and that it's normal. I guess the shitty workaround that I planned is actually the thing that I should do.

**Comment by awalterschulze** [comment]
Yes they changed behaviour and this is reflected in the transmitted data.  You cannot tell whether a field was set or unset in proto3.  This, in my opinion, was the biggest change from proto2.

Good luck with getting more funding :)
