### ISSUE TITLE
golang/protobuf/jsonpb unmarshal types.Struct error `reflect.Set: value of type map[string]*structpb.Value is not assignable to type map[string]*types.Value `

### ISSUE THREAD

**Issue by uschen** [gogo/protobuf#346]
gogo generated with:
```
Mgoogle/protobuf/struct.proto=github.com/gogo/protobuf/types
```

marshal types.Struct will panic:

```
reflect.Set: value of type map[string]*structpb.Value is not assignable to type map[string]*types.Value

```

it seems golang/protobuf/jsonpb is hardcoded to import `github.com/golang/protobuf/ptypes/struc`

https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb.go#L56

**Comment by awalterschulze** [comment]
Yes.  Please use github.com/gogo/protobuf/jsonpb package instead.

**Comment by awalterschulze** [comment]
I assume this solved the issue, but otherwise please reopen.
