### ISSUE TITLE
GetExtension on FileOptions error: proto: not an extendable proto

### ISSUE THREAD

**Issue by cdevienne** [gogo/protobuf#347]
I cannot get an extension from a FileOptions when "gogoproto_import" option is true.

Here is how to reproduce the error (in a 'mytest' subdir of gogo/protobuf).
Given the following test.proto:
```proto
syntax = "proto3";
option go_package="main";

import "github.com/gogo/protobuf/gogoproto/gogo.proto";
import "google/protobuf/descriptor.proto";

option (gogoproto.gogoproto_import) = true;

extend google.protobuf.FileOptions {
    string theOption = 50000;
}

option (theOption) = "a value";
```
and the following program (test.go):
```go
package main

import proto "github.com/gogo/protobuf/proto"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"
import "compress/gzip"
import "bytes"

func main() {
	var fd google_protobuf.FileDescriptorProto
	reader, err := gzip.NewReader(bytes.NewBuffer(fileDescriptorTest))
	if err != nil {
		panic(err)
	}
	var data = make([]byte, 2048)
	l, err := reader.Read(data)
	if err != nil {
		panic(err)
	}
	data = data[:l]
	if err := proto.Unmarshal(data, &fd); err != nil {
		panic(err)
	}
	if _, err := proto.GetExtension(fd.GetOptions(), E_TheOption); err != nil {
		panic(err)
	}
}
```
I generate the pb file and run with:
```protoc -I. -I ../../../.. --gogo_out=. test.proto  && go build . && ./mytest```

This gives me the following output:
```
panic: proto: not an extendable proto

goroutine 1 [running]:
panic(0x5dadc0, 0xc82000ace0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
main.main()
        /home/cdevienne/ws/ll/golang/src/github.com/gogo/protobuf/mytest/test.go:24
 +0x368
```

Change the gogoproto_import option to "false" and change the import in the program, and the panic vanishes!
Changing the syntax to proto2 did not help.

Is it a bug or did I miss something when it comes to extensions ?

**Comment by awalterschulze** [comment]
What happens when you only change the import to

import google_protobuf "github.com/gogo/protobuf/protoc-gen-go/descriptor"

**Comment by awalterschulze** [comment]
Sorry I meant

import google_protobuf "github.com/gogi/protobuf/protoc-gen-gogo/descriptor"

**Comment by cdevienne** [comment]
Note that this import is also done by the file generated by gogo.
So in order to compile, the change has to be done in both test.go and the generated test.pb.go.

One done, I get the following error from GetExtension:
```
proto: bad extended type; *descriptor.FileOptions does not extend *descripto
r.FileOptions
```

**Comment by awalterschulze** [comment]
Just for reference:

```
gogoproto_import: if false, the generated code imports github.com/golang/protobuf/proto instead of github.com/gogo/protobuf/proto.  Default = true.
```

**Comment by awalterschulze** [comment]
So that means that when `gogoproto=true` then we must import `github.com/gogo/protobuf/protoc-gen-gogo/descriptor` and when `gogoproto=false` we must import `github.com/golang/protobuf/protoc-gen-go/descriptor`

**Comment by awalterschulze** [comment]
But I don't think extensions and ptypes are supported for `gogoproto=false`.  This requires some extra work.

**Comment by awalterschulze** [comment]
Also if you are using `gogoproto=true` then you can just leave it out, since `gogoproto=true` is the default.

**Comment by awalterschulze** [comment]
Does this explain it, or do you still think there is a bug (not impossible)?

**Comment by cdevienne** [comment]
As I said, even using github.com/gogo/protobuf/protoc-gen-gogo/descriptor does not fix the issue: I still cannot access the extension (error: bad extended type).

I cannot say for sure if it is bug or a misuse but the fact is that I am stuck.

**Comment by awalterschulze** [comment]
[issue347.zip](https://github.com/gogo/protobuf/files/1410287/issue347.zip)

I used this make command

`protoc --proto_path=../../../../../:../../protobuf/:. --gogo_out=Mgoogle/protobuf/descriptor.proto=github.com/gogo/protobuf/protoc-gen-gogo/descriptor:. test.proto`

And then it "works" or then I get the panic:
```
panic: EOF [recovered]
	panic: EOF

goroutine 5 [running]:
testing.tRunner.func1(0xc4200ac0f0)
	/usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0x116b780, 0xc42004a040)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/gogo/protobuf/test/issue347.TestBla(0xc4200ac0f0)
	/Users/waschulze/code/src/github.com/gogo/protobuf/test/issue347/issue347_test.go:21 +0x265
testing.tRunner(0xc4200ac0f0, 0x11aa060)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de
exit status 2
FAIL	github.com/gogo/protobuf/test/issue347	0.008s
```

I have attached the whole folder that I placed in ./test/issue347 to get this to work.

**Comment by awalterschulze** [comment]
I hope this helps?

Maybe it was the -M that was missing :(

**Comment by cdevienne** [comment]
It does work indeed. I must have made a mistake at my last attempt.
Thanks a lot!

Now should this be the default behavior of gogo?

**Comment by awalterschulze** [comment]
My pleasure

Do you mean adding the M parameter as a default?

**Comment by cdevienne** [comment]
I mean the effect it has:
Import the ..-gogo/descriptor instead of ..-go/descriptor in the generated file when gogoproto.gogoproto_import is true/.

**Comment by awalterschulze** [comment]
Sorry, but I am and have been struggling to get the full picture, since I don't know what the failed generated code looks like.  Could you try to give someone who is context switching (me) a clear picture, by including some generated code please?
Sorry for the inconvenience.

**Comment by cdevienne** [comment]
The problem occurs when we extend types from "google/protobuf/descriptor.proto" (which is needed when we define custom options).

With the current version of gogo/protobuf, the generated code imports the original golang "github.com/gogo/protobuf/protoc-gen-gogo/descriptor" as "google_protobuf" and uses it to define the extensions types. In my example:

```go
var E_TheOption = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50000,
	Name:          "theOption",
	Tag:           "bytes,50000,opt,name=theOption",
	Filename:      "test.proto",
}
```

But here the "proto" is from gogo, which means we have to use gogo proto.GetExtensions to pass E_TheOption and retrieve it from a *descriptor.FileOptions.

I don't know exactly why but mixing `import proto "github.com/gogo/protobuf/proto"` and `import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"` somehow confuses proto.GetExtensions.

The solution you proposed (the -M flag) solves the problem by using `import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"` in the generated file.

Which leads me to think that importing "github.com/gogo/protobuf/protoc-gen-gogo/descriptor" (and not "github.com/golang/protobuf/protoc-gen-go/descriptor") should be the default behavior when the option "gogoproto.gogoproto_import" is "true".

The other solution would be to make GetExtension play nice with "github.com/gogo/protobuf/protoc-gen-gogo/descriptor".

I hope I made it clearer.

**Comment by awalterschulze** [comment]
Is this sentence correct?

```
With the current version of gogo/protobuf, the generated code imports the original golang "github.com/gogo/protobuf/protoc-gen-gogo/descriptor" as "google_protobuf" and uses it to define the extensions types. In my example:
```

Because original golang sounds like it should be you meant
```
"github.com/golang/protobuf/protoc-gen-go/descriptor" 
```

Or am I just miss reading?

**Comment by cdevienne** [comment]
You are right I made a mistake, I indeed meant 
> "github.com/golang/protobuf/protoc-gen-go/descriptor"

**Comment by awalterschulze** [comment]
I updated your previous comment to reflect this correction.

**Comment by awalterschulze** [comment]
When I look at how I generate gogoproto, which also extends google/protobuf/descriptor.proto, then I see that I also added the -M parameter
https://github.com/gogo/protobuf/blob/master/gogoproto/Makefile#L31
```
protoc --gogo_out=Mgoogle/protobuf/descriptor.proto=github.com/gogo/protobuf/protoc-gen-gogo/descriptor:. --proto_path=../../../../:../protobuf/:. *.proto
```

But when I remove it the generated code now imports 
```go
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "google/protobuf"
```

Which is different from what you describe.  So I suspect this would require the same type of solution for golang/protobuf.

```
protoc --go_out=Mgoogle/protobuf/descriptor.proto=github.com/golang/protobuf/protoc-gen-go/descriptor:. --proto_path=../../../../:../protobuf/:. *.proto
```

So I am a bit afraid of touching the import statements here, since this is their solution as well.
This is also the proposed solution for other "Well Known Types" in golang/protobuf.

Maybe my being afraid of touching any import semantics stems from me struggling to imagine how it effects other language outputs as well and me not understanding why golang/protobuf chose these solutions in the first place.

The reason GetExtensions gets confused is because gemerated extensions registers themselves with the imported proto package:

```go
func init() {
	proto.RegisterExtension(E_GoprotoEnumPrefix)
```
When you call getExtensions it looks up this register value.  So if you are calling a different package than where it was registered then this does not work.

This is not how java does it.  Java requires you to pass in your extensions to the unmarshaler, which I think is a much cleaner way of doing it, but the register pattern is sometimes easier for users to understand the first time.

**Comment by awalterschulze** [comment]
I hope I answered your question.  Otherwise please reopen.
