### ISSUE TITLE
Problem with proto3 type "any.proto"

### ISSUE THREAD

**Issue by markschmid** [gogo/protobuf#348]
When generating the .pb.go file using gogo protobuf (--gofast_out or --gogofast_out), the generated .pb.go file contains some errors:

`m.User.Size undefined (type *any.Any has no field or method Size)
m.User.MarshalTo undefined (type *any.Any has no field or method MarshalTo)
m.User.Unmarshal undefined (type *any.Any has no field or method Unmarshal)`

It's working fine when I use regular --go_out
I tried things like `-I$GOPATH/src/github.com/gogo/protobuf/protobuf` and `Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types` but so far, no luck.

Should using the any.proto type just work "out of the box"?

I'm on macOS, using latest versions of Go and the libraries.

**Comment by markschmid** [comment]
Never mind, it was my IDE (Visual Studio Code) that was not "refreshing" its state properly anymore. After a restart of the IDE, no errors anymore. Sorry.

**Comment by awalterschulze** [comment]
No problem :)  I hope you enjoy using gogoprotobuf :).

**Comment by markschmid** [comment]
Hmm, something is still off.
When compiled with gogoprotobuf, I get the following error:

`cannot use user.User (type *types.Any) as type *any.Any in argument to ptypes.Is`
(the type `*types.Any` is unexpected here, I think it should be `*any.Any`)

When the same .proto file is compiled with regular golang/protobuf, I don't get the error and user.User is of type `*any.Any`

*any.Any ideas of what's happening? ;)
Thanks.

**Comment by awalterschulze** [comment]
With gogoprotobuf it is easier to use 
https://github.com/gogo/protobuf/tree/master/types

```
regenerate:
	go install github.com/gogo/protobuf/protoc-gen-gogo
	protoc --gogo_out=\
	Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,\
	Mgoogle/protobuf/duration.proto=github.com/gogo/protobuf/types,\
	Mgoogle/protobuf/struct.proto=github.com/gogo/protobuf/types,\
	Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,\
	Mgoogle/protobuf/wrappers.proto=github.com/gogo/protobuf/types:. \
	--proto_path=../../../../../:../../protobuf/:. my.proto
```

**Comment by markschmid** [comment]
Thanks! It still doesn't quite work though... I'm using it in grpc context (plugins=grpc), does that matter in this case?
Also, which directories should the `--proto_path` point to?

**Comment by awalterschulze** [comment]
This part of the proto_path `../../../../../` == $GOPATH/src
`../../protobuf/` == $GOPATH/srcgithub.com/gogo/protobuf/protobuf
`.` == your protos location

It should still work in the grpc context.

**Comment by awalterschulze** [comment]
Did it work?

**Comment by awalterschulze** [comment]
Closing since no response :(

**Comment by gertcuykens** [comment]
Hmm that you would have to do this for gofast I more or less get, but that it doesn't use the gogo once for gogofast is a bit of cumbersome. Especially if you need to write all this in a one liner go:generate
```
protoc -I . task.proto --gogofast_out=plugins=grpc,\
Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/duration.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/struct.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/wrappers.proto=github.com/gogo/protobuf/types:.
```
The vanila go_out set it's own proto types internally for you right? So why not let gogofast set them by default? I understand that you dont want this for gofast but gogofast I asume everybody want the gogo once.
