### ISSUE TITLE
go get  fails on gofast

### ISSUE THREAD

**Issue by cloudmode** [gogo/protobuf#353]
go get github.com/gogo/protobuf/protoc-gen-gofast

returns:

You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

package github.com/gogo/protobuf/protoc-gen-gofast: exit status 1

**Comment by awalterschulze** [comment]
I cannot reproduce.
I just tried it and it works.

**Comment by cloudmode** [comment]
found this discussion:
https://groups.google.com/forum/#!topic/golang-nuts/t9dLLVwsMlM

did rm -rf of $GOPATH/src/github.com/gogo/protobuf
then it worked. 

there was an old version in there that seemed to be causing problems with git

**Comment by awalterschulze** [comment]
cool :)  Glad you got it solved.
