### ISSUE TITLE
Support treating warnings as errors (-Werror)

### ISSUE THREAD

**Issue by benesch** [gogo/protobuf#356]
We like to keep our protobufs neat and tidy over at cockroachdb/cockroach, which means we very much dislike when protobuf compilation outputs warnings. In fact, we'd like to be able to treat all of gogoproto's warnings as errors that fail compilation.

I'm about to [commit a hack](https://github.com/cockroachdb/cockroach/pull/20339/commits/3b8936d496ddd5f1ebfa313a8f41791e477861e7) that assumes any output from `protoc` is a warning and fails the build, but it'd be less gross to have the equivalent of a `-Werror` flag supported natively by gogoproto.

Not sure how hard that would be; looks like warnings currently [print directly to stderr](https://github.com/gogo/protobuf/blob/a11c89fbb0ad4acfa8abc4a4d5f7e27c477169b1/plugin/defaultcheck/defaultcheck.go#L102).

In any case, thanks for maintaining such a great project. It's been immensely valuable to us.

**Comment by awalterschulze** [comment]
Yes the warnings are just printed, but the stderr or using the logger

Here is a list of the current Warnings:

```go
fmt.Fprintf(os.Stderr, "WARNING: field %v.%v is a repeated non-nullable native type, nullable=false has no effect\n", generator.CamelCase(*msg.Name), generator.CamelCase(*field.Name))
```

```go
fmt.Fprintf(os.Stderr, "WARNING: field %v.%v is a non-nullable bytes type, nullable=false has no effect\n", generator.CamelCase(*msg.Name), generator.CamelCase(*field.Name))
```

```go
fmt.Fprintf(os.Stderr, "WARNING: found non-%v %v with embedded %v %v\n", names, ccTypeName, errStr, fieldname)
```

This one is in protoc-gen-gogo/generator.go and is from golang/protobuf
```go
log.Printf("protoc-gen-gogo: WARNING: failed finding publicly imported dependency for %v, used in %v", typeName, *g.file.Name)
```

Do you regularly get any of these 4 warnings?

Maybe I missed some?

**Comment by benesch** [comment]
Yeah, the one we regularly see is "BLAH is a repeated non-nullable native type". We mark more or less everything as non-nullable to avoid allocation, so it's easy to let muscle memory take over and mark a native type as non-nullable.

It occurs to me that protoc itself generates warnings ("import FOO but not used", for example), so perhaps this is more of an upstream issue. I'll file there.

**Comment by awalterschulze** [comment]
On Thu, 30 Nov 2017 at 23:14 Nikhil Benesch <notifications@github.com>
wrote:

> Yeah, the one we regularly see is "BLAH is a repeated non-nullable native
> type". We mark more or less everything as non-nullable to avoid allocation,
> so it's easy to let muscle memory take over and mark a native type as
> non-nullable.
>
Ah I remember when I was working for a company using gogoprotobuf, that we
also had MANY of those reflex actions.


> It occurs to me that protoc itself generates warnings ("import FOO but not
> used", for example), so perhaps this is more of an upstream issue. I'll
> file there.
>
Ah yes, that one does not seem to be part of gogoprotobuf.

**Comment by awalterschulze** [comment]
Should we close this issue or do you still want to change something in gogoprotobuf as well?
