### ISSUE TITLE
linter complains on code in generated Equal implementation

### ISSUE THREAD

**Issue by temoto** [gogo/protobuf#360]
First, huge thanks for improved protobuf.

Code generated by gogo/slick:
```
func (this *Request) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}
```

`gosimple` linter complain:
> /path/bla/bla.pb.go:349:3:warning: should use 'return <expr>' instead of 'if <expr> { return <bool> }; return <bool>' (gosimple)

Generated code could be reduced down to:
```
func (this *Request) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}
```

Thanks for gogo/protobuf. Have a great time.

**Comment by awalterschulze** [comment]
My pleasure :)

Is this the only remark the linter had?

**Comment by temoto** [comment]
Also it doesn't like repeated string literals in `*valueToString()` and `GoString()`. I guess linter wants `"nil"` hoisted into constant declaration.

**Comment by awalterschulze** [comment]
I would be willing to review the code if you are willing to make a pull request to fix these, if possible?

**Comment by temoto** [comment]
* Fixing `return this == nil` was super easy, nice code.
* Seems I'm not smart enough to fix `"nil"` constant. Naive approach would create duplicate declaration in sibling `second.pb.go` in same package.
* Irrelevant thought on `p.In()/p.Out()` - wouldn't it be better to produce "raw" code without indentation and fix everything with `gofmt` run?

**Comment by awalterschulze** [comment]
On p.In and p.Out.
Maybe yes.
In my other code generating project [goderive](https://github.com/awalterschulze/goderive) I generate gofmted code the first time, using p.In and p.Out.  I find that running gofmt over a few 100 000 lines of code becomes quite slow and tedious.
But if you code generators output go fmted code and your editor gofmts your code when you save, then you technically don't have to ever run gofmt over your whole code base.
So in the interest of a fast compile (and code generation) feedback loop, I think we actually need to put in more of an effort in gogoprotobuf to generate gofmted code and that way we can speed up some developers' feedback loop.

**Comment by temoto** [comment]
Understood. Have a great time.

**Comment by awalterschulze** [comment]
I hope it makes sense.

**Comment by temoto** [comment]
#perfmatters yo 👍

**Comment by shurcooL** [comment]
@temoto I'm just wondering, did you explicitly ask `gosimple` to include generated files in its scan (because the default is [false](https://github.com/dominikh/go-tools/blob/376b3b58b9e4def403181ee2fd3d4cc7de8375ae/cmd/gosimple/gosimple.go#L12)), or did it fail to detect that these were generated files?

**Comment by temoto** [comment]
@shurcooL I did not run gosimple at all. It's done by gometalinter with following config. It is quite possible that my gometalinter (with vendored linters) is too old to skip generated files. Anyway I'm quite happy that it checked and I had pleasure to get familiar with gogoprotobuf internals and remove ~4000 lines from tests fixtures.

**Comment by shurcooL** [comment]
I see, thanks.

I agree that this `return this == nil` change was a good simplification to make. But in the general case, I don't think that all linter advice is always appropriate for generated files; careful situational consideration should be applied.

**Comment by awalterschulze** [comment]
Exactly. I am open to generate more lintable code, but I will take it case by case.
