### ISSUE TITLE
 Add all WKT to ./types?

### ISSUE THREAD

**Issue by peter-edge** [gogo/protobuf#362]
When you download protoc from the releases page, it includes all the WKT:

```
		"google/protobuf/compiler/plugin.proto",
		"google/protobuf/any.proto",
		"google/protobuf/api.proto",
		"google/protobuf/descriptor.proto",
		"google/protobuf/duration.proto",
		"google/protobuf/empty.proto",
		"google/protobuf/field_mask.proto",
		"google/protobuf/source_context.proto",
		"google/protobuf/struct.proto",
		"google/protobuf/timestamp.proto",
		"google/protobuf/type.proto",
		"google/protobuf/wrappers.proto",
```

We only have a subset of these in `./types` - I know golang/protobuf made a similar call, but it's really difficult to split on the WKT in terms of what is and isn't in here. Can we add:

- api.proto
- source_context.proto
- type.proto

I know that `compiler/plugin.proto` and `descriptor.proto` are special-cased. This would mean that anyone using gogo/protobuf has access to compiled representations of all the WKTs, and no need to have logic that splits on whether or not a WKT exists in gogo/protobuf.

**Comment by peter-edge** [comment]
I know these are in e.g. https://godoc.org/google.golang.org/genproto/protobuf/api, is there a compatibility issue?

**Comment by awalterschulze** [comment]
We can definitely try adding api.proto, source_context.proto and type.proto into the types folder.

**Comment by awalterschulze** [comment]
I started some work here, but yeah import loop
https://github.com/gogo/protobuf/tree/morewkts
Not sure how to solve it yet.

**Comment by awalterschulze** [comment]
Merged
