### ISSUE TITLE
go-micro micro plugin not generating ServiceHandler

### ISSUE THREAD

**Issue by aleksarias** [gogo/protobuf#365]
When generating *.pb.go files from proto files using the following command: 
```
protoc -I=$(GOPATH)/src:. --gofast_out=plugins=micro:$(GOPATH)/src/github.com/aleksarias/golanging/importer-service \
proto/importer/importer.proto
```
The micro plugin provided by go-micro isn't used to generate the services.

**Comment by awalterschulze** [comment]
Go micro has a fork of protoc-gen-go. If you want to use the micro plugin
with gogoprotobuf, someone will need to make a fork of gogoprotobuf which
includes the micro plugin.

It should be quite easy. I would even look at the gogoprotobuf vanity
library, which is built to make such forks easier and more minimal.

**Comment by awalterschulze** [comment]
I hope that makes sense, if not please reopen.
