### ISSUE TITLE
Some unit tests can not locate  github.com/gogo/protobuf/gogoproto/gogo.proto

### ISSUE THREAD

**Issue by nim-nim** [gogo/protobuf#369]
Hi,

Fo some reason, all unit tests pass in release 0.5 *except* two packages that do not seem to find  github.com/gogo/protobuf/gogoproto/gogo.proto

# test/dashfilename
# df_test.go:43: err = exit status 1: github.com/gogo/protobuf/gogoproto/gogo.proto: File not found
# test/embedconflict
# ec_test.go:54: received error = exit status 1 and output = github.com/gogo/protobuf/gogoproto/gogo.proto: File not found.

Do those packages need a specific setup?

**Comment by nim-nim** [comment]
Ok, I've found the problem, sorry for the bother

**Comment by awalterschulze** [comment]
No problem :)

May I ask what the problem was, for future, if others run into the same problem?

**Comment by nim-nim** [comment]
Actually, I thought I had solved it, but nope :( Was waiting for a little more available braincells to investigate some more (I do note Fedora had disabled one of the problem tests in its packaging of an older version so there is something specific and fishy in them)

Can't figure why those two tests complain about this particular file when it's installed with the others in the same place

**Comment by awalterschulze** [comment]
These are both tests that execute protoc from within in the go tests and check the output of protoc.
Most others expect protoc to have already been executed using make.

**Comment by awalterschulze** [comment]
Interesting that you are not having problems with defaultconflict, issue270 and sizerconflict, which also do the same thing.

**Comment by awalterschulze** [comment]
May I ask you to try

```go
cmd := exec.Command("protoc", "--gogo_out=.", "-I=$GOPATH/src/:$GOPATH/src/github.com/gogo/protobuf/protobuf/:.", name+".proto")
```

instead of

```go
cmd := exec.Command("protoc", "--gogo_out=.", "-I=../../../../../:../../protobuf/:.", name+".proto")
```

in test/dashfilename

And to check whether you are not having the same problem with the three tests I mentioned in the previous comment?

**Comment by nim-nim** [comment]
Hi,

Thank you for pointing me there, this is indeed the root of the problem.

I tried many permutations with no success, relative paths seem to fail, variables such as GOPATH seem not to be evaluated (even though they are positioned at the right value), it's a major PITA

In the end I had to do this very dirty workaround at test time

for testfile in  $(grep -rl -- '"-I=../../../../../:../../protobuf/:."' test) ; do
  sed -i "s+\"-I=../../../../../:../../protobuf/:.\"+\"-I=%{buildroot}%{gopath}/src/:.:%{_includedir}\"+g" $testfile
done

(%{buildroot}%{gopath} is where the files are installed during tests and yes it is in GOPATH, %{_includedir} is the system location of ptotobuf files)

I'm not proud of it but it unlocks all tests :(

**Comment by awalterschulze** [comment]
What happens if we run `os.Getenv` in the test to get the gopath and update the paths with that in the tests?

Maybe we can avoid your sed.
