### ISSUE TITLE
add to readme that to use proto files from google/protobuf we need to add Mgoogle/protobuf/<filename>.proto=github.com/gogo/protobuf/types 

### ISSUE THREAD

**Issue by AlexRouSg** [gogo/protobuf#370]
Couldn't find this mentioned in obvious places and took a while of googleing before I found https://github.com/gogo/protobuf/blob/master/test/types/Makefile which shows the extra args I needed to set to get it to compile.

Also it would be nice if there's a github.com/gogo/protobuf/types/<filename>.proto we could import instead so we don't need to have a very long protoc command.

**Comment by awalterschulze** [comment]
Sounds like a good plan to add a note to the readme, would you like to make a pull request?

I am not sure making a not very long command is possible.  Could you elaborate on your idea?

**Comment by AlexRouSg** [comment]
Like can't we move the proto files from gogo/protobuf/protobuf/google/protobuf to gogo/protobuf/types?

So instead of import "google/protobuf/wrappers.proto"; I can do import "github.com/gogo/protobuf/types//wrappers.proto"; 
That way I don't have to add the Mgoogle.....

**Comment by awalterschulze** [comment]
Every other programming language is expecting the types to be under google/protobuf
This move would result in a loss of interoperability.

**Comment by AlexRouSg** [comment]
Ahhh, didn't considered that. I'm assuming it's not something that can be done by protoc-gen-gogo automatically either?

**Comment by awalterschulze** [comment]
Maybe, but the import logic is already so complex I wouldn't really want to add another special case :(
There is import_prefix, -M, proto_path and go_package also has an influence.
To be honest the import logic is the part of this project that I find the hardest to understand.

**Comment by AlexRouSg** [comment]
Pull request sent :)
