### ISSUE TITLE
Protobuf not generating RegisterExampleHandler?

### ISSUE THREAD

**Issue by mdere** [gogo/protobuf#379]
Hello - first off I am new to Golang and gomicro as a whole. So trying to learn this myself through micro go examples. So I am at the point where I am playing around with the template example.  One thing I noticed after I ran protoc and building main.go - 

```
github.com/test/greeter
./main.go:20:2: undefined: go_micro_srv_template.RegisterExampleHandler
```

Can someone please clarify if the example was suppose to work or I have to implement that method to my proto and my handler before I run protoc?

Thanks in an advance!

**Comment by mdere** [comment]
Also I am using Ubuntu 16 as my environment and I installed protobuf using this guide https://gist.github.com/sofyanhadia/37787e5ed098c97919b8c593f0ec44d8

**Comment by awalterschulze** [comment]
This is the gogoprotobuf repo not the go micro repo. Could you please ask
them?

**Comment by mdere** [comment]
@awalterschulze  - yup i just realized that - I had multiple tabs open haha - sorry for the bother man

**Comment by justjoeyuk** [comment]
As a note, if anybody comes across this issue the solution is as follows:

`go get github.com/micro/protoc-gen-micro`
`protoc -I. --micro_out=. --gogo_out=. path/to/my.proto`
