### ISSUE TITLE
how can I get jsonpb to embed json for `gogoproto.embed` fields?

### ISSUE THREAD

**Issue by ilackarms** [gogo/protobuf#380]
I have a proto definition that looks like this:

```proto
message Item {
    Metadata metadata = 1  [(gogoproto.embed) = true];
    repeated string attributes;
}


message Metadata {
    string name = 1;
}

```

The generated Go from this looks like:
```go

type Item struct {
	*Metadata `protobuf:"bytes,1,opt,name=metadata,embedded=metadata" json:"metadata,omitempty"`
	Attributes   []string   `protobuf:"bytes,2,rep,name=attributes" json:"attributes,omitempty"`
}

```

I *expect* the output of `jsonpb.Marshaler{}.Marshal()` to look like:
```json
{
  "name": "foo",
  "attributes": ["a"]
}
```

However, the result is:
```json
{
  "metadata": {
    "name": "foo"
  },
  "attributes": ["a"]
}
```

I would like that the json for `metadata` is embedded in the parent object. I thought this would be the expected behavior given the `[(gogoproto.embed) = true]` tag.

Is there any way to achieve this?

**Comment by awalterschulze** [comment]
Embed is only there to change the appearance of the generated code. Not the
Serialization. Changing jsonpb's behavior would break the specified proto
contract with another language. You could try encoding / json for this.

**Comment by ilackarms** [comment]
thanks @awalterschulze 
i'm relying on `jsonpb` to handle `oneof` fields currently, so i don't think there's an option to use `encoding/json`
i think the only way to achieve the desired result is to manually embed the `Metadata` fields in the messages that contain them. thanks.

**Comment by awalterschulze** [comment]
Sorry to disappoint
