### ISSUE TITLE
Confused about jsontag

### ISSUE THREAD

**Issue by briansorahan** [gogo/protobuf#385]
I created a test on my fork to illustrate my confusion. Hopefully I'm doing something dumb.

Here is the [message](https://github.com/briansorahan/protobuf/blob/76a3535fc673d478f44b18283cac140683a93cac/briantest/msg.proto).
Here is the [generated code](https://github.com/briansorahan/protobuf/blob/76a3535fc673d478f44b18283cac140683a93cac/briantest/msg.pb.go).
Here is the [test](https://github.com/briansorahan/protobuf/blob/76a3535fc673d478f44b18283cac140683a93cac/briantest/msg_test.go) which fails:

```
➜  briantest git:(master) make test
--- FAIL: TestMarshal (0.00s)
    --- FAIL: TestMarshal/using_gogoproto.jsontag (0.00s)
        msg_test.go:39: expected {"a":"foo","b":"bar"}, got {"aField":"foo","bField":"bar"}
FAIL
exit status 1
FAIL    github.com/briansorahan/protobuf/briantest      0.030s
make: *** [test] Error 1
```

I expect the `MsgTags` struct to looks like this when marshalled: `{"a":"foo","b":"bar"}`.
What am I doing wrong?

I'm on a Mac, installed protoc with brew, and followed the instructions in the readme to install the binaries.

```
➜  briantest git:(master) protoc --version
libprotoc 3.5.1
```

**Comment by awalterschulze** [comment]
jsonpb ignores jsontags :(
jsontag only works with encoding/json
Sorry :(

If you want jsontags to work with jsonpb here is an issue with golang/protobuf
https://github.com/golang/protobuf/issues/256

**Comment by briansorahan** [comment]
@awalterschulze I still don't understand how to customize the json struct tag, unfortunately. Note that the generated struct does not contain the gogoproto.jsontag value at all.

Actual:

```go
type MsgTags struct {
	AField string `protobuf:"bytes,1,opt,name=a_field,json=aField" json:"a_field,omitempty"`
	BField string `protobuf:"bytes,2,opt,name=b_field,json=bField" json:"b_field,omitempty"`
}
```

Expected:

```go
type MsgTags struct {
	AField string `protobuf:"bytes,1,opt,name=a_field,json=aField" json:"a,omitempty"`
	BField string `protobuf:"bytes,2,opt,name=b_field,json=bField" json:"b,omitempty"`
}
```

Maybe there is an issue with the way I am [generating the struct](https://github.com/briansorahan/protobuf/blob/76a3535fc673d478f44b18283cac140683a93cac/briantest/Makefile)?

**Comment by awalterschulze** [comment]
Oh good point

https://github.com/briansorahan/protobuf/blob/76a3535fc673d478f44b18283cac140683a93cac/briantest/Makefile#L9

Should be gogo_out

**Comment by awalterschulze** [comment]
I think you also swapped Expected and Actual?

**Comment by briansorahan** [comment]
`--gogo_out` works. Thank you!
