### ISSUE TITLE
Unexpected quotes around Int64Value

### ISSUE THREAD

**Issue by briansorahan** [gogo/protobuf#387]
Using jsonpb.Marshaler (because I need to use the `google.protobuf` wrapper types for nullability), I'm seeing unexpected quotes around fields that are `google.protobuf.Int64Value`.
I believe it's happening [here](https://github.com/gogo/protobuf/blob/b75782e777cfa7ca469bc46cc313ddd26e6e9d1c/jsonpb/jsonpb.go#L686-L693).
[Here is a test](https://github.com/briansorahan/protobuf/blob/master/briantest/msg_test.go#L43-L58) on my fork that is failing.
Is it expected that jsonpb.Marshaler adds quotes?
I [searched](https://github.com/gogo/protobuf/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Int64) for an existing issue describing this but didn't find one.

**Comment by awalterschulze** [comment]
Does the same happen with golang/protobuf or is this a gogo/protobuf specific issue?

**Comment by briansorahan** [comment]
@awalterschulze I just added [this test](https://github.com/briansorahan/protobuf/blob/master/briantest/msg_test.go#L61-L76) which is also failing, so same behavior with google jsonpb.Marshaler
I've also made that my master branch is up to date on both `github.com/golang/protobuf` and `github.com/gogo/protobuf`.

**Comment by briansorahan** [comment]
encoding/json takes a ",string" option in the json struct tag to make certain values encode as strings rather than their default JSON equivalents:

```
The "string" option signals that a field is stored as JSON inside a JSON-encoded string. It applies only to fields of string, floating point, integer, or boolean types. This extra level of encoding is sometimes used when communicating with JavaScript programs
```

Here is a [playground example](https://play.golang.org/p/KQRJ3iVWCeY).
Maybe they chose to make this the default behavior in jsonpb?
I would like this to be optional though.

**Comment by briansorahan** [comment]
@awalterschulze Sounds good https://github.com/golang/protobuf/issues/519

**Comment by briansorahan** [comment]
Closing based on reply from Joe Tsai.
jsonpb Unmarshaler seems to handle this, so it isn't a showstopper.

**Comment by awalterschulze** [comment]
Fair enough.
Thanks for trying.
