### ISSUE TITLE
Imports for custom/casttype are generated incorrectly under certain conditions

### ISSUE THREAD

**Issue by pltr** [gogo/protobuf#389]
Consider the following structure
**foo/bar/A.proto**
```protobuf
syntax = "proto3";
package bar;

message A {
    string f1 = 1;
}
```
**foo/bar/a.go**
```go
package bar;

type B struct {
    A
}
```
**foo/moo/C.proto**
```protobuf
syntax = "proto3";
package moo;

import "github.com/gogo/protobuf/gogoproto/gogo.proto";
import "foo/bar/A.proto";

message C {
     bar.A f2 = 1 [(gogoproto.customtype) = "foo/bar.B"];
}
```
Now the generated file (header) for C.proto:
```go
package moo

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import bar "foo/bar"

import foo_bar "foo/bar"
```
As you can see "foo/bar" gets imported twice in this case, which causes a compilation error:
```
# foo/moo
moo/C.pb.go:19:8: imported and not used: "foo/bar"
```

**Comment by awalterschulze** [comment]
Very interesting.

But customtype is meant for bytes fields.

https://github.com/gogo/protobuf/blob/master/custom_types.md

https://github.com/gogo/protobuf/issues/125

```proto
syntax = "proto3";
package moo;

import "github.com/gogo/protobuf/gogoproto/gogo.proto";
import "foo/bar/A.proto";

message C {
     bytes f2 = 1 [(gogoproto.customtype) = "foo/bar.B"];
}
```

**Comment by pltr** [comment]
But the very first example on that page seems to be not bytes?
Nonetheless bytes compiles but then the generated unmarshaler always overwrites it and allocates f2 on the heap, not sure if it's possible to change that behavior. I solved it temporarily with declaring an empty message `T{}` and using it instead, which works and only allocates `.f2 == nil`, otherwise it calls `f2.Unmarshal()` as expected.

**Comment by awalterschulze** [comment]
Sorry I have not forgotten about you.
I am just struggling to find some time that I can use to focus.
Sorry.

**Comment by awalterschulze** [comment]
Sorry again :(
This is probably one of my worst service moments.
I just came from a 3 day meeting in a Berlin and have some catch up homework to do for a class this Wednesday and then I have friends visiting as well.
I hope to get to this next weekend, in less than a week.

The reason I thought customtype needs to bytes is because this was always the case, until recently when the feature was extended to also allow messages.

Really sorry about this delay.

**Comment by awalterschulze** [comment]
Thanks for reporting this.
I have pushed a fix with a test that shows how it is working now.
https://github.com/gogo/protobuf/commit/1ae71f058b7323f06a3b3c12b420587dcc635b6f

**Comment by awalterschulze** [comment]
Really sorry for taking so long to fix this.
