### ISSUE TITLE
Cyclic dependencies

### ISSUE THREAD

**Issue by ostronom** [gogo/protobuf#392]
Suppose, we have two proto-files:

```proto
syntax = "proto3";

package test;

message A {
  int32 field = 1;
}
```

and

```proto
syntax = "proto3";

package test;

import "a.proto";

message AINB {
  A a = 1;
}
```

When we compile them like this:

```
protoc --gogoslick_out=. a.proto
protoc --gogoslick_out=. b.proto
```

we end up with `a.pb.go` and `b.pb.go` with the latter depending on the same package (in this case ".") in which it resides itself. This leads to a cyclic dependency.

Is there a way to work around this issue, given that I cannot change packages structure.

**Comment by awalterschulze** [comment]
This will happen with golang/protobuf as well.
The only way to avoid this is to pass all the proto files to protoc in one line :(
I also found this quite hard to deal with.

Here is an example with the well known types
https://github.com/gogo/protobuf/blob/master/protobuf/Makefile#L7-L20
Some of these files import each other, but their destination folder is the same.

I hope this helps.

**Comment by ostronom** [comment]
Thank you. That worked.
