### ISSUE TITLE
Using proto3 any.Any and marshaling

### ISSUE THREAD

**Issue by mcdee** [gogo/protobuf#396]
I have a simple test protobuf definition:

    syntax = "proto3";

    package state;

    import "google/protobuf/any.proto";

    message Test {
        repeated google.protobuf.Any any = 1;
    }

If I compile it using `protoc --gogo_out=. test.proto` the generated code does not contain `Marshal()`.

If I compile it using `protoc --gofast_out=. test.proto` the generated code does not compile, due to problems with any.Any:

    test.pb.go:71:44: msg.Size undefined (type *any.Any has no field or method Size)

Is there a simple way to make the former include the `Marshal()` or the latter to manage any.Any correctly?  I'm trying to keep my definitions as vanilla as possible, as they will be used for other platforms as well, so would like to avoid custom extensions to the .proto file.

**Comment by awalterschulze** [comment]
Have you tried `gogo_fast_out` ?

Also you need to specify your `M` parameters correctly for well known types:

```
protoc -I=. -I=$GOPATH/src -I=$GOPATH/src/github.com/gogo/protobuf/protobuf --{binary}_out=\
Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types:. \
myproto.proto
```

**Comment by awalterschulze** [comment]
Can I close this?

**Comment by adam-hanna** [comment]
I was having the same issue and your proposed solution works for me. If you don't hear back from OP, maybe consider it closed?

**Comment by mcdee** [comment]
Apologies for the delay in responding; this has indeed fixed the issue.  Thanks.
