### ISSUE TITLE
find offset of a field

### ISSUE THREAD

**Issue by xiang90** [gogo/protobuf#40]
Is it reasonable to add a functionality to find out the offset of a field?

I want to write a protobuf {uint64, uint64, []byte} on to disk and mmap back a bytes field. 

Thanks in advance!

**Comment by awalterschulze** [comment]
may I ask why?

**Comment by xiang90** [comment]
> may I ask why? 

I want to write a protobuf {uint64, uint64, []byte} on to disk and mmap back the bytes field.

Probably I should not use protobuf to serialize the struct to disk in this case?

**Comment by awalterschulze** [comment]
The offset is very easy to calculate given the descriptor and the content.
Is uint64, uint64 the field, length
or is it two other fields of type uint64
