### ISSUE TITLE
Expose Vanity TurnOnRegistration

### ISSUE THREAD

**Issue by Tommy-42** [gogo/protobuf#401]
Hi there,

I know that this feature is tagged as BETA, But would you consider exposing it ? 

Why ? 

Instead of importing `gogo/protobuf.proto` in every `.proto` applying a Vanity like `TurnOnRegistration` in custom cmd may be clearer ?

What do you think ?

I opened a PR for you that should do the job cc https://github.com/gogo/protobuf/pull/402

Thx !

**Comment by awalterschulze** [comment]
Sounds like a great idea.  If there is any other extensions that I missed please feel free to add them as well :)

**Comment by Tommy-42** [comment]
thanks !

I'll keep you in touch if I find more of them  👀

**Comment by awalterschulze** [comment]
Thanks for fixing :)
