### ISSUE TITLE
Issues with `customtype` and grpc

### ISSUE THREAD

**Issue by justjoeyuk** [gogo/protobuf#403]
My proto definition uses the following:

```
message GetByIDRequest {
  bytes ID = 1 [(gogoproto.customtype) = "github.com/globalsign/mgo/bson.ObjectId", (gogoproto.jsontag) = "_id", (gogoproto.moretags) = "bson:\"_id\""];
} 
```
When I attempt to communicate between services, I create a GetByIDRequest and populate the `ID` field with `bson.ObjectIdHex("valid")`.  However, when grpc is marshalling this request I get an `invalid UTF-8 string` error from grpc.

Is there any advice that might be useful here?

**Comment by awalterschulze** [comment]
Maybe we have not covered this, but have you looked at https://github.com/gogo/grpc-example ?
There are quite a few tricks that are necessary to make grpc work with gogoprotobuf.

**Comment by justjoeyuk** [comment]
@awalterschulze I've been spending way too long on this. I've looked at the examples and tried a number of things. We use a lot of `go-micro` under the hood but those implementations shouldn't really matter I think.

I've tried using `string ID = 1 [(gogoproto.casttype) = "github.com/globalsign/mgo/bson.ObjectId"];` and all sorts of variations using bytes, different option, etc. So far, nothing works. After having taken a look at the model for `ObjectId` it adds a lot of functionality to a string, since it's defined as `type ObjectId string`. However, it has it's own custom `MarshalText`, `MarshalJSON`, `UnmarshalText` and `UnmarshalJSON` implementations.

This makes me think that I may have to create my own ObjectId that also has MarshalFrom and MarshalTo functions. Does this seem right to you? If so, I have no idea how to start.

**Comment by awalterschulze** [comment]
Is there some way you could provide a small reproducible example?
It is pretty hard to guess for example, what is the underlying type of bson.ObjectId?

With an example, I would also go and find the place that returns `invalid UTF-8 string` by grepping through the code and adding some panics.  That could also help to shed lite on the situation.

**Comment by awalterschulze** [comment]
Is it still possible give a small example or can we close this?

**Comment by justjoeyuk** [comment]
Close :+1:
