### ISSUE TITLE
Generate custom field only for annotation

### ISSUE THREAD

**Issue by robinhuy** [gogo/protobuf#405]
I want to generate one field for annotation (don't use for storing data), example `tableName struct{}`:

```
type User struct {
    tableName struct{}
    OtherField string
}
```

I using `customtype` and `customname` in proto files (https://github.com/gogo/protobuf/blob/master/extensions.md):

```
message User {  
    bytes table_name = 1 [(gogoproto.customtype) = "struct{}", (gogoproto.customname) = "tableName", (gogoproto.nullable) = false];
    string other_field = 2;
}
```

It generate right struct, but has errors in some methods: Equal, Marshaler, Unmarshaler, Sizer (type struct{} has no field or method Equal, ...).

So I add more options for message to prevent generate these methods:

```
message User {  
    option (gogoproto.equal) = false;
    option (gogoproto.marshaler) = false;
    option (gogoproto.unmarshaler) = false;
    option (gogoproto.sizer) = false;

    bytes table_name = 1 [(gogoproto.customtype) = "struct{}", (gogoproto.customname) = "tableName", (gogoproto.nullable) = false];
    string other_field = 2;
}
```

It work perfectly. But every time I add more message which using User message, I must add all options above. Example:

```
message GetUser {
    option (gogoproto.equal) = false;
    option (gogoproto.marshaler) = false;
    option (gogoproto.unmarshaler) = false;
    option (gogoproto.sizer) = false;
  
    User user = 1;
}
```

When message User was used in many places, I must add too many options in proto files.
(github example: https://github.com/robinhuy/learning/tree/master/gogo-protobuf)

How to mark one field in a message only for annotation but don't need to add too many options (and don't affect other fields)?

**Comment by awalterschulze** [comment]
There are a few options here, but I think this is the easiest:
What about writing the equal, marshal, unmarshal and size methods manually for User.
Then all other structs can still generate those methods.

**Comment by robinhuy** [comment]
Thanks @awalterschulze .

But I think I will create another struct User for my project so I don't need to change the generated code.

**Comment by awalterschulze** [comment]
@robinhuy my pleasure :)

How would that work?
If only to explain this to someone else that finds this issue.

**Comment by robinhuy** [comment]
I reuse the struct generated from proto to create database model (using https://github.com/go-pg/pg).

And I need add some special field that does not supported in protobuf (like `tableName struct{}`).

So with structs which have many special fields that gogo hard to support, I will declare another struct in project.

**Comment by awalterschulze** [comment]
There is one more way.
If you don't want to marshal the tableName as part of the protobuf but still have it in the same struct then:
`gogoproto.typedecl=false`
Is a way to generate all the code except for the struct itself.
So you manually define the struct with all the extra fields you might require and the generated marshaler and unmarshaler will only touch the fields declared in the .proto file.
This is probably the most powerful feature in gogoprotobuf.

I think avoiding proxy objects (objects that are just there for marshaling and unmarshaling) is a great way to write performant software.  With proxy objects you have to copy between the objects you want to use and the generated proxy objects, this code is not only tedious to write, but also creates more garbage for the garbage collector to keep track of and allocates more memory which is also expensive.
