### ISSUE TITLE
Need sync golang/protobuf version 1.1.0

### ISSUE THREAD

**Issue by GrapeBaBa** [gogo/protobuf#409]
We meet this issue https://github.com/google/protobuf/issues/4582

**Comment by awalterschulze** [comment]
Most of the work (which was a lot) has been done, but we still have one issue left
https://github.com/golang/protobuf/pull/591#commitcomment-28469112
Once this is fixed we will merge the `dev` branch into `master` and be in sync with golang/protobuf version 1.10

**Comment by xjewer** [comment]
do you have any news?

**Comment by awalterschulze** [comment]
We are working on it over here
https://github.com/gogo/protobuf/pull/412

**Comment by awalterschulze** [comment]
We finally have a pull request
https://github.com/gogo/protobuf/pull/424/files

And then there are two more commits to merge before releasing 1.1

https://github.com/golang/protobuf/commit/3fac2a27c94f99f4379551928df388fcb0ad37ce
https://github.com/golang/protobuf/commit/7c4add53b497798e7fd7b204f28e41ab409bdbb7

**Comment by awalterschulze** [comment]
Merged :)

Now just for the last two commits.

**Comment by awalterschulze** [comment]
Released
https://github.com/gogo/protobuf/releases/tag/v1.1.0
