### ISSUE TITLE
Suggestion: Add information of gogo/protobuf version as a comment in generated go source files.

### ISSUE THREAD

**Issue by c-bata** [gogo/protobuf#419]
Hi. First, I want to say thank you for developing. This go source files generator is really flexible.

When I reviewed pull requests including changes of `*.pb.go`, It's difficult to identify what's gogo/protobuf version is used when generating `*.pb.go` from the diffs. Perhaps my colleague generated by using old version of gogo/protobuf. That's why I opened this suggestion.

But I know we can't change the outputs of previous versions because the consistency of generated files are really important in this project. So I suggest this for future releases.

How do you feel about this suggestion?
Thanks.

**Comment by awalterschulze** [comment]
What do you think about this issue on golang/protobuf
https://github.com/golang/protobuf/issues/524

We would most probably merge a change they make there.
If you take your request there, then gogoprotobuf can stay more consistent with its origin.
Would you mind?

**Comment by c-bata** [comment]
I think your thought is more reasonable than me. Thanks for your quick response 👍

**Comment by awalterschulze** [comment]
My pleasure and good luck :)
