### ISSUE TITLE
Fields are out of order

### ISSUE THREAD

**Issue by andyleap** [gogo/protobuf#42]
The generated marshalling code is building messages out of order.  While still usable, this doesn't conform to spec.

Issue is most likely at https://github.com/gogo/protobuf/blob/master/plugin/marshalto/marshalto.go#L319, and `message.Field` just needs to be sorted by tag number

**Comment by awalterschulze** [comment]
I must have missed it.
Could you please point to where it says in the spec that the message should be marshaled in field number order?

Do you know what golang/protobuf does?

**Comment by EricJ2190** [comment]
https://developers.google.com/protocol-buffers/docs/encoding#order

**Comment by andyleap** [comment]
so, it's not "MUST", just a should, but it shouldn't be too hard.  Golang/Protobuf does serialize in tag order https://github.com/golang/protobuf/blob/master/proto/encode.go#L1177

**Comment by awalterschulze** [comment]
Awesome thank you for reporting.
This is now an issue that needs to be fixed.
https://developers.google.com/protocol-buffers/docs/encoding#order

**Comment by awalterschulze** [comment]
I have made a fix on the proto3 branch
https://github.com/gogo/protobuf/commit/4d206a9868d69cfbcd1fa8aec562976a31a3ce35
What do you think?

**Comment by awalterschulze** [comment]
I believe this is fixed.
Please reopen if you think I am wrong.
