### ISSUE TITLE
Cannot use stdtime and stdduration extensions in query parameters in gRPC-gateway

### ISSUE THREAD

**Issue by johanbrandhorst** [gogo/protobuf#420]
Hi!

We ran into this recently at work, but I'm aware there's not much GoGo Protobuf can do about it, so I'm just raising it as a reference point for others who may run into this problem. Essentially:

_IF_ you use the gRPC-Gateway
and
_IF_ you use `gogoproto.stdtime` or `gogoproto.stdduration`
and 
_IF_  you use either of the aforementioned types in a `GET` request with no body

then you will see the following error in reply to your request:
```
unsupported field type reflect.Value
```

This, rather cryptically, points to a problem in the gRPC-Gateway query parameter resolution. The error comes from https://github.com/grpc-ecosystem/grpc-gateway/blob/fa90cfb8fa521cb2df47e090ea21ad310a188d07/runtime/query.go#L294, but the issue is really that that method is not equipped to handle a target field of type `*time.Time` or `*time.Duration`.

I _will_ attempt to fix this in the gRPC-Gateway, but I'm not terribly hopeful that it will be merged, since it only affects users of GoGo Protobuf.

The workaround, of course, is to not use `gogoproto.stdtime` or `gogoproto.stdduration` for fields that are parsed from the query parameters in your gRPC-Gateway requests.

**Comment by johanbrandhorst** [comment]
Fix submitted to grpc-gateway

**Comment by awalterschulze** [comment]
Wow sorry I've been a little sick, so I haven't caught up with everything yet.  This is really awesome work.  The pull request to grpc-gateway looks great.  I really hope they accept it.
Keeping the gogoprotobuf dependency out was key to it having a chance, great call :)

**Comment by awalterschulze** [comment]
Wow this is awesome work thank you so much @johanbrandhorst and @tmc
I really appreciate this :D

**Comment by awalterschulze** [comment]
I guess we can close this issue now?

**Comment by johanbrandhorst** [comment]
Yes, agreed
