### ISSUE TITLE
proto.Marshal panics on nil pointer since v1.1.0

### ISSUE THREAD

**Issue by johannasmith** [gogo/protobuf#428]
A call to `proto.Marshal` as of [1.0.0](https://github.com/gogo/protobuf/blob/1adfc126b41513cc696b209667c8656ea7aac67c/proto/encode.go#L223-L242) runs fine, but since the reorg and [newMarshaller interface](https://github.com/gogo/protobuf/blob/7d68e886eac4f7e34d0d82241a6273d6c304c5cf/proto/table_marshal.go#L2699-L2758), my tests break on usage.

```
Test Panicked
      runtime error: invalid memory address or nil pointer dereference
      /usr/local/go/src/runtime/panic.go:491

      Full Stack Trace
      	/usr/local/go/src/runtime/panic.go:491 +0x2a2
      github.com/gogo/protobuf/proto.makeOneOfMarshaler.func1(0xc42007ae48, 0x0, 0x19f)
      	/tmp/build/f541ec31/workspace/src/github.com/gogo/protobuf/proto/table_marshal.go:2398 +0x1ce
      github.com/gogo/protobuf/proto.(*marshalInfo).size(0xc4204f8200, 0xc42007ae10, 0xc42039c740)
      	/tmp/build/f541ec31/workspace/src/github.com/gogo/protobuf/proto/table_marshal.go:198 +0x19d
      github.com/gogo/protobuf/proto.(*InternalMessageInfo).Size(0xc42039c740, 0x1146900, 0xc42007ae10, 0x0)
      	/tmp/build/f541ec31/workspace/src/github.com/gogo/protobuf/proto/table_marshal.go:129 +0x8f
      github.com/gogo/protobuf/proto.Marshal(0x1146900, 0xc42007ae10, 0xc42007ae10, 0x2, 0xc4200c89c8, 0x0, 0x0)
      	/tmp/build/f541ec31/workspace/src/github.com/gogo/protobuf/proto/table_marshal.go:2749 +0x169
.
.
.
```

**Comment by awalterschulze** [comment]
Could you provide a small reproducing example, that we can use as a test, when we attempt a fix?

**Comment by johannasmith** [comment]
```
_, err := proto.Marshal(converted)
Expect(err).ToNot(HaveOccurred())
```
produces the panic above.
Founde [here](https://github.com/cloudfoundry/loggregator/blob/50a36338fdb501076ede5e37727482f4b978e675/plumbing/conversion/http_test.go#L78-L79) if more context needed.

**Comment by awalterschulze** [comment]
I was wondering if you could provide a small self contained example, that we can use in a test?

**Comment by johannasmith** [comment]
It turns out we switched over the `golang/protobuf` for our v2 and the tests were still trying to unmarshal with `gogo/protobuf/proto` in some places.

**Comment by awalterschulze** [comment]
May I ask why you switched to golang/protobuf?
Always good to understand where we have short comings.
