### ISSUE TITLE
The latest commits seem to broke up imports

### ISSUE THREAD

**Issue by antony66** [gogo/protobuf#430]
I've checked out the latest version today and it seem to generate wrong imports:

    import golang_org_x_net_context "golang.org/x/net/context"
    import google_golang_org_grpc "google.golang.org/grpc"

but the rest of autogenerated code uses old prefixes like:

    // Reference imports to suppress errors if they are not otherwise used.
    var _ context.Context
    var _ grpc.ClientConn

It can be seen even here: https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/testdata/grpc/grpc.pb.go#L10 vs https://github.com/gogo/protobuf/blob/master/protoc-gen-gogo/testdata/grpc/grpc.pb.go#L152

So I am unable to compile any old code. Am I doing anything wrong or is it a bug?

**Comment by awalterschulze** [comment]
A fix is in the works

https://github.com/gogo/protobuf/pull/429

**Comment by awalterschulze** [comment]
Could you check whether master fixes the problem?

**Comment by Proxeter** [comment]
@awalterschulze We had same problem and it works on master version now. Thank you!

**Comment by awalterschulze** [comment]
Thank you @jmarais

**Comment by antony66** [comment]
@awalterschulze yes it works now. Thank you!

**Comment by awalterschulze** [comment]
Thank you for reporting :)

**Comment by awalterschulze** [comment]
Release published https://github.com/gogo/protobuf/releases/tag/v1.1.1
