### ISSUE TITLE
Unmarshal allocates twice the memory needed for repeated fields

### ISSUE THREAD

**Issue by gunnihinn** [gogo/protobuf#436]
The generated code that deserializes a repeated field is essentially:

    xs := make([]type, 0)
    for _, x := range things {
        xs = append(xs, x)
    }

When the Go runtime needs to grow the backing array of a slice, it uses a doubling strategy to do so.  If we have _n_ elements to append to an empty slice, and _k_ is such that _2^k < n < 2^{k+1}_, then this means we usually end up allocating space for at least

    1 + 2 + 4 + ... + 2^{k+1} = 2 * 2^{k+1}

elements, while making a single allocation of _n_ elements would have been enough.

When we deserialize a protobuf message with a packed repeated field, we know how many elements we're going to deserialize and can allocate all the memory needed in one go. [Here](https://github.com/gunnihinn/protobuf-alloc) is a demonstration of a simple program that does this. Profiling its memory use with the default generated code, and also with a single ad-hoc patch that performs this allocation, shows that what we describe above really does happen.

I work for Booking.com, and we're very interested in making this deserialization code more clever about its allocations if possible and acceptable to the maintainers. We use this library in our implementation of a [Graphite server](https://github.com/go-graphite/carbonapi), and Unmarshal is responsible for the vast majority of its memory use (around 20 GB when things are calm), which is unsurprising as the server spends most of its time deserializing very large arrays of doubles.  Getting rid of this behaviour would cut our memory use by about half.

## Sample results from running the [above program](https://github.com/gunnihinn/protobuf-alloc):

```
## Commit 36a0ed7 (current behaviour):

$ ./protobuf-alloc
$ go tool pprof protobuf-alloc memory.prof
File: protobuf-alloc
Type: inuse_space
Time: Jul 24, 2018 at 12:01pm (CEST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top                                                                                                                                                                  
Showing nodes accounting for 5175.25MB, 100% of 5175.25MB total                                                                                                              
      flat  flat%   sum%        cum   cum%
 2871.24MB 55.48% 55.48%  2871.24MB 55.48%  github.com/gunnihinn/protobuf-alloc/foo.(*Foo).Unmarshal
    2048MB 39.57% 95.05%  5175.25MB   100%  main.main
  256.01MB  4.95%   100%   256.01MB  4.95%  github.com/gunnihinn/protobuf-alloc/foo.(*Foo).Marshal
         0     0%   100%  5175.25MB   100%  runtime.main

## Commit 97163c0 (with ad-hoc allocation patch):

$ ./protobuf-alloc
$ go tool pprof protobuf-alloc memory.prof                                                                                         
File: protobuf-alloc                                                                                                                                                         
Type: inuse_space
Time: Jul 24, 2018 at 12:03pm (CEST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top                                                                                                                                                                  
Showing nodes accounting for 2304.01MB, 100% of 2304.01MB total                                                                                                              
      flat  flat%   sum%        cum   cum%
    2048MB 88.89% 88.89%  2304.01MB   100%  main.main
  256.01MB 11.11%   100%   256.01MB 11.11%  github.com/gunnihinn/protobuf-alloc/foo.(*Foo).Marshal
         0     0%   100%  2304.01MB   100%  runtime.main
```

**Comment by awalterschulze** [comment]
Can you please show the original generated code that sets the slice cap to
zero? I can't find it in your example?

**Comment by gunnihinn** [comment]
I'm sorry, I was not precise. The generated code doesn't perform any explicit allocations, it just works with what it's given. When we write something like
```
f := &foo.Foo{}
f.Unmarshal(blob)
```
then the fields in `f` will have their default values, which in the case of slices have length zero. Thus, in effect, Unmarshal will behave as in the first code block in the issue report.

You could say that the users have enough information to figure out how much space they'll need for repeated fields by the time they have both the byte blob and the protobuf definition, and should setup the struct they're going to unmarhal into accordingly. If that's the recommended use of the library, we'll follow that. However, it seems likely that most people are using the library like we are, and in that case we _could_ check if they've initialized their repeated fields, and do it for them it not. Most of them might not care, but a few people, like us, will end up caring a lot.

We're happy to write the patches to do this and take them through your review process. We just want to make sure this is something you'd want in the first place before doing it. :)

**Comment by awalterschulze** [comment]
Cool. Yes I think this optimization can work for packed repeated fields,
which includes proto3 native fields.

If you want to contribute a patch that would be great 😀

**Comment by gunnihinn** [comment]
Cool. We'll try to get something to you in the next week or two.

**Comment by tomwilkie** [comment]
I'm thinking about a similar optimisation - but for nested fields.  Our proto is basically:

```
message WriteRequest {
  repeated TimeSeries timeseries = 1 [(gogoproto.nullable) = false];
}

message TimeSeries {
  repeated LabelPair labels = 1 [(gogoproto.nullable) = false];
  // Sorted by time, oldest sample first.
  repeated Sample samples   = 2 [(gogoproto.nullable) = false];
}

message LabelPair {
  bytes name  = 1 [(gogoproto.customtype) = "github.com/weaveworks/cortex/pkg/util/wire.Bytes", (gogoproto.nullable) = false];
  bytes value = 2 [(gogoproto.customtype) = "github.com/weaveworks/cortex/pkg/util/wire.Bytes", (gogoproto.nullable) = false];
}

message Sample {
  double value       = 1;
  int64 timestamp_ms = 2;
}
```

Some 30% of the allocations tend to be when unmarshalling `samples` and `labels`, and we tend to know how big these array will be (~100 samples and ~10 labels).  I wonder if we could provide this number in an extension/gadget/annotation (not sure the right term)?

**Comment by gunnihinn** [comment]
Not a maintainer, just a random dude, but if you know in advance how many things live in the slices you're going to deserialize, I think you can allocate space for them in the struct you deserialize them into before calling Unmarshal:
```
wr := &WriteRequest{
    timeseries: TimeSeries{
        labels: make([]LabelPair, 0, n),
        samples: make([]Sample, 0, m),
    },
}
wr.Unmarshal()
```
From over here, your case seems a bit different than the one we're working on (I got two junior developers at work interested in treating the case of packed varints this morning). When dealing with packed fields, we know how many of the next bytes in the stream are relevant to the repeated field, and can decide based on that whether to try to count how many elements they correspond to. We don't have that byte count for non-packed fields, so it seems less obvious whether to scan ahead to try to count elements or not. We're going to err on the side of not in our PRs.

If we're able to handle the case of varints on our end, and get that PR and [the one](https://github.com/gogo/protobuf/pull/437) that treats packed fixed-length types merged, then you could profit from that by changing the protobuf definition to
```
message TimeSeries {
  repeated LabelPair labels = 1;
  //repeated Sample samples  = 2;
  repeated Values double = 3;
  repeated TimestampsMs int64 = 4;
}
```
so Values and TimestampsMs would be packed primitives.

If that doesn't seem right to you, maybe your problem would get more attention from the maintainers in its own issue?

**Comment by tomwilkie** [comment]
>  I think you can allocate space for them in the struct you deserialize them into before calling Unmarshal

Thanks for the response!  I tried that - but these are nested `repeated` fields.  The `Unmarshal` code puts an empty `TimeSeries` in the `[]TimeSeries`, wiping any chance I have to preallocated `Labels` and `Samples`.

> changing the protobuf definition

I wish I could!  But this is a external API, so its pretty hard to go through such a change.

**Comment by tomwilkie** [comment]
I did it in an even more hacked up way (with a custom type): https://github.com/grafana/cortex/commit/ef1728b7dd271430ed54bbae9bda358b86a6bcc9#diff-8ddb008bd1159258872969a8f392d3d7L27

**Comment by awalterschulze** [comment]
@tomwilkie I am struggling to decide whether that is a hack of just the correct solution.

**Comment by awalterschulze** [comment]
I think we can close this issue as the pull request has been merged, or do you think there is more we can do here?

**Comment by tomwilkie** [comment]
Yeah my comments should be a separate issue ideally.

**Comment by gunnihinn** [comment]
> I think we can close this issue as the pull request has been merged, or do you think there is more we can do here?

I still think it's worth it to do the same for packed fields of varints. I managed to interest some junior developers over here that this was a nice project. We're having a look together, but I don't have a deadline for when their patches will be ready. I'll see to that it gets picked up one way or the other, so you can close the issue if you want to.

**Comment by awalterschulze** [comment]
Ok cool, then lets keep the issue open :)
