### ISSUE TITLE
Default empty value cause problem in JS

### ISSUE THREAD

**Issue by silentred** [gogo/protobuf#442]
pb file:
```
message EchoRequest {
  string name = 1;
  Group group = 2;
}

enum Group {
  A = 0;
  B = 1;
}
```
When the group value is set to A, the result of Marshal() ignores the group. This is fine in Go, but not in javascript. The group value comes out 'undefined' in JS. 

example:
```
req = EchoRequest{Name: "peter", Group: GroupA}

actual result:
0a057065746572

expect result:
0a0570657465721000
```

Is there an option that can switch the feature on or off?

**Comment by awalterschulze** [comment]
I assume this also happens with golang/protobuf, since this simply not marshaling the default value which is following the proto3 specification.
I think this is a problem in the javascript unmarshaling?

**Comment by silentred** [comment]
@awalterschulze thanks. Changing version to proto2 returns the expected result. It seems the JS lib does not completely follow the proto3 specification. I will close this issue.
