### ISSUE TITLE
Size method panic   when rpc method panic !

### ISSUE THREAD

**Issue by myonlyzzy** [gogo/protobuf#444]
when  rpc method panic  I can recover panic in method defer func.but because the response point is nil ,so Size method panic . like this:

`func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
	defer func() {
		if r := recover(); r != nil {
			log.Println(string(debug.Stack()))
		}
	}()
	panic("test")
	return &pb.HelloReply{}, nil
}

func main() {
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	s := grpc.NewServer()
	pb.RegisterGreeterServer(s, &server{})
	// Register reflection service on gRPC server.
	reflection.Register(s)
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}`

stack debug

goroutine 35 [running]:
github.com/myonlyzzy/go-exmaple/examples/helloworld/helloworld.(*HelloReply).Size(0x0, 0xc4202237d8)
	/Users/myonlyzzy/go/src/github.com/myonlyzzy/go-exmaple/examples/helloworld/helloworld/helloworld.pb.go:317 +0x22
github.com/myonlyzzy/go-exmaple/examples/helloworld/helloworld.(*HelloReply).Marshal(0x0, 0x14cf540, 0x0, 0x1e60048, 0x0, 0xd79573501)
	/Users/myonlyzzy/go/src/github.com/myonlyzzy/go-exmaple/examples/helloworld/helloworld/helloworld.pb.go:219 +0x2f
google.golang.org/grpc/encoding/proto.codec.Marshal(0x14cf540, 0x0, 0x0, 0xc420223908, 0x100ed6d, 0xc420010000, 0x148c760)
	/Users/myonlyzzy/go/src/google.golang.org/grpc/encoding/proto/proto.go:70 +0x19e
google.golang.org/grpc.encode(0x1e60000, 0x1812e10, 0x14cf540, 0x0, 0x1812e10, 0xc4201cc968, 0xc420210050, 0xc420210030, 0xc4201ac4a8)
	/Users/myonlyzzy/go/src/google.golang.org/grpc/rpc_util.go:487 +0x61
google.golang.org/grpc.(*Server).sendResponse(0xc420182380, 0x1581520, 0xc4200f0200, 0xc4201e8000, 0x14cf540, 0x0, 0x0, 0x0, 0xc42020c048, 0x0, ...)
	/Users/myonlyzzy/go/src/google.golang.org/grpc/server.go:830 +0x89
google.golang.org/grpc.(*Server).processUnaryRPC(0xc420182380, 0x1581520, 0xc4200f0200, 0xc4201e8000, 0xc4201842d0, 0x17e31d0, 0x0, 0x0, 0x0)
	/Users/myonlyzzy/go/src/google.golang.org/grpc/server.go:1035 +0x5df
google.golang.org/grpc.(*Server).handleStream(0xc420182380, 0x1581520, 0xc4200f0200, 0xc4201e8000, 0x0)
	/Users/myonlyzzy/go/src/google.golang.org/grpc/server.go:1248 +0x1318
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42009a640, 0xc420182380, 0x1581520, 0xc4200f0200, 0xc4201e8000)
	/Users/myonlyzzy/go/src/google.golang.org/grpc/server.go:680 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/myonlyzzy/go/src/google.golang.org/grpc/server.go:678 +0xa1

**the line 317** 
func (m *HelloReply) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovHelloworld(uint64(l))
	}
	return n
}

len(m.Name) panic because m is nil.

how to  solve this problem?

**Comment by awalterschulze** [comment]
O wow, can you provide the proto file and generating command?

**Comment by myonlyzzy** [comment]
ok.

$ protoc --version
libprotoc 3.5.1

**proto file**
`syntax = "proto3";

package helloworld;

import "gogoproto/gogo.proto";

option java_multiple_files = true;
option java_package = "io.grpc.examples.helloworld";
option java_outer_classname = "HelloWorldProto";
option (gogoproto.marshaler_all) = true;
// Enable custom Unmarshal method.
option (gogoproto.unmarshaler_all) = true;
// Enable custom Size method (Required by Marshal and Unmarshal).
//option (gogoproto.sizer_all) = false;


// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string name=1;
}
message header {
  string message=1;
  int64  age=2;

}

message Basic{
  string name=1;
}`

**generating command.**

protoc -I.:`echo $GOPATH/src/github.com/gogo/protobuf`:`echo $GOPATH/src/github.com/gogo/protobuf/protobuf`  --go_out=plugins=grpc:. ./helloworld/helloworld.proto

**Comment by myonlyzzy** [comment]
I think the reason is not proto file and generating command , the reason is  the response point is nil because a grpc method panic .  but Size method  use this nil point .

**Comment by awalterschulze** [comment]
Shouldn't it be `gogo_out` rather than `go_out` ?

With proto3 it is impossible for `m.Name` to be nil, except if `m` is nil.
And then I have to ask, why are you trying to Marshal nil messages?

**Comment by myonlyzzy** [comment]
sorry I copy  wrong .command is protoc -I.:`echo $GOPATH/src/github.com/gogo/protobuf`:`echo $GOPATH/src/github.com/gogo/protobuf/protobuf`  --gogo_out=plugins=grpc:. ./helloworld/helloworld.proto 。

the Marshal method is generator by gogast plugin .  the m is nil reason is in say method panic (panic("test")). but grpc server also sendresponse to client . the sendrespone method call . the detail  you can see debug stack.   I only modify grpc example hellowrold ,add panic("test). don't 
change other .

**Comment by awalterschulze** [comment]
Ok wait, I think I get it now, you are saying, since panic(test) is executed, then the defer executes, which recovers the panic, but it is the end of the method, which means that `SayHello` returns with `nil, nil` and then `m` is nil and then we get the panic in `Size`.

So to fix 
```go
func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (out *pb.HelloReply, err error) {
   out = &pb.HelloReply{}
   defer func() {
       if r := recover(); r != nil {
           log.Println(string(debug.Stack()))
       }
    }()
    panic("test")
    return
}
```

Or what did you have in mind?

**Comment by myonlyzzy** [comment]
yes , that's my mean.but  the  solution you provide is one way to solve that. But I think Size method need   like  Get method  add if m!=nil.
func (m *Basic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

**Comment by awalterschulze** [comment]
@donaldgraham @jmarais 
What do you think of updating the generation of the Size method from

```go
func (m *HelloReply) Size() (n int) {
    var l int
    _ = l
    l = len(m.Name)
    if l > 0 {
        n += 1 + l + sovHelloworld(uint64(l))
    }
    return n
}
```

to

```go
func (m *HelloReply) Size() (n int) {
    if m == nil {
        return 0
    }
    var l int
    _ = l
    l = len(m.Name)
    if l > 0 {
        n += 1 + l + sovHelloworld(uint64(l))
    }
    return n
}
```

I don't think there should be any negative implications, but maybe you can think of something I am missing?

**Comment by jmarais** [comment]
@awalterschulze  I think its a good suggestion. I will take a look if I can find any other implications regarding this change.

**Comment by awalterschulze** [comment]
Best way is to try and implement it and run the tests :)
