### ISSUE TITLE
Which is the license of this repo?

### ISSUE THREAD

**Issue by wu-sheng** [gogo/protobuf#450]
Hi, I just read the LICENSE file: https://github.com/gogo/protobuf/blob/master/LICENSE

But it doesn't say which license it is. It looks like the BSD-3 license, is it? Or some license else?

**Comment by wu-sheng** [comment]
I need to use some protos in the [Apache SkyWalking](https://github.com/apache/incubator-skywalking). So I must make sure the license is safe. Thanks.

**Comment by donaldgraham** [comment]
The license is the 3-clause license ("BSD License 2.0", "Revised BSD License", "New BSD License", or "Modified BSD License"), as you guessed.

**Comment by donaldgraham** [comment]
Thanks for bringing this to our attention.  We'll add the license type to the README.

Would you mind if we add your project to our list of users in our README?  It looks very useful...

**Comment by wu-sheng** [comment]
@donaldgraham PR sent.

**Comment by donaldgraham** [comment]
Thanks so much!
