### ISSUE TITLE
Error generating test/issue449/issue449.proto

### ISSUE THREAD

**Issue by jmarais** [gogo/protobuf#460]
I get this error when regenerating master for issue449.proto:
```
issue449.proto: Import "github.com/gogo/protobuf/gogoproto/gogo.proto" was not found or had errors.
panic: exit status 1
```

It seems like the makefile depends on your ```GOPATH``` env variable:

```
	protoc-min-version --version="3.0.0" \
	--proto_path=.:$(GOPATH)/src/ \
	--gogo_out=. issue449.proto
```

We could replace the ```GOPATH``` with the same path declaration as in the other tests

**Comment by jmarais** [comment]
Closed with pull request #461

**Comment by awalterschulze** [comment]
I am on the fence, but I am easily swayed either way.

**Comment by jmarais** [comment]
Keeping the original proto_path and adding:

```
$(GOPATH)/src/github.com/gogo/protobuf/protobuf/
```
Works in my development env. 
Now I am a bit unsure why this worked without adding this last statement in the path?

**Comment by jmarais** [comment]
I tried to look for an answer in the travis logs, but didn't find any. I also executed the travis commands in my environment but I still get a regeneration error. @awalterschulze can you regenerate issue449.proto on commit:
```
e6483bbb475dab67b82694c39bcd807197be1e0e
```
in you environment?

**Comment by awalterschulze** [comment]
When I checkout the commit and run make in the root, it works, no errors.

**Comment by awalterschulze** [comment]
```
~/code/src/github.com/gogo/protobuf ((e6483bb...))$ echo $GOPATH
/Users/waschulze/code
```

**Comment by awalterschulze** [comment]
Your GOPATH sounds right to me :)

**Comment by jmarais** [comment]
Do you have a link in from ```$GOPATH/src/google``` to a directory which could contain the  ```google/protobuf/descriptor.proto``` ?

**Comment by jmarais** [comment]
Ok. Then I am stumped.
The last thing I tried was:
```
mkdir testproto
cd testproto/
export GOPATH=/home/jacques/Development/testproto
export GOBIN=$GOPATH/bin
export PATH=$GOBIN:$PATH

go get github.com/gogo/protobuf
cd src/github.com/gogo/protobuf/
git checkout e6483bbb475dab67b82694c39bcd807197be1e0e
make
```
And I still get the error:
```
make[1]: Entering directory `/home/jacques/Development/testproto/src/github.com/gogo/protobuf/test/issue449'
go install github.com/gogo/protobuf/protoc-gen-gogo
go install github.com/gogo/protobuf/protoc-min-version
protoc-min-version --version="3.0.0" \
--proto_path=.:/home/jacques/Development/testproto/src/ \
--gogo_out=. issue449.proto
google/protobuf/descriptor.proto: File not found.
...
...
issue449.proto: Import "github.com/gogo/protobuf/gogoproto/gogo.proto" was not found or had errors.
panic: exit status 1
```

```
$ go version
go version go1.10 linux/amd64
$ protoc --version
libprotoc 3.5.1
```

**Comment by awalterschulze** [comment]
Could you try a git clone rather than a go get ?

**Comment by jmarais** [comment]
ok. So I executed the following:

```
mkdir testproto2
cd testproto2/
mkdir -p src/github.com/gogo/
cd src/github.com/gogo/
git clone https://github.com/gogo/protobuf.git
cd protobuf

export GOPATH=/home/jacques/Development/testproto2
export GOBIN=$GOPATH/bin
export PATH=$GOBIN:$PATH

git checkout e6483bbb475dab67b82694c39bcd807197be1e0e
make
```
And I get the same error.

```
make[1]: Entering directory `/home/jacques/Development/testproto2/src/github.com/gogo/protobuf/test/issue449'
go install github.com/gogo/protobuf/protoc-gen-gogo
go install github.com/gogo/protobuf/protoc-min-version
protoc-min-version --version="3.0.0" \
--proto_path=.:/home/jacques/Development/testproto2/src/ \
--gogo_out=. issue449.proto
google/protobuf/descriptor.proto: File not found.
```

**Comment by awalterschulze** [comment]
Is it ok if we say that your fix, fixes this?

**Comment by jmarais** [comment]
So now I am not sure what I fixed? It worked fine on travis:
https://travis-ci.org/gogo/protobuf/builds/414403268?utm_source=github_status&utm_medium=notification

So I am just including the ```<projectroot>/protobuf``` directory in the protopath, and this works in my environment.

**Comment by awalterschulze** [comment]
We had this problem once before and I really don't know, if you can figure it out that would be amazing.

I just end up playing with the paths until it works on travis and every reported environment.
And it seems like master now works on your environment and travis, so all should be good, right?

You are just trying to figure out what was wrong before?

**Comment by jmarais** [comment]
> You are just trying to figure out what was wrong before?
Yeh

**Comment by awalterschulze** [comment]
Sorry, but now that is a really tough one :)

**Comment by jmarais** [comment]
> I  am on the fence, but I am easily swayed either way.

So I can assume you have been swayed?

**Comment by awalterschulze** [comment]
yes :) whatever works :)
