### ISSUE TITLE
[help wanted] Why adding some XXX_ field to Timestamp pb?

### ISSUE THREAD

**Issue by JulienBreux** [gogo/protobuf#462]
My problem is simple,

I use MongoDB with a simple `Insert(interface{})`.

But now, it's not really cool :(

https://github.com/gogo/protobuf/blob/master/types/timestamp.pb.go#L118-L120
```
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
```

Need this to do without over-compute... (Marshal / Unmarshal / etc)
```
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
```

Do you have an opinion?

**Comment by donaldgraham** [comment]
@jmarais, you've done some thinking about bson.  Can you comment on this?

**Comment by donaldgraham** [comment]
@JulienBreux, please could you take a look at #467 - "options to not generate xxx fields", and the associated PR (#467).  I think this may solve your problem.  Please let us know if it does.

**Comment by JulienBreux** [comment]
Yes, cool!
