### ISSUE TITLE
fixing letmegrpc

### ISSUE THREAD

**Issue by awalterschulze** [gogo/protobuf#471]
letmegrpc is currently broken

It uses `p.RecordTypeUse(m.GetInputType())` , which blows up in generator.go here

`g.usedPackages[obj.GoImportPath()] = true`, since the usedPackages map has not been initialized.

Could I ask that we make the following change?

```
diff --git a/protoc-gen-gogo/generator/helper.go b/protoc-gen-gogo/generator/helper.go
index 3c7cf84..8104f06 100644
--- a/protoc-gen-gogo/generator/helper.go
+++ b/protoc-gen-gogo/generator/helper.go
@@ -339,8 +339,15 @@ func (g *Generator) GeneratePlugin(p Plugin) {
        }
 }

+func (g *Generator) SetFile(filename string) {
+       g.file = g.fileByName(filename)
+}
+
 func (g *Generator) generatePlugin(file *FileDescriptor, p Plugin) {
        g.writtenImports = make(map[string]bool)
+       g.usedPackages = make(map[GoImportPath]bool)
+       g.packageNames = make(map[GoImportPath]GoPackageName)
+       g.usedPackageNames = make(map[GoPackageName]bool)
        g.file = file

        // Run the plugins before the imports so we know which imports are necessary.
```

The SetFile method was removed during the upgrade to v1.1, here I propose we add it back, which allows me to fix a test in letmegrpc, used to demonstrate creation of custom forms.
So it is not just a test, it is how it is being used.

**Comment by awalterschulze** [comment]
No I think it just happened by accident while merging in the huge number of changes made by golang/protobuf.  I must have thought that it is not being used, since the method is not used anywhere inside gogoprotobuf.

**Comment by jmarais** [comment]
Ah ok. Thanks

**Comment by awalterschulze** [comment]
Thanks for merging
