### ISSUE TITLE
Compiler ignore the `faster` or `slick` and fallback to regular gogo compiler

### ISSUE THREAD

**Issue by AlmogBaku** [gogo/protobuf#482]
After upgrading the version to master a few hours ago(via `go get -u`), I suddenly cannot compile using the faster or slick compiler, and the generated code still contains `XXX_` functions:

```protoc -I=. -I=$GOPATH/src --gogoslick_out=plugins=grpc:. *.proto```

**Comment by jmarais** [comment]
>  I suddenly cannot compile using the faster or slick compiler

What is the error you are receiving?

Which protobuf compiler version are you using?

**Comment by AlmogBaku** [comment]
No error, it just uses the `gogo_out` instead of the slick/faster.

protobuf version `libprotoc 3.6.0`

**Comment by jmarais** [comment]
> generated code still contains XXX_ functions

So the XXX_ functions won't go away. They were added by ```golang/protobuf```` as part of one of their reworks. You are able to disable the XXX_ fields using the options:
```(gogoproto.goproto_unrecognized) = false```
```(gogoproto.goproto_unkeyed) = false```
```(gogoproto.goproto_sizecache) = false```

What problem are you experiencing compiling with ```gogoslick``` or ```gogofaster``` ?
