### ISSUE TITLE
Please clean this repo if possible

### ISSUE THREAD

**Issue by smcduck** [gogo/protobuf#500]
.git folder size is too big, go get will cost too much time. Thanks.

**Comment by bretep** [comment]
```
$ time go get github.com/gogo/protobuf/protoc-gen-gofast
go get github.com/gogo/protobuf/protoc-gen-gofast  8.26s user 1.45s system 289% cpu 3.357 total
```

You can setup a GoGetProxy and cache in a local environment (dev, build, etc...). https://github.com/golang/go/wiki/GoGetProxyConfig

Long term, this is probably the best way to go. It's not scalable to ask every package maintainer to clean up their repo if possible.

**Comment by donaldgraham** [comment]
Thanks, @bretep.  @smcduck, are you happy with that solution?
