### ISSUE TITLE
how to use gogoprotobuf in "net/rpc"

### ISSUE THREAD

**Issue by thinkboy** [gogo/protobuf#53]
hi~
    how to use gogoprotobuf in golang standard pkg "net/rpc" and instead of its "gob". 
    i have tried to implement “gobServerCodec” and "ServerCodec interface", but seems no Decode() or Encode() method. so is there anyway to use "gogoprotobuf" instead of "gob".

**Comment by awalterschulze** [comment]
cockroachdb seems to have managed
https://github.com/cockroachdb/cockroach/blob/master/rpc/codec/client.go
https://github.com/cockroachdb/cockroach/blob/master/rpc/codec/server.go
I would also look at http://golang.org/pkg/net/rpc/jsonrpc/ for an example of how to implement a net/rpc codec.
I hope this helped?
