### ISSUE TITLE
EncodeFixed32() checks if input overflows uint64 instead of uint32

### ISSUE THREAD

**Issue by jonathangold** [gogo/protobuf#536]
When encoding a `fixed32` that's larger than the max value of `uint32`, `EncodeFixed32()` doesn't return an error. 

When the resulting value is decoded, it does not match the encoded value, since there aren't enough bytes to represent it.

I'd expect the function to return an error if the input overflows uint32 rather than uint64

To reproduce:
```
package main

import (
	"fmt"
	"github.com/gogo/protobuf/proto"
)

func main() {
	b := proto.NewBuffer([]byte{})
	if err := b.EncodeFixed32(9999999999999999999); err != nil {
		panic("whoops")
	}
	fmt.Printf("%v", b)
}
```

prints `&{[255 255 231 137] 0 [] [] [] [] [] [] []}` which decodes to `2313682943` not `9999999999999999999`

If I add another 9 to the input, making it larger than uint64 allows, it errors.

```
package main

import (
	"fmt"
	"github.com/gogo/protobuf/proto"
)

func main() {
	b := proto.NewBuffer([]byte{})
	if err := b.EncodeFixed32(99999999999999999999); err != nil {
		panic("whoops")
	}
	fmt.Printf("%v", b)
}
```

`./main.go:10:28: constant 99999999999999999999 overflows uint64`

**Comment by jmarais** [comment]
Hi. Thanks for reporting this. I made a quick test and this seems to also be the case in golang/protobuf:
https://github.com/golang/protobuf/blob/master/proto/encode.go#L141
The EncodeFixed32 method's parameter is a ```uint64```.
Could you report the issue there? So that I can merge in their fix.

**Comment by jonathangold** [comment]
https://github.com/golang/protobuf/pull/827

**Comment by jonathangold** [comment]
@jmarais The patch was rejected, since it could break existing (but undocumented) use cases. Feel free to reopen if you want to fix it in gogo/protobuf anyway, but I suspect you'd want to maintain compatibility.
