### ISSUE TITLE
Add ability to enable stdtime/stdduration with vanity

### ISSUE THREAD

**Issue by sgtsquiggs** [gogo/protobuf#538]
A custom generator using vanity (customized from gogo{fast,faster,slick}) covers 99% of my needs. It would be great if it were possible to enable stdtime/stdduration with vanity as well.

**Comment by jmarais** [comment]
Hey. Thanks for the question. I don't think I am going to add such a vanity at this moment, however it is easy to make one. I created an example here for you (I realize afterwards the branch is stdduration and the example is for stdtime):

https://github.com/jmarais/protobuf/tree/stddurationvanity/protoc-gen-gotime
with some test code:
https://github.com/jmarais/protobuf/tree/stddurationvanity/test/stdtime

You can add the:
[vanity.ForEachFieldInFiles(files, StdTimeStamp)](https://github.com/jmarais/protobuf/blob/stddurationvanity/protoc-gen-gotime/main.go#L45)
to an existing vanity, or you can create your own one with your custom options.

**Comment by sgtsquiggs** [comment]
The stdtimestamp and stdduration options add the timestamp/duration as a pointer; is there a way to combine stdtimestamp and stdduration with `TurnOffNullableForNativeTypesWithoutDefaultsOnly` ?

**Comment by sgtsquiggs** [comment]
Immediately figured it out :laughing: 

```go
func StdDuration(field *descriptor.FieldDescriptorProto) {
	if field.IsRepeated() {
		return
	}
	if !field.IsMessage() {
		return
	}
	if !strings.Contains(*field.TypeName, "google.protobuf.Duration") {
		return
	}
	vanity.SetBoolFieldOption(gogoproto.E_Stdduration, true)(field)
	vanity.SetBoolFieldOption(gogoproto.E_Nullable, false)(field)
}
```

**Comment by jmarais** [comment]
Nice.
