### ISSUE TITLE
Text format fails to decode oneof

### ISSUE THREAD

**Issue by speezepearson** [gogo/protobuf#547]
`UnmarshalText` fails to deserialize the output of `MarshalTextString` in some circumstances. I believe it's caused by interaction with `oneof`: I've experimented a little, and I can't get text-deserialization to work with `oneof`, and I can't get it to fail without.

The message definition (`goroot/src/protoparse/protos/retry.proto`):
```protobuf
syntax = "proto3";

message RetryConfig {
	oneof backoff {
		uint32 constant_millis = 1;
		float exponential_growth_factor = 2;
	}
}
```

The code that reveals the failure (`goroot/src/protoparse/main.go`):
```go
package main

import (
	"fmt"
	gogo "github.com/gogo/protobuf/proto"
	"protoparse/protos"
)

var CONFIG = retry.RetryConfig{
	Backoff: &retry.RetryConfig_ExponentialGrowthFactor{2},
}

func main() {
	err := gogo.UnmarshalText(gogo.MarshalTextString(&CONFIG), &retry.RetryConfig{})
	fmt.Println("unmarshaling error:", err)
}
```

The error:
```
~/G/s/protoparse $ go run main.go
unmarshaling error: line 1.0: unknown field name "exponential_growth_factor" in retry.RetryConfig
```

Or perhaps I'm doing something wrong, in which case, sorry to throw noise at you!

**Comment by speezepearson** [comment]
More information:
- I generate the protos with `protoc -I="$HOME/Go/src" -I="$HOME/Go/src/github.com/gogo/protobuf" -I=protos/ --gofast_out=protos/ protos/retry.proto`
- Code that compares results with `golang/protobuf`, demonstrating that (a) `golang/protobuf` does not experience the same error, and (b) the error is specifically with the _un_-marshaling step:

    ```
    package main
    
    import (
    	"fmt"
    	golang "github.com/golang/protobuf/proto"
    	gogo "github.com/gogo/protobuf/proto"
    	"protoparse/protos"
    )
    
    var CONFIG = retry.RetryConfig{
    	Backoff: &retry.RetryConfig_ExponentialGrowthFactor{2},
    }
    
    func main() {
    	marshaled := gogo.MarshalTextString(&CONFIG)
    	gogoMarshaled := gogo.MarshalTextString(&CONFIG)
    
    	if gogoMarshaled != marshaled {
    		panic("Different marshaled values!?");
    	}
    
    	err := golang.UnmarshalText(marshaled, &retry.RetryConfig{})
    	fmt.Println("unmarshaling error for golang:", err)
    	err = gogo.UnmarshalText(marshaled, &retry.RetryConfig{})
    	fmt.Println("unmarshaling error for gogo:", err)
    }
    ```

**Comment by jmarais** [comment]
Hey. Thanks for the information.
Yes with your protoc generation option:
```bash
--gofast_out
```
You cannot use ```"github.com/gogo/protobuf/proto"``` to try and unmarshal the message as the generated code in the ```*.pb.go``` will import and register the types in the ```"github.com/golang/protobuf/proto"``` package.

If you only want to depend on ```gogo/protobuf``` you can use the:
```bash
--gogofast_out
```
vanity binary.

However, currently with you using the text-marshaling you are not using the generated gogo marshal and unmarshal functions.

**Comment by speezepearson** [comment]
Aha, I see! User error, then. Thanks for your help!
