### ISSUE TITLE
Feature: allow repeated embed field

### ISSUE THREAD

**Issue by TennyZhuang** [gogo/protobuf#553]
```proto
message A {}

message B {
  repeated A as = 1 [(gogoproto.embed) = true]
}
```

and generate

```go
type B struct {
  As []A
}
```

instead of

```go
type B struct {
  As []*A
}
```

**Comment by jmarais** [comment]
I don't think you can generate ```repeated``` fields while using the ```embed``` feature.
You should get the message:
```ERROR: found repeated embedded field Foo in message B```
I do not think you can even embed slices into structs if you look at the documentation:
https://golang.org/doc/effective_go.html#embedding
and this example:
https://play.golang.org/p/gUUc6O41IDf

Your example is using the ```gogoproto.embed``` feature but your generated example still have the fieldname ```As```

Can you clarify your feature a bit more?

**Comment by TennyZhuang** [comment]
sorry, this is a feature request, I need an embed slice to unify the
behavior, why this is        an error?

jmarais <notifications@github.com>于2019年3月7日 周四00:09写道：

**Comment by TennyZhuang** [comment]
Sorry for misunderstanding the meaning of embed, I just need a feature that convert the nested proto message to something like mongo “embed”, generate value type but without pointer.

**Comment by TennyZhuang** [comment]
Maybe I need some feature like [(gogoproto.ref) = false]

**Comment by jmarais** [comment]
I think I understand. So with a normal repeated use we generate this:
```protobuf
message Foo {
	repeated Bar one = 1;
}
message Bar {
	string two = 1;
}
```
```golang
type Foo struct {
	One    []*Bar
}
```
But you can use the ```gogoproto.nullable``` option like this:
```protobuf
message Foo {
	repeated Bar one = 1 [(gogoproto.nullable) = false];
}
message Bar {
	string two = 1;
}
```
to generate a struct like:
```golang
type Foo struct {
	One    []Bar
}
```

Will that solve your problem?

**Comment by TennyZhuang** [comment]
It exactly solved my problem! Thank you
