### ISSUE TITLE
Extending descriptor.FieldOptions

### ISSUE THREAD

**Issue by sjames-iberis** [gogo/protobuf#590]
Is this a bug or am I doing something wrong?

I am compiling the following definition:
```
syntax = "proto2";
option go_package = "gogoissue/proto";

import "google/protobuf/descriptor.proto";
 
extend google.protobuf.FieldOptions {
    optional MyFieldOptions my_options = 1024;
}
 
message MyFieldOptions {
    optional bool is_key             = 1;
}
 
message MyMessage {
    required string system_id        = 1 [(my_options).is_key = true];
}
```
with the command:
```
protoc -I . --gogofast_out=plugins=grpc:../.. *proto
```
The generated go source imports the descriptor package from:
```
"github.com/golang/protobuf/protoc-gen-go/descriptor"
```
So, consequently I am not able to use the generated E_MyOptions extension descriptor.
I have to define my own copy of it, referencing the gogo descriptor package.
Running the following go:
```
package main

import myproto "gogoissue/proto"
import "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
import "fmt"
import "github.com/gogo/protobuf/proto"

var E_MyOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*myproto.MyFieldOptions)(nil),
	Field:         1024,
	Name:          "my_options",
	Tag:           "bytes,1024,opt,name=my_options",
	Filename:      "issue.proto",
}

func main() {

	msg := &myproto.MyMessage{}

	fd, _ := descriptor.ForMessage(msg)
	for _, ex := range fd.MessageType {
		for _, fl := range ex.GetField() {
			opts := fl.GetOptions()
			if opts != nil {
				myopts, err := proto.GetExtension(opts, myproto.E_MyOptions)
				fmt.Println("OPTS:", myopts, err)
				myopts, err = proto.GetExtension(opts, E_MyOptions)
				fmt.Println("OPTS:", myopts, err)
			}
		}
	}
}
```
produces:
```
OPTS: <nil> proto: bad extended type; *descriptor.FieldOptions does not extend *descriptor.FieldOptions
OPTS: is_key:true  <nil>
```

**Comment by jmarais** [comment]
> protoc -I . --gogofast_out=plugins=grpc:../.. *proto

I think your generated file could import the wrong protobuf/descriptor.
Just check that it is importing:
"github.com/**gogo**/protobuf/protoc-gen-gogo/descriptor"
and not:
"github.com/**golang**/protobuf/protoc-gen-go/descriptor"

I think you need to change your command to:

> --gogofast_out=Mgoogle/protobuf/descriptor.proto=github.com/gogo/protobuf/protoc-gen-gogo/descriptor,plugins=grpc:.

In order to tell the generator to remap the:
```import "google/protobuf/descriptor.proto";```
import in your .proto file.

**Comment by sjames-iberis** [comment]
I confirm that with the mapping option on the command line, the generated code now includes the gogo descriptor package.

Thanks.
