### ISSUE TITLE
How to fix this dep break?

### ISSUE THREAD

**Issue by hyacinthus** [gogo/protobuf#591]
Not long ago, I can't update my go mod any more.

go get -u

go: finding github.com/gogo/protobuf v0.0.0-00010101000000-000000000000
go: github.com/gogo/protobuf@v0.0.0-00010101000000-000000000000: unknown revision 000000000000

Many packages depend on this package, I can't find who's problem...

**Comment by greblin** [comment]
I have the same problem
I found such file: https://github.com/istio/gogo-genproto/blob/master/go.mod. It was commited 7 hours ago, and it looks like the cause of the problem. But I don't use istio/gogo-genproto in my project and can't understand which dependency uses it

**Comment by greblin** [comment]
I have temporary solution: write in your project go.mod
`
replace github.com/gogo/protobuf v0.0.0-00010101000000-000000000000 => github.com/istio/gogo-protobuf v1.2.2-0.20190726125433-4c9abdb3090c
`

**Comment by hyacinthus** [comment]
@greblin thank you, so many libs use this package. Perhaps we should to post a issue in istio.

**Comment by hyacinthus** [comment]
Oh, you've posted it.

**Comment by hyacinthus** [comment]
Fixed.
