### ISSUE TITLE
gRPC plugin does not work

### ISSUE THREAD

**Issue by tegk** [gogo/protobuf#610]
I want use the gRPC plugin but the codes does not generated, just the proto related code.

I am using this command which generates without any warning the example.pb.go but without the code related to gRPC.

`protoc -I=. -I=$GOPATH/src -I=$GOPATH/src/github.com/gogo/protobuf/protobuf --gogofaster_out=plugins=grpc:. example.proto
`

The protofile:
```
syntax = "proto3";

import "github.com/gogo/protobuf/gogoproto/gogo.proto";

option (gogoproto.marshaler_all) = true;
option (gogoproto.unmarshaler_all) = true;
option (gogoproto.sizer_all) = true;
option (gogoproto.populate_all) = true;
option (gogoproto.equal_all) = true;
option (gogoproto.testgen_all) = true;
option (gogoproto.benchgen_all) = true;

message PingRequest {
    string ping = 1;
}

message PingResponse {
    string pong = 1;
    string api_version = 2;
}

```

System: Ubuntu 19.04 x64
go version go1.12.9 linux/amd64

What could be the issue here?

**Comment by jmarais** [comment]
Hi. I think you are generating the correct code given your example proto file?
You do not have a grpc ```service``` defined in your example. So there are no ```grpc``` related code to generate.
You can add:
```protocol buffer
service PingPong {
  rpc Ping(PingRequest) returns (PingResponse);
}
```
This will generate the ```PingPong``` grpc client/server code.
