### ISSUE TITLE
Bug: json omitempty not set for repeated native type when nullable=false is set.

### ISSUE THREAD

**Issue by tamird** [gogo/protobuf#62]
https://github.com/gogo/protobuf/blob/master/plugin/defaultcheck/defaultcheck.go#L100 warns:
> WARNING: field NodeStatus.StoreIds is a repeated non-nullable native type, nullable=false has no effect

however, this is not true, because `nullable=false` does have an effect. Removing it:
```diff
diff --git a/proto/status.proto b/proto/status.proto
index d735e64..1465466 100644
--- a/proto/status.proto
+++ b/proto/status.proto
@@ -45,7 +45,7 @@ message StoreStatus {
 // node.
 message NodeStatus {
   optional NodeDescriptor desc = 1 [(gogoproto.nullable) = false];
-  repeated int32 store_ids = 2 [(gogoproto.nullable) = false, (gogoproto.customname) = "StoreIDs"];
+  repeated int32 store_ids = 2 [(gogoproto.customname) = "StoreIDs"];
   optional int32 range_count = 3 [(gogoproto.nullable) = false];
   optional int64 started_at = 4 [(gogoproto.nullable) = false];
   optional int64 updated_at = 5 [(gogoproto.nullable) = false];

```
causes:
```diff
diff --git a/proto/status.pb.go b/proto/status.pb.go
index 0947198..0468495 100644
--- a/proto/status.pb.go
+++ b/proto/status.pb.go
@@ -96,7 +96,7 @@ func (m *StoreStatus) GetAvailableRangeCount() int32 {
 // node.
 type NodeStatus struct {
 	Desc                 NodeDescriptor `protobuf:"bytes,1,opt,name=desc" json:"desc"`
-	StoreIDs             []int32        `protobuf:"varint,2,rep,name=store_ids" json:"store_ids"`
+	StoreIDs             []int32        `protobuf:"varint,2,rep,name=store_ids" json:"store_ids,omitempty"`
 	RangeCount           int32          `protobuf:"varint,3,opt,name=range_count" json:"range_count"`
 	StartedAt            int64          `protobuf:"varint,4,opt,name=started_at" json:"started_at"`
 	UpdatedAt            int64          `protobuf:"varint,5,opt,name=updated_at" json:"updated_at"`

```
Notice that JSON handling has changed - `StoreIDs` has become nullable in JSON.

**Comment by awalterschulze** [comment]
Hmmm good catch.
My opinion is that this was a bug in the original implementation of nullable=false.
I should make a fix that gives all repeated fields and omitempty tag.
What do you think?

**Comment by tamird** [comment]
I actually would like to _not_ have the omitempty tag, because that means the thing _is_ nullable.

**Comment by awalterschulze** [comment]
Yes thats true, its only for repeated fields though.
This is how protobuf sends them anyway.  It does not send a zero length list.
Are you sure this is what you really want and why?

**Comment by tamird** [comment]
Actually I don't feel so strongly

**Comment by awalterschulze** [comment]
Ok great :)
This is then something that should be fixed.

**Comment by awalterschulze** [comment]
This commit should fix this issue
https://github.com/gogo/protobuf/commit/5ba1012ef3868db1b9ff374280a558c1bfff39c3
