### ISSUE TITLE
Vote For New Feature: Yaml `nullable=false` should generate `yaml:"omitempty"`

### ISSUE THREAD

**Issue by tamird** [gogo/protobuf#63]
This is currently done for JSON, but not YAML.

**Comment by awalterschulze** [comment]
And what about bson and xml and all the other serialization formats.
I think this is what gogoproto.moretags is for.
We could add a vanity binary that supports yaml, but adding moretags by convention.
What do you think?

**Comment by tamird** [comment]
I'd be 100% happy with a vanity function :)

**Comment by awalterschulze** [comment]
Can we close this, or is anyone interested enough to do some work here?

**Comment by tamird** [comment]
The JSON tag doesn't really matter - folks should be using jsonpb.
