### ISSUE TITLE
casttype doesn't handle nullable []byte correctly

### ISSUE THREAD

**Issue by tamird** [gogo/protobuf#64]
In proto2 syntax:
```proto
message RangeTreeNode {
  optional bytes left_key = 4 [(gogoproto.casttype) = "Key"];
}
```
In the generated code, LeftKey should be a pointer (because this thing is nullable) but it is not. Even the more explicit:
```proto
message RangeTreeNode {
  optional bytes left_key = 4 [(gogoproto.nullable) = true, (gogoproto.casttype) = "Key"];
}
```
yields a value type rather than a pointer.

**Comment by awalterschulze** [comment]
This you can only do with customtype.
casttype assumes that the generated code without casttype is castable to the casttype.
bytes does not generate *[]byte, but generates []byte, so it is not castable to *Key
