### ISSUE TITLE
Vote For New Feature: vanity: oneof should generate code using union

### ISSUE THREAD

**Issue by tamird** [gogo/protobuf#66]
Currently oneof is translated exactly into a list of optionals, unless `option (gogoproto.onlyone) = true;` is specified. `option (gogoproto.onlyone) = true;` should be the default for `oneof`.

**Comment by awalterschulze** [comment]
The generated code should be as close to golang/protobuf as possible.
Maybe this is also a case for another vanity function.
What do you think?

**Comment by tamird** [comment]
Yeah, a vanity function sounds good to me.

**Comment by awalterschulze** [comment]
I think the new golang/protobuf oneof implementation is much better than my onlyone implementation.
