### ISSUE TITLE
using go_package breaks package name

### ISSUE THREAD

**Issue by phemmer** [gogo/protobuf#664]
If you have a proto file with `package foo;`, and generate the go code, the resulting go file will also be in `package foo`.
However if you specify `option go_package = "github.com/acme/bar";`, the resulting go file will be in `package bar`.

The latter should not be happening. The go package path denotes the **path** to the package, not the package name itself. Lots of go packages have a package name different from the final component of their path. Commonly when the path is something "github.com/acme/go-foo", and the package name is just "foo".

**Comment by meling** [comment]
This is the expected behavior. See the documentation [here](https://developers.google.com/protocol-buffers/docs/reference/go-generated#package).

**Comment by phemmer** [comment]
Thanks, was unaware of that.

I was finding it necessary to use `go_package` to specify the fully qualified path to the package for some reason I really can't remember now. I think it was something related to importing from other proto files, and not working without. But unfortunately I don't recall what that difficulty was.
In the end, I used `option go_package` and `sed` go:generate commands to get everything working.

But as this is clearly documented, I'll close.
