### ISSUE TITLE
Is this Dead ?

### ISSUE THREAD

**Issue by ghost** [gogo/protobuf#676]
Just wondering if this project dead . Since the last commit on October 2019

**Comment by traian-schiau** [comment]
Same question here, I've opened a PR in Jan. https://github.com/gogo/protobuf/pull/659

**Comment by apelisse** [comment]
For what it's worth, last commit late last year doesn't mean it's dead, it's certainly still used :-)

**Comment by johanbrandhorst** [comment]
Sorry for the radio silence on this, we've been talking between us maintainers and have posted https://github.com/gogo/protobuf/issues/691.

**Comment by tonyboxes** [comment]
Why does this project exist? The project has created historical problems that cannot be solved.

**Comment by alexshtin** [comment]
Performance and convenience. For performance you can check my small bench repo: https://github.com/alexshtin/proto-bench. And generated code looks better and easier to use.
