### ISSUE TITLE
Bug: gofast does not support grpc and some doc for grpc would be nice

### ISSUE THREAD

**Issue by chakrit** [gogo/protobuf#68]
Like the title says. I have the file in this gist: https://gist.github.com/chakrit/9708ad015e85cbf4e7bf which is just a hello world service.

The command invoked is:

```sh
$ protoc --gofast_out=plugins=grpc:./src/generated *.proto
```

But the resulting Go file contains no mention of `Greeter` at all.

**Comment by chakrit** [comment]
Also can't find any mention abt grpc anywhere in the README or the doc pages.

**Comment by chakrit** [comment]
It seems that all the various generator binaries do not make any use of the `gRPC` plugin flag and only the `protoc-gen-gogo` actually output a gRPC interface (regardless of the flag.)

Had to look in the `letmegrpc` project sources to discover that.

**Comment by awalterschulze** [comment]
This is atleast tied to this issue
https://github.com/gogo/protobuf/issues/60

**Comment by awalterschulze** [comment]
I should add readme instructions as well.

**Comment by awalterschulze** [comment]
Yes it seems gofast does not support grpc.  This is a bug.

**Comment by awalterschulze** [comment]
bug fixed.
Now just some docs.

**Comment by awalterschulze** [comment]
Added a one line doc to the Readme.md

**Comment by awalterschulze** [comment]
Thanks again for reporting.
I have made some major oversights.
Sorry for the inconvenience.

**Comment by chakrit** [comment]
@awalterschulze thanks for fixing it so quickly :)

**Comment by awalterschulze** [comment]
My pleasure.  Thanks for reporting :)
