### ISSUE TITLE
gogo supporting google.golang.org/protobuf

### ISSUE THREAD

**Issue by yashrsharma44** [gogo/protobuf#697]
Does `gogo` supports https://pkg.go.dev/mod/google.golang.org/protobuf ?
I was trying to port `grpc_middlewares` to use the updated apiv2 of protobuf, but it seems that I am not able to compile files correctly. So does gogo support `google.golang.org/protobuf`?

**Comment by marbar3778** [comment]
gogoproto does not support apiv2. there is a larger discussion here: https://github.com/gogo/protobuf/issues/691 about this repo and other things for apiv2.

**Comment by ydnar** [comment]
You can potentially get it to work if you enable the Marshaler and Unmarshaler generation for all messages in your proto files.

**Comment by johanbrandhorst** [comment]
Lets move this discussion to #691
