### ISSUE TITLE
is there a way to do `type MyFoo string`?

### ISSUE THREAD

**Issue by cbarraford** [gogo/protobuf#715]
Trying to create a protobuf for a non-struct. Say i have a custom string type, such as...
```
type Password string
```

I'm creating a custom var type over `string` because i want to hang addition functions on it (for example, `func (p Password) IsValid() bool` check it meets the minimum password requirements).

But I can't seem to figure out how to get protobuf to create a type that is just a `string` (not a struct). Any means of doing so??

**Comment by marbar3778** [comment]
You will have to use a struct here, type aliasing is not possible. The wellknown types cover these simple structs.

**Comment by cbarraford** [comment]
bummer 🤔 thanks
