### ISSUE TITLE
add external structs

### ISSUE THREAD

**Issue by cbarraford** [gogo/protobuf#716]
Say i have a struct like the following... where "semver" is a struct of another repository I do not have control over (to use protobufs). How can I include this into my protobuf??

```
import (
    "github.com/blang/semver"
)

type MsgSetVersion struct {
    Version semver.Version    `json:"version"`
    Signer  cosmos.AccAddress `json:"signer"`
}
```

Here is my attempt at doing this...
```
syntax = "proto3";
package types;

option go_package = ".../types";

import "gogoproto/gogo.proto";

message MsgSetVersion {
  bytes version = 1 [(gogoproto.customtype) = "github.com/blang/semver.Version", (gogoproto.nullable) = false];
  bytes signer = 2  [(gogoproto.casttype) = "github.com/cosmos/cosmos-sdk/types.AccAddress"];
}
```

Any suggestions on how do work with an external struct like this?

**Comment by cbarraford** [comment]
using 
```
bytes version = 1 [(gogoproto.casttype) = "github.com/blang/semver.Version"];
``` 
generates the following errors...

```
.../types/msg_version.go:10:3: cannot use version (type string) as type semver.Version in field value
.../types/msg_version.pb.go:70:2: cannot use nil as type semver.Version in return argument
.../types/msg_version.pb.go:135:8: invalid argument m.Version (type semver.Version) for len
.../types/msg_version.pb.go:136:11: invalid argument m.Version (type semver.Version) for len
.../types/msg_version.pb.go:137:7: second argument to copy should be slice or string; have struct { Major uint64; Minor uint64; Patch uint64; Pre []semver.PRVersion; Build []string }
.../types/msg_version.pb.go:137:7: too many errors
```

**Comment by Megavolv** [comment]
> using
> 
> ```
> bytes version = 1 [(gogoproto.casttype) = "github.com/blang/semver.Version"];
> ```
> 
> generates the following errors...
> 
> ```
> .../types/msg_version.go:10:3: cannot use version (type string) as type semver.Version in field value
> .../types/msg_version.pb.go:70:2: cannot use nil as type semver.Version in return argument
> .../types/msg_version.pb.go:135:8: invalid argument m.Version (type semver.Version) for len
> .../types/msg_version.pb.go:136:11: invalid argument m.Version (type semver.Version) for len
> .../types/msg_version.pb.go:137:7: second argument to copy should be slice or string; have struct { Major uint64; Minor uint64; Patch uint64; Pre []semver.PRVersion; Build []string }
> .../types/msg_version.pb.go:137:7: too many errors
> ```

How did you manage to do this trick?
