### ISSUE TITLE
Bug: Generated code doesn't compile when importing a packaged called "index"

### ISSUE THREAD

**Issue by abustany** [gogo/protobuf#72]
The `Unmarshal` method generated for protobuf messages uses a variable called "index". If a package called "index" is also imported, one gets a naming conflict, and the generated code doesn't compile. One way to fix that would be to alias all generated imports to unique names so that there are no risks of conflicts.

**Comment by awalterschulze** [comment]
Good catch :)

**Comment by awalterschulze** [comment]
We can probably get away with just naming the index "keyword" to something that people are unlikely to use.  Like "iNdEx" :)
I am guessing there are a lot of these type of issues, but I think renaming all the variables with some method that does not conflict with the packageNames might be overkill.
If I get a lot of these kinds of reports I'll do something better.

**Comment by awalterschulze** [comment]
fixed
https://github.com/gogo/protobuf/commit/05b9dd05e2149cf01fd645b3dc550542556ddea7

**Comment by awalterschulze** [comment]
Might I ask where you are using gogoprotobuf?

**Comment by abustany** [comment]
Eh, your fix has the merit of being simple :-) Thanks a lot for the quick reply.

We're using gogoprotobuf in a proprietary project at work, so unfortunately not much I can tell about :-\ Except that gogoprotobuf is working great for us so far!

**Comment by awalterschulze** [comment]
Thank you.
That is great to hear :)
