### ISSUE TITLE
Bug: Compile Issue

### ISSUE THREAD

**Issue by hangyuancn** [gogo/protobuf#73]
if seems that the github.com/gogo/protobuf/proto has been updated ? I can't build successfully now:

rpc/codec/wire/wire.pb.go:299: undefined: proto.Skip
rpc/codec/wire/wire.pb.go:432: undefined: proto.Skip
# github.com/cockroachdb/cockroach/proto
proto/api.pb.go:934: undefined: proto.Skip
proto/api.pb.go:1189: undefined: proto.Skip
proto/api.pb.go:1310: undefined: proto.Skip
proto/api.pb.go:1377: undefined: proto.Skip
proto/api.pb.go:1471: undefined: proto.Skip
proto/api.pb.go:1562: undefined: proto.Skip
proto/api.pb.go:1629: undefined: proto.Skip
proto/api.pb.go:1747: undefined: proto.Skip
proto/api.pb.go:1814: undefined: proto.Skip
proto/api.pb.go:1896: undefined: proto.Skip
proto/api.pb.go:1896: too many errors

**Comment by awalterschulze** [comment]
My bad.
If the code is regenerated it should all work, but I forgot that not everyone is able to do that for every project they depend on.
I'm putting the function back.

**Comment by awalterschulze** [comment]
fixed https://github.com/gogo/protobuf/commit/58bbd41c1a2d1b7154f5d99a8d0d839b3093301a
