### ISSUE TITLE
Poor error message when gogoproto.embed = true is used incorrectly

### ISSUE THREAD

**Issue by vivekmenezes** [gogo/protobuf#74]
Create two protobuf field of type bytes. Use nullable=false, embed = true on one of them. See the error message below. Note the actual type is not printed as part of the error message. It took me a good 30 minutes to figure out the problem.

2015/06/22 16:18:00 protoc-gen-gogo: error:can't find object with type 
--gogo_out: protoc-gen-gogo: Plugin failed with status code 1.
sed: ./cockroach/proto//*.pb.go: No such file or directory
sed: ./cockroach/proto//*.pb.go: No such file or directory
sed: ./cockroach/proto//*.pb.go: No such file or directory

**Comment by awalterschulze** [comment]
Could you provide an example proto file please?

Or does this seem about right?

message TakesLongTooDebug {
  optional bytes Field1 = 1;
  optional bytes Field2 = 2 [(gogoproto.nullable)=false, (gogoproto.embed)=true)];
}

**Comment by vivekmenezes** [comment]
That example should give you the impossible to interpret error message.
Thanks

**Comment by awalterschulze** [comment]
This should fix it
https://github.com/gogo/protobuf/commit/d47746f9175faa5203b6adbadc06d9b8b9ea71bd
I think
```
ERROR: found embedded bytes field %s in message %s\n
```
is a better error message
