### ISSUE TITLE
Bug: nil pointers for structs in proto3

### ISSUE THREAD

**Issue by olegdunkan** [gogo/protobuf#75]
Hello!
Let we have this:

```
syntax = "proto3";
package main;
message Info {
  	string group = 1;
  	string key = 2;
	Card card = 3;
}
message Card {
	int32 number = 1;
	string bank = 2;
}
```
But there is no check for nil pointers in generated .pg.go file.
```
func (m *Info) MarshalTo(data []byte) (n int, err error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Group) > 0 {
		data[i] = 0xa
		i++
		i = encodeVarintScheme(data, i, uint64(len(m.Group)))
		i += copy(data[i:], m.Group)
	}
	if len(m.Key) > 0 {
		data[i] = 0x12
		i++
		i = encodeVarintScheme(data, i, uint64(len(m.Key)))
		i += copy(data[i:], m.Key)
	}
	data[i] = 0x4a
	i++
	i = encodeVarintScheme(data, i, uint64(m.CardBank.Size()))
	n1, err := m.CardBank.MarshalTo(data[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	return i, nil
}
```
That is why panic will occur in this code:
```
info := &Info{Group:"A", Key:"1"}
info.Marshal()
``` 
but if I use golang/protobuf all is fine, what I am doing wrong? Or you doesn't support this behavior for nil pointers?
I used last protoc and gofast.
Thank you.

**Comment by awalterschulze** [comment]
You have probably found a bug.  I'll check it out asap.  Thank you for reporting.

**Comment by awalterschulze** [comment]
That was quite a big bug.  Well done.
This should fix it https://github.com/gogo/protobuf/commit/db85e0662942d6d7c9a557ef95518f4359271357
My test generation had the same bug, that is why I didn't pick it up.
Thank you very very much for reporting! :+1:

**Comment by olegdunkan** [comment]
Hello, thanks. The same issue comes with maps. 

````
message Users {  
    map<string, User> list = 1;
}

message User {
    string name = 1;
    int32 age = 2;
}

GO:
users := &Users{List:make(map[string]*User)}
users.List["a"] = nil 
users.Marshal() // panic
````

**Comment by awalterschulze** [comment]
Thanks for reporting :)

**Comment by awalterschulze** [comment]
Seems like I also need to merge in some fixes from golang/protobuf before this will work perfectly.
I'll get to it soon, sorry for the delay.

**Comment by awalterschulze** [comment]
I started some work here
https://github.com/gogo/protobuf/tree/nilmaps

**Comment by awalterschulze** [comment]
Seems as though I should return an error instead of panicing

https://github.com/golang/protobuf/commit/cab84a34852dc030c7c849c8119488c839d51cba

**Comment by awalterschulze** [comment]
This should now be fixed
https://github.com/gogo/protobuf/commit/0c34f4f53b253dc0d31c5a178a6263b6517b7ca4
