### ISSUE TITLE
vanity and defaults are not really jelling.

### ISSUE THREAD

**Issue by tamird** [gogo/protobuf#78]
discovered in: https://github.com/cockroachdb/cockroach/pull/1317:

```
vanity.ForEachFieldInFiles(files, vanity.TurnOffNullableForNativeTypesOnly)
vanity.ForEachFile(files, vanity.TurnOffGoGettersAll)
```
Results in a spew of:
```
error:illegal default value:  client_streaming  in  MethodDescriptorProto  is not nullable and is thus not allowed to have a default value
```
--------------------------
```
// vanity.ForEachFieldInFiles(files, vanity.TurnOffNullableForNativeTypesOnly)
vanity.ForEachFile(files, vanity.TurnOffGoGettersAll)
```
Results in a spew of:
```
ERROR: field MethodDescriptorProto.ClientStreaming cannot have a default value and not have a getter method
```

**Comment by awalterschulze** [comment]
Seems like the errors are spot.

Although I guess the current convention does not really cover defaults in a sensible way.
Interesting hmmm.

**Comment by awalterschulze** [comment]
This should commit should fix this issue
https://github.com/gogo/protobuf/commit/c948aac0178a73864b46b0dd098cf9075947570c
