### ISSUE TITLE
Bug: UnmarshalMerge() + nullable int64 field

### ISSUE THREAD

**Issue by neilconway** [gogo/protobuf#80]
```
package test;

option (gogoproto.unmarshaler_all) = true;

message TestM {
  required int64 timestamp = 1 [(gogoproto.nullable) = false];
}
```

```
var msg test.TestM
for {
    // Fill buf
    _ := proto.UnmarshalMerge(buf, msg)
}
```

It is possible I'm misunderstanding the semantics of UnmarshalMerge(), but the program above behaves differently depending on whether `[(gogoproto.nullable) = false]` is set.

If the field is nullable, the previous value of msg.Timestamp is overwritten in each loop iteration (which is what I had intended). If the field is non-nullable, the previous content of msg.Timestamp is bitwise-OR'd with the previous content; this results in basically producing a corrupted msg.Timestamp in subsequent loop iterations. i.e., this generated code:

```
            for shift := uint(0); ; shift += 7 {
                if index >= l {
                    return io.ErrUnexpectedEOF
                }
                b := data[index]
                index++
                m.Timestamp |= (int64(b) & 0x7F) << shift
                if b < 0x80 {
                    break
                }
            }
```

My expectation was that because "timestamp" is a required field, the previous value would be overwritten by UnmarshalMerge() -- which is the observed behavior when the field is nullable.

**Comment by awalterschulze** [comment]
Welcome back, good to hear from you again, I thought you might have died :)

For interest sake, why are you using UnmarshalMerge?
I have never understood why anyone would use this function.  
I would really like to know about a real world use case.

So basically you want the generated code to be:
```
m.Timestamp = 0
for shift := uint(0); ; shift += 7 {
....
```

**Comment by neilconway** [comment]
Hi Walter,

Yes, that's the generated code I'd like to see.

Re: why I'm using UnmarshalMerge, my messages look like:

```
message M {
    required int64 f1 [(gogoproto.nullable) = false];
    repeated M2 f2 [(gogoproto.nullable) = false];
}
```

To deserialize a new message, I reset the f2 slice and then UnmarshalMerge(); this avoids reallocating a new backing store for the f2 slice on every message. Happy to hear suggestions if there's a better way to do this :)

**Comment by awalterschulze** [comment]
Ok that is a pretty cool use case.
Sounds like in this basic message that should help performance a lot, especially since f2 is also nullable=false.
For now though you could set f1 to zero yourself before merging, just until I fix this issue?
Seems like the actual repeated message unmarshal code is generated correctly for merging.

**Comment by awalterschulze** [comment]
This should fix the issue
https://github.com/gogo/protobuf/commit/de972354f2c5c1a4fac1944652ec70dd532d29a1

**Comment by neilconway** [comment]
Thanks for the prompt fix!
