### ISSUE TITLE
Doc: gofast cannot be used with any gogoproto extensions

### ISSUE THREAD

**Issue by nemothekid** [gogo/protobuf#81]
I'm trying to compile this proto file with protoc 2.6.1 (with gogoprotobuf @ 056e49a669ad72a638fd and golang/proto @ ab974be44dc3b7b8a) with 

```
protoc --proto_path=$GOPATH/src:$GOPATH/src/github.com/gogo/protobuf/protobuf:. --gofast_out=. queue/message.proto
```

```proto
package queue;

import "github.com/gogo/protobuf/gogoproto/gogo.proto";

message Message {
	required string name = 1 [(gogoproto.nullable) = false];
	required bytes key = 2;
	required bytes data = 3;
}
```

The generated `message.pb.go` fails to compile with:
```
message.pb.go:172: undefined: proto.NewRequiredNotSetError
message.pb.go:175: undefined: proto.NewRequiredNotSetError
message.pb.go:178: undefined: proto.NewRequiredNotSetError
message.pb.go:319: undefined: proto.NewRequiredNotSetError
message.pb.go:327: undefined: proto.NewRequiredNotSetError
```

Sample line in question from the generated file:
```go
if m.Data == nil {
	return 0, github_com_golang_protobuf_proto.NewRequiredNotSetError("data")
} else {
```

**Comment by nemothekid** [comment]
Fixed by using `--gogofast_out` instead - not sure if this is a bug or not, I'm not sure the docs make this distinction clear.

**Comment by awalterschulze** [comment]
Yes if you are going to use any extensions like especially nullable then you need to use a gogo out.
gofast is only for users who want nothing else except some extra speed.
Maybe this should be documented better though.

**Comment by mschoch** [comment]
I seem to be getting the same error, and I'm not using any extensions (to my knowledge).  Protoc 2.6.1, googprotobuf @ 8edb24c179ed858a38f18920d9005c2dde05ec17, golang/proto @ 68c687d

```
$ cat upside_down.proto 
message BackIndexTermEntry {
	required string term = 1;
	required uint32 field = 2;
}

message BackIndexStoreEntry {
	required uint32 field = 1;
	repeated uint64 arrayPositions = 2;
}

message BackIndexRowValue {
	repeated BackIndexTermEntry termEntries = 1;
	repeated BackIndexStoreEntry storedEntries = 2;
}
```

```
$ protoc --gofast_out=. upside_down.proto 
```

```
$ go build
# github.com/blevesearch/bleve/index/upside_down
./upside_down.pb.go:188: undefined: proto.NewRequiredNotSetError
./upside_down.pb.go:191: undefined: proto.NewRequiredNotSetError
./upside_down.pb.go:276: undefined: proto.NewRequiredNotSetError
./upside_down.pb.go:558: undefined: proto.NewRequiredNotSetError
./upside_down.pb.go:566: undefined: proto.NewRequiredNotSetError
./upside_down.pb.go:594: undefined: proto.NewRequiredNotSetError
```

**Comment by awalterschulze** [comment]
Could you report this as a separate issue.
This is an actual bug and not just a lack of documentation.
Basically a test with required fields is lacking and I should rather return a locally generated error in this case, in stead of a gogoprotobuf library specific error.

**Comment by mschoch** [comment]
The issue described in my comment has been moved to bug #90

**Comment by awalterschulze** [comment]
Please don't close this.
I don't think this should be closed until I write clearer documentation.

**Comment by awalterschulze** [comment]
I think this has now been solved with new readme.
