### ISSUE TITLE
gogofaster cannot be used with any gogoproto extensions

### ISSUE THREAD

**Issue by luan** [gogo/protobuf#82]
When using gogofaster it will try and make everything not nullable, which will then prevent you from having defaults. That's fine and expected, only problem being that when you import gogoproto extensions it will then import other protos that have defaults and explode:

```
2015/07/16 12:17:30 protoc-gen-gogo: error:illegal default value:  client_streaming  in  MethodDescriptorProto  is not nullable and is thus not allowed to have a default value
```

Is there something we can do so that protos defined in library files you import aren't converted with gogofaster so you can use both gogofaster and extensions?

**Comment by luan** [comment]
I believe the same is true for gogoslick, or anything that tries to use the all nullable feature in vanity.

**Comment by awalterschulze** [comment]
Are you only importing the library files or also generating their code?

**Comment by luan** [comment]
Only importing

**Comment by awalterschulze** [comment]
This commit should fix this issue
https://github.com/gogo/protobuf/commit/c948aac0178a73864b46b0dd098cf9075947570c
Thank you for reporting :)

**Comment by luan** [comment]
Awesome, thanks!
