### ISSUE TITLE
Bug: GoGoSlick/GoGoFast `proto3` nullable problem

### ISSUE THREAD

**Issue by mwitkow-io** [gogo/protobuf#85]
As discussed in:
https://github.com/gogo/protobuf/issues/57#issuecomment-124984289

I'm trying to generate the following file in proto3:
```proto
syntax = "proto3";

message AppId {
  string name = 1;
}
```
After doing:
`protoc -I . --gogoslick_out=plugins=grpc:. apps.proto`
I get:
```
ERROR: field AppId.Name is a native type and in proto3 syntax with nullable=false there exists conflicting implementations when encoding zero values--gogoslick_out: protoc-gen-gogoslick: Plugin failed with status code 1.
```

I would really prefer not to have to put nullable=False to each one of my fields. Does it make sense at all to have the concept of nullable in proto3 at all? The docs for proto3 explicitly state what the default values should be.

**Comment by awalterschulze** [comment]
This commit should fix the issue
https://github.com/gogo/protobuf/commit/33a491225609b307cd96dc6a1c3ad484a2ac5f3e

**Comment by mwitkow-io** [comment]
Great, thanks for the quick fix! :)
