### ISSUE TITLE
Bug: FuzzTests are sometimes throwing away unrecognized bytes

### ISSUE THREAD

**Issue by awalterschulze** [gogo/protobuf#91]
https://github.com/dvyukov/go-fuzz/pull/76

**Comment by awalterschulze** [comment]
https://github.com/gogo/fuzztests
More work is required.

**Comment by awalterschulze** [comment]
@dvyukov 
I fixed some fuzz tests for the generated unmarshaler
https://github.com/gogo/protobuf/commit/e8b9b26839019778c78d24936f79e919a1445e55#diff-6bca0143efa485acde512d77ff13d42f
Like so
https://github.com/gogo/protobuf/commit/e8b9b26839019778c78d24936f79e919a1445e55#diff-e0188cb7643b9790acd32abc395a5659
That these fuzztests found
https://github.com/gogo/fuzztests/tree/dd8509cb52dd1c848ba92335cff036fb6a6ac3d1

I did find that I could shrink the examples quite a bit to produce the same error.
If you look at TestFuzzSint64Overflow you can see the original bytes that produced the error commented out and the input bytes I used to reproduce the error which is a subset of the bytes in the original.

**Comment by dvyukov** [comment]
@awalterschulze Thanks, filed https://github.com/dvyukov/go-fuzz/issues/100

**Comment by awalterschulze** [comment]
Fixed another fuzz test failure
https://github.com/gogo/protobuf/commit/2093b57e5ca2ccbee4626814100bc1aada691b18
Found using this version of the fuzztests
https://github.com/gogo/fuzztests/tree/e62df375312286dd3e1e65abffef3a3407dcd6b0

**Comment by awalterschulze** [comment]
Maybe I am missing something
https://github.com/golang/protobuf/issues/77

**Comment by awalterschulze** [comment]
https://github.com/golang/protobuf/issues/76

**Comment by awalterschulze** [comment]
I think there has been enough fuzzing for now.
Comparing the errors from golang and gogo protobuf would be the next thing to do, but I think at least the current generated code is better now.
