### ISSUE TITLE
generated code changes when plugins are compiled with go1.5

### ISSUE THREAD

**Issue by tamird** [gogo/protobuf#92]
Looks like this is because plugins are registered using `init()`, and the load order has changed in 1.5, but I'm not sure.

**Comment by awalterschulze** [comment]
I think this problem has already been experienced here:
https://github.com/gogo/protobuf/pull/83
I asked that it is reported to golang/protobuf, but I haven't seen anything.
I should probably open this issue myself.

Is it just the order that has changed or are you experiencing compile errors?

**Comment by awalterschulze** [comment]
https://github.com/golang/protobuf/issues/57

**Comment by tamird** [comment]
Nope, no errors.

**Comment by awalterschulze** [comment]
Ok, but the problem is the generated code has a lot of diffs right?

**Comment by tamird** [comment]
Correct

**Comment by awalterschulze** [comment]
So the plugins should probably be sorted before generation begins.

**Comment by tamird** [comment]
Now that go 1.5 is released, this is about to become an issue o.O
