### ISSUE TITLE
Vote For New Feature: customname for enum value.

### ISSUE THREAD

**Issue by ceram1** [gogo/protobuf#94]
golang's naming convention does not match it of former languages.

Example usecase:
```
enum Corpus {
    UNIVERSAL = 0 [(gogoproto.customname)="Universal"];
    WEB = 1 [(gogoproto.customname)="Web"];
    IMAGES = 2; // ...
    LOCAL = 3; // ...
    NEWS = 4; // ...
    PRODUCTS = 5; // ...
    VIDEO = 6; // ...
  }
```

**Comment by awalterschulze** [comment]
You could always use
```
goproto_enum_prefix	Enum	bool	if false, generates the enum constant names without the messagetype prefix	true
```
And change the enum names to Universal etc.
Or is it required that the enum names be capitals in the proto file?

**Comment by ceram1** [comment]
Because currently I share proto files across  languages.
Is there any tool to sync multiple proto files?

**Comment by awalterschulze** [comment]
Fair enough, so think it would be easier to just change the names for go?

What do you mean with sync multiple proto files?

**Comment by ceram1** [comment]
I mean I want to sync changes. (mainly adding field) 
And may add some options based on language.

**Comment by awalterschulze** [comment]
sync changes with what?
If I understand git diff and apply will probably be your best bet.

**Comment by ceram1** [comment]
Sorry, english is not my primary language.

I don't want this
```
+-- service.go.proto
+-- service.java.proto
```
instead, I want
```
+-- service.proto
```

and for convenience, (including naming convention) I want to change name of UNIVERSAL to Universal only for golang.

**Comment by awalterschulze** [comment]
Ok yes thats fine, except for the feature: customname for enums, not existing yet.

**Comment by awalterschulze** [comment]
I am open to having the feature in gogoprotobuf, but finding the time to do it is a different question.

**Comment by ceram1** [comment]
I see it. Thank you for your prompt reply.

**Comment by awalterschulze** [comment]
You are also welcome to make a pull request.
I would recommend making a new extension enum_customname
