### ISSUE TITLE
New feature: field validator annotation

### ISSUE THREAD

**Issue by mwitkow-io** [gogo/protobuf#96]
We're currently thinking about moving our field value validation to `.proto` files to make it explicit what the contract is. For example:

```proto
message FooBar {
   string identifier = 1 [ gogo.validator.regexp = "[a-z0-9]{2,20}"]
   int32 magic_value = 2 [ gogo.validator.greater_than = "0"]
}
```

These would generate a `FooBar.Validate() error` function that would return `nil` if the field matches or a textual error for the reason of failure `magic_value must be greater than 0`.

Is that a feature they you would be willing to consider for GoGo? If so, can you provide pointers on where to start hacking and how to test it? :)

**Comment by awalterschulze** [comment]
Cool idea.
What field validation mechanism do you currently have?

This could maybe be done orthogonally to gogoprotobuf.
I would start by making my own proto file containing extensions similar to gogo.proto but with your own validation functions.
Next I would start writing a plugin that generates the validation methods.
Pick an example over here:  https://github.com/gogo/protobuf/tree/master/plugin
Once you have it working with standard go protocol buffers I would think about using this with gogoprotobuf custom types, nullable=false, customnames, etc.
One decision you will have to make is which programming languages you are going to support?

On the other hand I am actually working on a validator myself. https://github.com/katydid/katydid
v0.2 should be ready in a few months.  I only have really hard problem to solve and then its just some coding.
v0.1 is working in production, but it has a horrible syntax and no abstraction from the underlying automaton.
v0.2, currently on the prototype brach, will have a writable readable syntax, already has a combinator library.  The interpretation is already working very well.  I am working on compiling it down to an automaton that executes faster.  After which I will work on the syntax and optimising the automaton.

Obviously I would prefer you wait for katydid, but I still think this protocol buffer specific validation is really cool, depending on how many languages you support it might also be really quick and easy to implement.

**Comment by awalterschulze** [comment]
I am not against it.
Any thoughts?

**Comment by miekg** [comment]
I like the OP's idea, especially because it can be kept relative simple and thus fast.

The best way forward, I think, is it to code this with the pointers you gave and see how it works out in practice.

**Comment by awalterschulze** [comment]
OP's?

May I ask if and where you are using gogoprotobuf and if I may add you to the user list?

I think it should be relatively simple and fast to implement.
Validation would be quick, but you would have to unmarshal before you can validate, which has a cost.
I guess it depends on whether you validate before you marshal or after you unmarshal what you think the percentage of invalid structs are going to be.

**Comment by miekg** [comment]
OP - original poster - thought I try some hacker news lingo :)

**Comment by awalterschulze** [comment]
Ha ha, sorry I am very bad with lingo.

**Comment by mwitkow-io** [comment]
Apologies for lack of response, life got in the way ;)

We're using gogoprotobuf as the Go protobuf generator for our gRPC + REST framework (through gRPC Gateway). Our immediate problem is that certain fields in our protobufs contain names of resources or value ranges that have logical constraints (max string length, characters disallowed, max int value) we currently need to validate by hand. Typically we have a function like:

```go
func validateNode(node *pb_nodes.Node) error
```

in our gRPC service implementations. We use `.proto` files as the protocol documentation as well (generating Markdown docs), and keeping the  validator function logic in sync with the `.proto` comments is error prone. As such, we'd like it to be an auto-generated annotation.

Since the bulk of our public APIs are written in Go, we'd mostly use it these in Go. For other languages we can afford writing manual validators. Hence the idea to do it inside gogoprotobuf, as it already has some nice extensions.
We need to unmarshal the struct anyway, since that is what gRPC gives us. That's fine, since most structs will be valid, this is to catch user-errors when using our APIs. 

Initially we'd put the auto-generated `interface Validator { Validate() error}` methods instead of our custom validators. Down the line, we could put a on-RPC hook into the gRPC server that would call this on each message received and reject it if it doesn't validate.

We'd prefer to put this stuff into gogoprotobuf, as if feels like yet another "protobuf gadget" that would be useful for other people, but if you prefer we can make a separate protoc plugin.

**Comment by awalterschulze** [comment]
I also think having the validation spec with the proto spec makes a lot of sense and is a lot simpler to maintain.

Just as you need to inject the codec
https://github.com/gogo/protobuf/tree/master/codec
into grpc to fully take advantage of the extra possible speed gogoprotobuf provides you can also
have a codec with a validator.
That way it is actually possible to validate before or after unmarshaling.

I think this is a really cool gadget :)
I think the flexibility and readability of the validator extension will be important.
So I would prefer to first see a rough draft before I see something that is properly working.

Maybe gogo.validator should just regenerate a call to a function.
```
message FooBar {
   string identifier = 1 [ gogo.validator = "regexp.Match(\"[a-z0-9]{2,20}\")"]
   int32 magic_value = 2 [ gogo.validator = "myfolder/mylibrary.GreaterThan(0)"]
}
```
Damn there are so many ways to do this.

Maybe you would like to Skype of Hangout some time?

**Comment by mwitkow-io** [comment]
Oh yea, custom coded would be awesome! :)

In the #100 pull request (nice number :D), got a proposal that turns:

```proto
message ValidatorMessage {
	option (gogoproto.validator) = true;
	message Embedded {
		option (gogoproto.validator) = true;
		optional string Identifier = 1 [(gogoproto.validate) = {regex: "[a-z]{2,5}"}];
		required int64 SomeValue = 2 [(gogoproto.validate) = {int_gt: 0}];
	}
	required string Name = 1 [(gogoproto.validate) = {regex: ".{2,5}"}];
	repeated uint32 SomeValue = 2 [(gogoproto.validate) = {int_lt: 0}];
	optional uint32 Unvalidated = 3;

	optional Embedded embeddedOpt = 4;
	required Embedded embeddedReq = 5 [(gogoproto.nullable) = false];
}
```

Into validators like:

```go
var _regexValidatorMessage_Name = regexp.MustCompile(".{2,5}")

func (this *ValidatorMessage) Validator() error {
	if !_regexValidatorMessage_Name.MatchString(this.Name) {
		return fmt.Errorf("validation error: ValidatorMessage.Name must conform to regex '.{2,5}'")
	}
	for _, item := range this.SomeValue {
		if !(item < 0) {
			return fmt.Errorf("validation error: ValidatorMessage.SomeValue must be less than '0'")
		}
	}
	if this.EmbeddedOpt != nil {
		if msg, ok := this.EmbeddedOpt.(interface {
			Validator() error
		}); ok {
			if err := msg.Validator(); err != nil {
				return err
			}
		}
	}
	if msg, ok := this.EmbeddedReq.(interface {
		Validator() error
	}); ok {
		if err := msg.Validator(); err != nil {
			return err
		}
	}
	return nil
}

var _regexValidatorMessage_Embedded_Identifier = regexp.MustCompile("[a-z]{2,5}")

func (this *ValidatorMessage_Embedded) Validator() error {
	if !_regexValidatorMessage_Embedded_Identifier.MatchString(this.Identifier) {
		return fmt.Errorf("validation error: ValidatorMessage_Embedded.Identifier must conform to regex '[a-z]{2,5}'")
	}
	if !(this.SomeValue > 0) {
		return fmt.Errorf("validation error: ValidatorMessage_Embedded.SomeValue must be greater than '0'")
	}
	return nil
}
```

I decided to go with nested message options, and implement custom validators. There's also special case to pre-compile the regex with two advantages:
 * it will fail on load through `MustCompile`
 * it will be significantly more efficient

Thoughts? The biggest hurdle I've seen was checking whether a nested message contains a `Validator` itself, because I found no way to do it through Proto types. and used an expensive Go type check :(

**Comment by awalterschulze** [comment]
I think I answered your question about nesting in the pull request?

Yes I don't think my plan will ever have fail on load, which is a bit unfortunate.
Compiling once would still be possible using some memoizing.

This is hard, being specific has some clear advantages, but being generic will be much less maintenance work.

**Comment by awalterschulze** [comment]
Lots of validation frameworks have user defined functions, which is my version of generic functions.  Although I think jsonschema might have gotten away without it.

**Comment by awalterschulze** [comment]
I think we are discussing this in the pull request now, so I think it should be ok to close this.
