### ISSUE TITLE
Work In Progress: merge oneof support from https://github.com/golang/protobuf

### ISSUE THREAD

**Issue by tamird** [gogo/protobuf#99]
https://github.com/golang/protobuf/commits/master landed a few days ago

**Comment by awalterschulze** [comment]
I just need some time to think about all the implications surrounding the new oneof support.

**Comment by awalterschulze** [comment]
Started working on this on the oneof branch.
There is still quite a bit of work left.

**Comment by awalterschulze** [comment]
Waiting for https://github.com/golang/protobuf/issues/74
The rest of the work is complete on the oneof branch.

**Comment by tamird** [comment]
Nice! Thanks for all your work @awalterschulze.

**Comment by awalterschulze** [comment]
Yes it was quite a LOT of work.

**Comment by awalterschulze** [comment]
Merged :)
